### ISSUE TITLE
High and medium severity issues found in lodash 4.17.20

### ISSUE THREAD

**Issue by matt-primrose** [express-validator/express-validator#1003]
Snyk is reporting 2 issues with lodash 4.17.20:
https://snyk.devtools.intel.com/vuln/SNYK-JS-LODASH-1040724
https://snyk.devtools.intel.com/vuln/SNYK-JS-LODASH-1018905

These issues are fixed in 4.17.21.  Do you want me to submit a pull request upping the lodash version?

**Comment by matt-primrose** [comment]
Resolved in #1004

**Comment by fedeci** [comment]
We are not directly using `_.template` and regexes affected by ReDos attacks.
