### ISSUE TITLE
isStrongPassword() does not count '@' sign as a symbol

### ISSUE THREAD

**Issue by sang-uk-lee** [express-validator/express-validator#1006]
## Describe the bug

When validating a password string with the validation chain `isStrongPassword()`, a password string containing '@' sign does not pass the default `IsStrongPasswordOption` check nor a custom options check.

e.g.
```
{
  minLength: 8,
  minUppercase: 2,
  minLowercase: 2,
  minNumbers: 2,
  minSymbols: 1,
}
```

Validator.js recently updated (v13.5.2) and included an '@' sign in the validation regex [[Commit](https://github.com/validatorjs/validator.js/blob/deb1d1ef79fd60dfc60e7894db345df51eb409ee/src/lib/isStrongPassword.js
)] [[PR](https://github.com/validatorjs/validator.js/pull/1566)]. and think it's not a version issue.

### My validation chain used
```
static passwordInBody = (key: string): ValidationChain =>
  body(key)
    .isStrongPassword({
      minLength: 8,
      minUppercase: 1,
      minLowercase: 1,
      minNumbers: 1,
      minSymbols: 1,
    })
    .withMessage(
      'Must be at least 8 characters long, contain at least 1 uppercase, lowercase, number, and special characters',
    );
```

### Response after sending a request (value: 'AaA1b2bbbb@@@@@')
```
{
    "error": "Bad Request Error",
    "description": "Invalid request parameters provided",
    "payload": [
        {
            "value": "AaA1b2bbbb@@@@@",
            "msg": "Must be at least 8 characters long, contain at least 1 uppercase, lowercase, number, and special characters",
            "param": "password",
            "location": "body"
        }
    ]
}
```

## Expected behavior

`isStrongPassword()` counts '@' sign as a symbol, and one '@' sign in the regex should suffice one `minSymbols` value in IsStrongPasswordOptions.

## Current behavior

`isStrongPassword()` does not count '@' sign as a symbol.

## Express-validator version:

- Version: 6.10.0
* validator.js version (in my yarn.lock): 13.5.2

**Comment by fedeci** [comment]
Hi @sang-uk-lee, `v13.5.2` was released in December 2020, while the commit fixing the bug is from January 2021, so it is not yet live.
