### ISSUE TITLE
Add MongoDB object id validation

### ISSUE THREAD

**Issue by Yrkan** [express-validator/express-validator#1008]
I use express-validator very often alongside MongoDB and i often end up validating the MongoDB object id manually with mongoose `mongoose.Types.ObjectId.isValid,` would be great if we can do that from express-validator checks, something like isMongoId(). But I'm not sure if that's something you want to implement.

I am ready to work on this if it gets accepted.

**Comment by fedeci** [comment]
Hi @Yrkan, `isMongoId()` is already a validator. You can see all the standard validators [`here`](https://github.com/validatorjs/validator.js#validators). Furthermore there are some special ones you can find on [`express-validator docs`](express-validator.github.io)

**Comment by Yrkan** [comment]
Oh, it weird that it didn't show up in my code auto completion, but i tested and it worked.
Thanks @fedeci .
