### ISSUE TITLE
`errors.isEmpty` not working

### ISSUE THREAD

**Issue by prabormukherjee** [express-validator/express-validator#1011]
I am trying to validate the email, password and confirm password with `express-validator`. But it's accepting any value as password, not checking length, not even matching with confirm password. Simply it's not working.  
`"express-validator": "^6.10.0",`  
Here is the code: 
```
Router.post(
  "/signup",
  [
    check("email")
      .isEmail()
      .withMessage("Please enter a valid email")
      .custom((value, { req }) => {
        return User.findOne({ email: email }).then((userdoc) => {
          if (userdoc) {
            return Promise.reject("Email already exist");
          }
        });
      })
      .normalizeEmail(),
    body("password", "Please use a password longer than 7 characters").isLength(
      {
        min: 8,
      }
    ),
    body("confirmPassword").custom((value, { req }) => {
      if (value !== req.body.password) {
        throw new Error("Password have to match with confirm password");
      }
      return true;
    }),
  ],
  // another middleware..working good
);
```
I am expecting this is the problem with `express-validator`, as without codes from `[]` ,it is working

**Comment by fedeci** [comment]
Hi, why the title mentions `node`? Are you checking the validation errors using `validationResult`?

**Comment by prabormukherjee** [comment]
Actually I was using it with node.js  
Here is how I was checking. Also I used in other plasec and files, which are not working. Simply accepting everything
```
exports.postSignup = (req, res, next) => {
  const email = req.body.email;
  const password = req.body.password;
  const confirmPassword = req.body.confirmPassword;
  const errors = validationResult(req);
  if (!errors.isEmpty) {
    return res
      .status(422) //validation failed
      .render("auth/signup", {
        pageTitle: "Signup",
        path: "/signup",
        errorMessage: errors.array()[0].msg,
        oldInput: {
          email: email,
          password: password,
          confirmPassword: confirmPassword,
        },
        validationErrors: errors.array(),
      });
  }
// else logic
};```

**Comment by prabormukherjee** [comment]
Here is how I am importing them  
`const { validationResult } = require("express-validator");`
`const { check, body } = require("express-validator");`

**Comment by fedeci** [comment]
`isEmpty` is a method, you have to call it `errors.isEmpty()`. Otherwise it will always return `false` if used along with `!` because the function is defined.

**Comment by prabormukherjee** [comment]
Ooh, yes got it. My bad. Thanks for helping
