### ISSUE TITLE
Checkbox validation

### ISSUE THREAD

**Issue by TheKnown44** [express-validator/express-validator#1016]
Hi,

So I have a checkbox which I want users to check before they sign up "I agree to terms" checkbox.

I'm not exactly sure how to check if they have checked the checkbox. 

I have tried to use the `.notEmpty()` method but it doesn't really work for me.

What would be the correct way to check if a checkbox is checked using express-validator?

I would appreciate your suggestions. Thank you.

**Comment by fedeci** [comment]
Hi @TheKnown44, I assume you send to your backend a boolean value to indicate if the checkbox was checked or not, right?
You can use a custom validator like this:
```js
body('checkbox').custom(value => {
  // explicitly check for equality to true
  return value === true
})
```

**Comment by TheKnown44** [comment]
Hi @fedeci,

I do not send any boolean values. The values I get are `undefined` and `on`.

So I guess I could check if the value is `on`?

Like this:

```javascript    
body('checkbox')
    .custom(value => {
    if(value !== 'on') {
        throw new Error('err')
    } else {
        return value;
    }
})
```

**Comment by fedeci** [comment]
Exactly, but you should return `true` instead of `value`.

**Comment by TheKnown44** [comment]
Okay, changed it to `return true;`. Thank you!
