### ISSUE TITLE
Custom errors to send custom status codes

### ISSUE THREAD

**Issue by thernstig** [express-validator/express-validator#1018]
I am trying to implement a validation chain, where some errors should return 400 (with a specific message) but some other should return 403 (with a specific message). I have found no neat way to do this, as I handle all `validationResult(req)` at the end of the validation chain. It would be cool to be able set like `withStatus` that gets attached to the results, or maybe even `withCustom` to add custom things to it. Or maybe there is an easier, more intuitive way?

**Comment by fedeci** [comment]
Return status is not set from `express-validator`, it is totally up to the user to decide which error to return.
You may provide an object inside `withError()` specifying an error param. [Check this.](https://express-validator.github.io/docs/custom-error-messages.html#complex-errors)

**Comment by thernstig** [comment]
I just found this myself https://express-validator.github.io/docs/custom-error-messages.html#complex-errors and was about to close this. Thanks!

**Comment by thernstig** [comment]
@fedeci But how about using custom things in the message from e.g. the req object? For example it is quite common to log message as:

```js
logger.info(`Username ${req.param.username} invalid`);
```

It would be nice if the `withMessage(message: string)` had access to the `req` object. I find myself always want to give feedback to the user of what they tried to change.

**Comment by fedeci** [comment]
[Here](https://express-validator.github.io/docs/custom-error-messages.html#dynamic-messages) it is also that!😄

**Comment by fedeci** [comment]
.withMessage(({ req }) => {
  return { ... }
})
Does this work?

**Comment by thernstig** [comment]
Will try it when I get a chance, thanks.

**Comment by anbreaker** [comment]
Hello everyone,

This is my custom validator:

``` 
const emailExistOnDB = async (email) => {
  const emailExist = await User.findOne({ email });

  if (emailExist) throw new Error(`The email ${email}, already exists`);
};
```

and this is the middleware on route.

` check('email').custom(emailExistOnDB),`

If the email exists it returns the error of the emailExistOnDB function. But I want change de error status, 

How can I do it?

I have tried following [https://express-validator.github.io/docs/custom-error-messages.html#complex-errors](url)

But only But I just want to see the error code reflected in the json response.

```
{
    "errors": [
        {
            "value": "test1test.com",
            "msg": {
                "message": "Not an email",
                "errorCode": 202
            },
            "param": "email",
            "location": "body"
        }
    ]
}
```

I can't change the status in the response to send it via Postman or view it through the Morgan library.

Thank!

**Comment by fedeci** [comment]
There is no way to set the error code in the response through `express-validator`, you have to do it manually via `express`.

**Comment by anbreaker** [comment]
Thank you for your response,

I've been trying several things... (to try to understand) 

Could you suggest a way to do it? I am a junior dev.

In this link you can see an image of what I tried.

[https://ibb.co/Z8VRfGM](url)

**Comment by anbreaker** [comment]
Thank you very much, I did just what you told me, I created another middleware and this is the one that sends the status.

Other question, Would it be useful to implement something like this?

```
check('email').custom(...).withMessage('dasdf').withStatus(422)
```

I wouldn't mind trying to do it

**Comment by fedeci** [comment]
Accessing that error code would become the same as accessing an error code thrown with `withMessage`, so I don't think it could be helpful.
```js
check('email').custom(...).withMessage('dasdf').withStatus(422)
// same as
check('email').custom(...).withMessage({ message: 'dasdf', status: 422 })

```
