### ISSUE TITLE
multiple country phone number validaton

### ISSUE THREAD

**Issue by shekhawat777** [express-validator/express-validator#1024]
im tryng to validate mul,tiple country code how to do it 
 check('phone')
    .not()
    .isEmpty()
    .withMessage(CREATE_USER_PHONE_REQUIRED)
    .isMobilePhone('en-IN')

**Comment by fedeci** [comment]
Hi there, you can provide an array of locales to `isMobilePhone`.
```js
// e.g. 
.isMobilePhone(['en-IN', 'it-IT'])
```
Please check [validatorjs docs](https://github.com/validatorjs/validator.js/)

**Comment by shekhawat777** [comment]
thanks fedeci
