### ISSUE TITLE
Add options support to isAlphanumeric

### ISSUE THREAD

**Issue by trumankain** [express-validator/express-validator#1026]
isAlphanumeric is meant to support options in the same way that express-validator already supports them on isAlpha. I would like to add support for options on isAlphanumeric.

The validator docs list an identical description of `options` for both isAlpha and isAlphanumeric:
>options is an optional object that can be supplied with the following key(s): ignore which can either be a String or RegExp of characters to be ignored e.g. " -" will ignore spaces and -'s.

**Comment by fedeci** [comment]
Thanks! It's yours.

**Comment by trumankain** [comment]
Yes, only reason I didn't submit the other day was lack of unit testing. Will submit regardless.

**Comment by avala-HFI** [comment]
Just ran into this issue yesterday.  Can't say how thrilled I am to see a fix is already in the works @trumankain !
