### ISSUE TITLE
Using .if() Asynchronously

### ISSUE THREAD

**Issue by Garry14** [express-validator/express-validator#1028]
How to use .if() asnycly? 
ex : `body('blah').if((value, { req }) => {
  return db.Model.findOne({ where: { id:7 } }).then(dat => dat.uuid === req.body.theUuid) // I need to call model for uuid
})`

It doesn't work

Or if I use async in .if() : 

`body('blah').if(async (value, {req}) => {
 return false // Just return false
})`

It returns true, yet

I need to call db model, so can somebody help me, please?

**Comment by fedeci** [comment]
https://github.com/express-validator/express-validator/blob/c064a8e8762182546ed8efa231f2e5c1f2fb4f7a/src/context-items/custom-condition.ts#L7-L20

That's a bug. Do you want to fix it? It should be quite simple.

For the moment you can return `Promise.resolve()` or `Promise.reject()` instead of `true` or `false` when running `async`.

**Comment by Garry14** [comment]
> https://github.com/express-validator/express-validator/blob/c064a8e8762182546ed8efa231f2e5c1f2fb4f7a/src/context-items/custom-condition.ts#L7-L20
> 
> That's a bug. Do you want to fix it? It should be quite simple.
> 
> For the moment you can return `Promise.resolve()` or `Promise.reject()` instead of `true` or `false` when running `async`.

Thank you.. 

I've tried : 
`body('blah')
.if((value, { req }) => {
    return asyncFunction().then(data => {
        return Promise.resolve(false);
    })
})
.notEmpty().withMessage('Cannot Empty')
`

It still requires the input field blah (Cannot Empty)

**Comment by fedeci** [comment]
@Garry14 can you provide more details on the code you are running or a reproduction repo? Because I cannot replicate the error locally.

**Comment by Garry14** [comment]
### Describe The Bug
Using async function inside `.if()` 

### To Reproduce
```javascript
body('myfield') 
    .if(async (value, { req }) => {
        const checkRole = await db.Role.findOne({where: { id:2 }})
        if (checkRole) return req.body.user.role_id === checkRole.uuid
        else return false
    })
    .notEmpty().withMessage("My Field Cannot Empty")
```

### Expected Behavior
If the result is `false`, the `notEmpty()` is ignored, and if the result is `true`, the `notEmpty()` is unignored
as this documentation https://express-validator.github.io/docs/validation-chain-api.html#ifcondition

### Current Behavior
If it used `async` function, the return has to be `Promise.resolve()` and `Promise.reject()` instead of `true` and `false`

### Express Validator Version
Version: 6.10.1
