### ISSUE TITLE
How to get failed error type 

### ISSUE THREAD

**Issue by jensysantana** [express-validator/express-validator#1030]
Hi i'm trying to get the error type failed to validate:

This is what o have when validation fail but i want to know what kind of fail was. like: required or maxlength etc.
{
    value: undefined,
    msg: 'Invalid value',
    param: 'lname',
    location: 'body'
  }

I need something like this:

{
    value: undefined,
    msg: 'Invalid value',
    param: 'lname',
    location: 'body',
    king: 'required'
  }

**Comment by fedeci** [comment]
It is impossible for us to detect which option threw the error because [validatorjs](https://github.com/validatorjs/validator.js) doesn't give us any kind of information about that `e.g. isLength({ min: 10 })`. However we can add the generic validator that was unsuccessful `e.g. isLength`.

**Comment by jensysantana** [comment]
ok. thank you. I fixed I think I use a try catch block.

**Comment by fedeci** [comment]
You added trycatch around `check().isLength...`?

**Comment by gustavohenke** [comment]
As a suggestion, you can use `withMessage` to send error codes back to your frontend application, e.g. `check('name').isAlpha().withMessage('IS_ALPHA')`.
It may be a bit cumbersome, but allows for greater flexibility, in my opinion.

**Comment by gustavohenke** [comment]
Closing as it's been ~2 years since the last activity

Please open a new issue if needed.
