### ISSUE TITLE
isEmail is not rejecting when exclamation mark (!) is included

### ISSUE THREAD

**Issue by jasonlewicki** [express-validator/express-validator#1031]
## Describe the bug

the isEmail() method is not validating properly when an exclamation point is included in the string.

## To Reproduce

`example.hello!@gmail.com`
`await body("email_address").isEmail().run(request);`

## Expected behavior

a thrown error is expected

## Current behavior

returns `true`

## Express-validator version:

`^2.0.4`

**Comment by fedeci** [comment]
Hi there, this is not an issue with `express-validator`, but with [`validatorjs`](https://github.com/validatorjs/validator.js). Please report it to them.
