### ISSUE TITLE
The typescript type of matchedData

### ISSUE THREAD

**Issue by TitusEntertainment** [express-validator/express-validator#1041]
I can see that matchedData returns a Record, but I can't get access to the record nor the expected data from it.

Is there anyways to for example to Record<IMessage> so that TypeScript can know what the return data of the validator is?

**Comment by fedeci** [comment]
Actually no, because `matchedData` is evaluated at runtime, so we have no way to know the underlying types.

**Comment by cancan101** [comment]
FWIW https://github.com/af/envalid which parses + validates the env vars _does_ produce a typed response. Would be cool if there was some way to get `express-validator` to do that.
