### ISSUE TITLE
how to check user enter data is whether null?

### ISSUE THREAD

**Issue by tytom2003** [express-validator/express-validator#1050]
Below is my program.
```js
.post([
   check('user_name').isEmpty().withMessage('User Name is require').not().isNumeric().withMessage('Please fill in English in User Name'),
   check('user_mail').isEmpty().withMessage('Please fill in your email.'),
   check('user_password').isEmpty().withMessage('Please fill in user password').not().isLength({ min: 8 })
    .withMessage('Passowrd Password min 8 char').matches(/[a-zA-Z]{8,30}$/).withMessage('Password need uppercase and lowcase')
 ] ,userCtrl.userPost);
``` 

my program want to check user enter user_name is whether null, when i use "check('user_mail').isEmpty().withMessage('Please fill in your email.')". user_mail is null. it will not show "Please fill in user password". when i add not().).isEmpty(). it can show  "Please fill in user password".

                                       
 _________________________________not()|       no not()                                                     
 user_name is null   __|   show message  |  no show message 
user_name not null  |   show message  |   no show message

i want my program check user enter data is whether null. Then, it will show message.

Thank you very much.

**Comment by fedeci** [comment]
Hi there, validation chain items `isEmpty()`, `isLength`, etc...are what you want the value to BE.
If you add `isEmpty` you are expecting a value to be empty, not the opposite, so the validation will result in an error if the value is NOT empty.
So if you want to check that `user_email` is not empty, you have to do the opposite.
```js
check('user_email').exists({ checkNull: true }).withMessage('Email should exist').not().isEmpty().withMessage('Email should not be empty')
```
