### ISSUE TITLE
Is there any way to avoid unknown fields ?

### ISSUE THREAD

**Issue by parseshyam** [express-validator/express-validator#1051]
can we add configuration flag like allowUnknown: false/true hence by doing so we can totally avoid any security vulnerability that might cause disaster!
Here's the scenario : -

say my user model is

```
first_name: { type: STRING, allowNull: false },
last_name: { type: STRING, allowNull: false },
profile_pic: { type: STRING, defaultValue: null, allowNull: true, },
phone: { type: STRING(20), unique: true, allowNull: false },
phone_verified: { type: BOOLEAN, defaultValue: false, allowNull: false },
verify_code: { type: INTEGER, defaultValue: null    },
verify_exp: { type: BIGINT, defaultValue: null    },
```
say for user update if my validation schema is as below:-
```
body('first_name').trim().escape().matches(/^[a-zA-Z ]*$/).withMessage(USER.FIRST_NAME_ERR),
body('last_name').trim().escape().matches(/^[a-zA-Z ]*$/).withMessage(USER.LAST_NAME_ERR),
body('profile_pic').trim().isURL().optional()
```
and for any user - update route say i'm updating user-model like so:-
```
await User.update({ ...req.body }, { where: { id: req.user.id } });
```
If JSON data contain any fields which belongs to user model it'll get passed ( even though if it's not in our validation schema) hence the update query will update all fields that passed which could be disastrous.
if we can have a config field as mentioned allowUnknown: false/true defaults to false we could avoid this. JOI does the same if the field is not in validation schema it'll prompt with a message like 'xyz field' is not allowed.

**Comment by fedeci** [comment]
Have you solved this?

**Comment by parseshyam** [comment]
> Have you solved this?

No, but i guess i found some thing i could do in middelware check function like this:- 
Is there any alternative to do this ? Like what if there were like ( params or query params ) ?
```
export const validationCheck = (req: Request, res: Response, next: NextFunction) => {
    try {
        const errors: any = validationResult(req);
        
        ====== a patch ============
        const` data = matchedData(req);
        if (Object.values(req.body).length) {
            req.body = data;
        }
        ========================
        if (errors.isEmpty()) return next();
        const error: ICustomError = new Error(errors?.errors?.[0]?.msg);
        error.statusCode = 400;
        error.data = errors.array()
        throw error;
    } catch (error) {
        next(error)
    }
}
```

**Comment by fedeci** [comment]
Yes, `matchedData` is the right way, cause it is able to remove non-matched data. I'd suggest you to use it in your main middleware and not in `validationCheck`, and not to edit `req.body`.

See [docs](https://express-validator.github.io/docs/matched-data-api.html#matcheddatareq-options). (`locations` option helps you to match data from multiple locations all at once)
