### ISSUE TITLE
isURL returns error no 18 invalid url format on a url

### ISSUE THREAD

**Issue by charbelsako** [express-validator/express-validator#1056]
## Describe the bug

isURL returns error no 18 invalid url format on a perfectly good url

## To Reproduce

just use the isURL function to validate the user input.

1. 
2. 

## Expected behavior

to not return any error

## Current behavior

returns error as mentioned above

## Express-validator version:

- Version: 
Version: 6.12.0

**Comment by fedeci** [comment]
`isURL` is a wrapper to a [validatorjs](https://github.com/validator/validator) validator, so the issue unlikely is to be reported here. Could you attach the failing url please?

**Comment by charbelsako** [comment]
https://youtube.com

**Comment by fedeci** [comment]
I can't reproduce this. You should provide more details to help us understand the problem.

**Comment by developerbazaar1** [comment]
@fedeci  i got the same issue 

to reproduce use this 

`checkSchema({
  ratioJobTimeFrame: {
    in: ["body"],
    notEmpty: {
      errorMessage: "ratioJobTimeFrame is required",
    },
    trim: true,
    escape: true,
    custom: {
      options: (value) => {
        if (typeof value === "number" && value > 0) {
          return true;
        }
        if (typeof value === "string") {
          const numValue = parseFloat(value);
          if (!isNaN(numValue) && numValue > 0) {
            return true;
          }
        }
        throw new Error("ratioJobTimeFrame must be a positive number");
      },
    },
  },
  endPoint: {
    in: ["body"],
    notEmpty: {
      errorMessage: "endPoint is required",
    },
    isString: {
      errorMessage: "endPoint must be a string",
    },
    trim: true,
    escape: true,
    isURL: {
      errorMessage: "endPoint must be a valid URL",
    },
  },
});`  

This is request body value

```
{
  "ratioJobTimeFrame": 7,
  "endPoint": "https://clearstarttax-posting.ytel.space/x5/api/non_agent"
}
```

I'm getting this error 

`{
    "status": false,
    "message": "endPoint must be a valid URL"
}`

**Comment by charbelsako** [comment]
Same bug reported after 4 years, kinda funny

**Comment by gustavohenke** [comment]
In the case of @developerbazaar1, inspecting the whole error gives the answer:

```js
{
    type: 'field',
    value: 'https:&#x2F;&#x2F;chatgpt.com&#x2F;c&#x2F;67ea3cec-0634-8008-a1a9-257ada4a4bc9',
    msg: 'endPoint must be a valid URL',
    path: 'endPoint',
    location: 'body'
  }
```

The `escape` there is causing the URL to be invalid.
