### ISSUE TITLE
isDate() - what is considered an invalid value?

### ISSUE THREAD

**Issue by weirdyang** [express-validator/express-validator#1058]
```
  app:journals.controller     {
  app:journals.controller       value: '2021-07-01T09:35:47.628Z',
  app:journals.controller       msg: 'Invalid value',
  app:journals.controller       param: 'dateOfEntry',
  app:journals.controller       location: 'body'
  app:journals.controller     }
```
```
const reqChecks = [
  check('title').not().isEmpty().bail(),
  check('entry').not().isEmpty().bail(),
  check('dateOfEntry').isDate(),
];
```
Why is `value: '2021-07-01T09:35:47.628Z',` considered an invalid date?

**Comment by fedeci** [comment]
This package depends on [validatorjs](https://github.com/validatorjs/validator.js). You can find the regex for this validator there and eventually open an issue if you discover bugs.

**Comment by weirdyang** [comment]
For those who face this issue, the solution will be to use isISO8601.

see 

https://github.com/express-validator/express-validator/issues/146

https://github.com/express-validator/express-validator/pull/557
