### ISSUE TITLE
Argument of type 'readonly number[]' is not assignable to parameter of type 'any[]'

### ISSUE THREAD

**Issue by horyzont85** [express-validator/express-validator#1059]
## Describe the bug

When I use:
`check("foo").isIn(myArray)`
where myArray is readonly array then I got an error:

> Argument of type 'readonly number[]' is not assignable to parameter of type 'any[]'.
>   The type 'readonly number[]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.ts(2345)

## Expected behavior

isIn shouldn't report an error for readonly arrays.

## Express-validator version:

- Version: 6.12.0

**Comment by fedeci** [comment]
Hi @horyzont85, which version of typescript are you using? Could you share your `tsconfig.json`?

**Comment by gustavohenke** [comment]
The bug makes sense to me -- we use `readonly` arrays all the time at work. `readonly any[]` is different from `any[]`:
https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgJwQLhggpnAJuANgT3jHwG0BdGAXhhIEYAaGAJkYGYyBuAKADMBXMMCgBLcDBwBlEAFt0UABbCwAcwAUSgA58oqOMXIBKGAG8Avl0ky5ilasQIDHIA

**Comment by gustavohenke** [comment]
Fixed in v6.12.1.
