### ISSUE TITLE
How to use express-validator to validate two input files in the same form?

### ISSUE THREAD

**Issue by Eduardishion** [express-validator/express-validator#1060]

**Comment by fedeci** [comment]
Do you want to validate the files content?

**Comment by Eduardishion** [comment]
I have two input files of images, the first loads a single image, the second loads more than one image, and it gives me an underfined error when wanting to validate them, even though it has already added the images

**Comment by fedeci** [comment]
I am not used to multer, could you provide some code examples?

**Comment by fedeci** [comment]
Closing it because it is stale.
