### ISSUE TITLE
Get a method like 'isMongoId()' to validate that url param is a mongo db _id

### ISSUE THREAD

**Issue by filmspace** [express-validator/express-validator#1063]
Hey everyone , I was working with express-validator and mongoDB and i have to sometimes validate the mongoDB _id field many times. Wouldn't it be great a method like isUUID() is available for the mongoDB document _id.

**Comment by fedeci** [comment]
Hi there, `isMongoId()` already exists.
e.g.
```js
body('_id').isMongoId()
```
