### ISSUE TITLE
Express-Validator Does Not Fail When Using `checkSchema` and Default Validation API Tools

### ISSUE THREAD

**Issue by loganknecht** [express-validator/express-validator#1064]
# Gratitude

Hello! I really enjoy `express-validator` and appreciate it being a layer for sanitization/validation in `Express`. I really like not having to worry about this in the actual logic of the code, so your work is greatly appreciated.

# Problem

I feel like I understand how to use the `checkSchema` functionality, but I appear to be having some issues getting it successfully to fail.

I'm trying to accept a string of `comma-separated values` that is parsed into an array using the sanitizer and validator.

I've started with the validation piece first so my goal is to use `checkSchema`.

And it will run. But it doesn't seem to be using the default chain API tools provided by `express-validator`

I've read the documentation here
- https://express-validator.github.io/docs/schema-validation.html
- https://express-validator.github.io/docs/validation-chain-api.html

But there's not much to go off of. And I've searched extensively, but I cannot seem to find many resources that use the `checkSchema` functionality.

# Code Example

I have a set up like this for my app

```typescript
import express from "express";
import cors from "cors";
import { RoutesConfig } from "./common/routes-config";
import { AllRoutes } from "./example/all-routes";

const app: express.Application = express();
const port = 8080;
const routes: Array<RoutesConfig> = [];

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());

// set-up routes
// API V1 routes
const v1Router = express.Router();
routes.push(new EndpointRoutes(v1Router));
app.use("/api/v1", v1Router);

// default routes
app.use("/api", v1Router);

app.listen(port, () => {
    routes.forEach((route: RoutesConfig) => {
        console.log(`${route.getName()} configured.`);
    });
});
```

And how it works is we push custom routers into an array that we pass to the main `app` to use.

In the custom router is where I'm calling `checkSchema`
```typescript
// Third-Party
import express from "express";
import { checkSchema } from "express-validator";
// Custom
import { RegisterController, RegisterSchema } from "./register";
import { RoutesConfig } from "../common/routes-config";

class AllRoutes extends RoutesConfig {
    constructor(router: express.Router) {
        super(router, "DeviceRoutes");
    }

    configureRoutes(): express.Router {
        this.router.route("/register").post(checkSchema(RegisterSchema), RegisterController.Register);

        return this.router;
    }
}

export { DevicesRoutes };
```

And the schema part that I expect to fail should be happening because I am using this schema.
```typescript
import { Schema } from "express-validator";

const registerSchema: Schema = {
    serial_numbers: {
        in: ["body"],
        notEmpty: true,
        errorMessage: "serial_numbers MUST be a comma separated list of serial numbers",
        custom: {
            options: (value, { req, location, path }) => {
                console.log("CUSTOM");
                return value + req.body.foo + location + path;
            },
        },
    },
};

export { registerSchema };
```

But when I run it through `Postman` I get this back
![image](https://user-images.githubusercontent.com/1308524/125705891-c1c9723d-54fd-43bc-a5f9-31077e683405.png)

The `all good` comes from the controller itself here
```typescript
// Third-Party
import { Request, Response } from "express";
import { StatusCodes } from "http-status-codes";
// Custom
import {
    RegisterLocals,
    RegisterParamsDictionary,
    RegisterQuery,
    RegisterRequestBody,
    RegisterResponseBody,
} from "./dto";

class RegisterController {
    async Register(
        request: Request<
            RegisterParamsDictionary,
            RegisterResponseBody,
            RegisterRequestBody,
            RegisterQuery,
            RegisterLocals
        >,
        response: Response
    ): Promise<void> {
        console.log(request.body);
        console.log(request.body.serial_numbers);

        response.status(StatusCodes.OK).send("all good");
    }
}

export default new RegisterController();
```

And I've hooked up express to log out the response data, as well.

So I can see this in the logs:
```
CUSTOM
{ serial_numbers: '1' }
1
{
  meta: {
    req: {
      url: '/api/v1/register',
      headers: {
        'content-type': 'application/x-www-form-urlencoded',
        'user-agent': 'PostmanRuntime/7.28.1',
        accept: '*/*',
        'postman-token': '17703a0b-0d01-498a-a4e9-d89fc3da306c',
        host: 'localhost:8080',
        'accept-encoding': 'gzip, deflate, br',
        connection: 'keep-alive',
        'content-length': '16'
      },
      method: 'POST',
      httpVersion: '1.1',
      originalUrl: '/api/v1/register',
      query: {}
    },
    res: { statusCode: 200 },
    responseTime: 21
  },
  level: 'info',
  message: 'HTTP POST /api/v1/devices/unpin'
}
```

So I KNOW the `custom` keyword in the schema is being executed. Which means that
1. My request is making it
2. The request is being parsed correctly
3. The `express-validator` middleware is running

But it's not using the default validation api tools available OR it is using them and I'm really misunderstanding how they work?

# Conclusion

To re-iterate: I'm trying to accept a `string` of `comma-separated values` that will be parsed into an array and get passed to the controller where the actual logic will be performed.

I want to validate this string to make sure it's
- notEmpty
- isString
- isLength > 0 (probably the same as notEmpty)

What am I doing wrong? Do you see something I'm overlooking?

**Comment by loganknecht** [comment]
Figured it out.

I need to call `validationResult` in order to get anything to happen.

See below.

```
// Third-Party
import { Request, Response } from "express";
import { validationResult } from "express-validator";
import { StatusCodes } from "http-status-codes";
// Custom
import {
    RegisterLocals,
    RegisterParamsDictionary,
    RegisterQuery,
    RegisterRequestBody,
    RegisterResponseBody,
} from "./dto";

class RegisterController {
    async Register(
        request: Request<
            RegisterParamsDictionary,
            RegisterResponseBody,
            RegisterRequestBody,
            RegisterQuery,
            RegisterLocals
        >,
        response: Response
    ): Promise<void> {
        // ----------
        // Validation
        // ----------
        try {
            validationResult(request).throw();
        } catch (validation_error) {
            response.status(422).json(validation_error);

            // Short-Circuit and terminate
            return;
        }

        // ----------
        // Sanitization?
        // ----------
        // TODO

        // ----------
        // Processing
        // ----------
        response.status(StatusCodes.OK).send("all good");
    }
}

export default new RegisterController();
```


I leave this exercise only with one lesson.

I kind of wish the documentation was a little more explicit on the workflow of `checkSchema`.

**Comment by anthonyorona** [comment]
I agree, the documentation really needs complete examples.
