### ISSUE TITLE
Bypass validation by specifing same parameter multiple times

### ISSUE THREAD

**Issue by over-9k** [express-validator/express-validator#1065]
## Describe the bug

If you specify a query-parameter multiple times, you can bypass the validation. Not tested for other locations

## To Reproduce

1. Use simple validation as shown below 
`app.get('/',[query("test").isAlphanumeric()], (req,res,next) => {
  validationResult(req).throw()
  //something
})`

2. http://localhost:8000/?test=A&test=!! --> **passes**

## Expected behavior

Validation should fail, since express handles stuff like this as array. 
Should check every value of given array.
--> `{ test: [ 'A', '!!' ] }`

## Current behavior

Validation passes

## Express-validator version:

- Version: 6.12.0

**Comment by fedeci** [comment]
It is a known issue, it will be fixed in v7 (#1002).
For the moment if you expect `test` to be an array you should use wildcards like
```js
query('test.*').isAlphanumeric()
```
