### ISSUE TITLE
default() Sanitization does not work at checkSchema

### ISSUE THREAD

**Issue by alloyfang** [express-validator/express-validator#1068]
## Describe the bug

`
app.post("/default_test", body("def_val").default("abc"), c.test);
`
this works fine.
`
app.post("/default_test", checkSchema({
  def_val: {
    default: "abc"
  }
}), c.test)
`
this doesn't work
## To Reproduce

`
app.post("/default_test", checkSchema({
  def_val: {
    default: "abc"
  }
}), c.test)
`

## Expected behavior

req.body.def_val = "abc"

## Current behavior

no "dev_val" property in req.body

## Express-validator version:

- Version: 6.12.1

**Comment by fedeci** [comment]
Have you tried with the below?
```js
checkSchema({
  foo: {
    default: { options: "default" } 
  }
})
```
There is a PR to update the behaviour but it is stale😞
