### ISSUE TITLE
Allow simple extension of custom validators/sanitizers for better readability and reusability

### ISSUE THREAD

**Issue by ysfaran** [express-validator/express-validator#1077]
## Is your feature request related to a problem? Please describe.

When I add a custom validator, which I need to reuse, I usually create a function like this:

```js
export const isToken = (value) => {
  if (typeof value !== "string") {
    throw Error("Value must be a string");
  }

  if (!value.startsWith("0x")) {
    throw Error("Value  must start with '0x'");
  }

  if (value.length !== 42) {
    throw Error("Value must be 42 characters long");
  }

  return true;
};
```

Usage: 

```js
body("token").custom(isToken),
```

I use the snippet `custom(isToken)` above for a lot of validations and also reuse it for different middlewars like `param` instead of `body`. This unfortunatley breaks the cleanness of the fluent api and makes it harder to read. You also need to import `isToken` everywhere you use it. For `customSanitizer` it's quite similar.

## Describe the solution you'd like

`express-validator` should allow to extend it's validators/sanitizers in an easier way, similiar to how `jest` does it with [`expect.extend`](https://jestjs.io/docs/expect#expectextendmatchers).

A good solution would be to export new functions from the library:

```js
import { extend } from "express-validator";
```

which will allow to add custom validators and sanitizers:

```js
extend.validators({
  isToken,
});

extend.sanitizers({
  toSomeSanitizer: /*..*/,
});
```

Usage afterwards:

```js
body("token").isToken().toSomeSanitizer(),
```

With this solution the API would look much cleaner and it would simplify reusability in contrast to `custom` or `customSanitizer`.

## Implementation Idea

The feature could be implemented by extending the `prototype` of https://github.com/express-validator/express-validator/blob/690cd636df27cd5d32ad4f0e3f6ca783d86f873f/src/chain/validators-impl.ts#L8

```js
export const extend = {
  validators(customValidators){
    for([name, validator] of Object.entries(customValidators)){
      // note: currently this.custom doesn't seem to support options
      ValidatorsImpl.prototype[name] = function(options) { return this.custom(validator, options); }
    }
  }
}
  
  // sanitizers() ...
}
```
It should also be supported to pass options to custom validators, e.g.:

```js
export const isToken = (value, { length = 42 } = {} ) => {
  // ...

  if (value.length !== length) {
    throw Error(`Value must be ${length} characters long`);
  }

  return true;
};

body("token").isToken({ length: 18 }),
```

(I just had a rough look into to the code and there might be better ways to implement it. Feel free to suggest more appropriate solutions.)

**Comment by fedeci** [comment]
I completely agree with you about this feature requirement, it is in the v7 roadmap right now, we just need to implement a solution😄

**Comment by ysfaran** [comment]
@fedeci great 😄  is the road map publicly visible somewhere?

**Comment by fedeci** [comment]
Yes #990

**Comment by gustavohenke** [comment]
This is now possible in v7.0.0!
[Check out docs here](https://express-validator.github.io/docs/guides/customizing#the-expressvalidator-class)
