### ISSUE TITLE
URL validator has an issue

### ISSUE THREAD

**Issue by henoktsegaye** [express-validator/express-validator#1078]
okay so the problem is when validating URL like
```https://exmple.33.com```
the validator seems to fail at this point. 

```query('url').isUrl()``` will fail

**Comment by fedeci** [comment]
Can I assume that the request you are handling is something similar to this `http://abc.com?url=https://exmple.33.com` (with the url value escaped)?

**Comment by henoktsegaye** [comment]
yes its a get request

**Comment by fedeci** [comment]
I can't replicate the bug. Can you create a reproduction repo to help me debug it?

**Comment by fedeci** [comment]
Closing this as stale
