### ISSUE TITLE
Whole body validation

### ISSUE THREAD

**Issue by jooohny** [express-validator/express-validator#1081]
Is there a way to proceed the whole body validation but like in middleware function where I get the whole body at my disposal and do whatever I want with it? I need all the fields at once cuz I need to realize pretty complicated validation and sanitizing. Besides I never know what specific fields the body will have.

**Comment by fedeci** [comment]
Is `.custom(validatorFn)` what you where looking for?
I can't understand well what you mean by whole body validation, an example would probably help.

**Comment by jooohny** [comment]
> Is `.custom(validatorFn)` what you where looking for?
> I can't understand well what you mean by whole body validation, an example would probably help.

Yes, that's what I need. Thank you!
