### ISSUE TITLE
Validating a union type in a modular way

### ISSUE THREAD

**Issue by AlexZeitler** [express-validator/express-validator#1084]
I have a discriminated union like this:

```ts
type UnionCaseA = {
  type: 'UnionCaseA'
  propertyX: string
}

type UnionCaseB = {
  type: 'UnionCaseB'
  propertyY: number
}
```

I have validation for `UnionCaseA`:

```ts
const validateUnionCaseA = (): ValidationChain[] => {
  return [
    body('propertyX').notEmpty().withMessage('is required').isString().trim()
  ]
}
```

I have a test for it:

```ts
describe('validateUnionCaseA', (): void => {
  it('should validate "propertyX"', async () => {
    const req = createRequest({
      headers: {
        'accept-language': 'de-DE'
      },
      body: {
        type: 'UnionCaseA'
      }
    })
    await testExpressValidatorMiddleware(
      req,
      createResponse(),
      validateUnionCaseA()
    )

    const result = validationResult(req)
    result
      .array()
      .filter((i) => i.msg === 'is required')
      .length.should.equal(1)
  })
})
```

This test succeeds.

Next, I have a validation for the Union Type itself:

```ts
const validateUnion = (): ValidationChain[] => {
  return [
    body('type').custom(async (value: string, { req }) => {
      const result = await check('type')
        .isIn(['UnionCaseA', 'UnionCaseB'])
        .withMessage('Must be "UnionCaseA" or "UnionCaseB"')
        .run(req)

      const isValid = result.isEmpty()
      if (!isValid) return [result]

      switch (value) {
        case 'UnionCaseA':
          return validateUnionCaseA()
        case 'UnionCaseB':
          return validateUnionCaseB()
      }
    })
  ]
}
```

There's a succeeding test as well:

```ts
describe('validateUnion', (): void => {
  it('should validate "type"', async () => {
    const req = createRequest({
      body: {
        type: ''
      }
    })
    await testExpressValidatorMiddleware(req, createResponse(), validateUnion())

    const result = validationResult(req)
    result
      .array()
      .filter((i) => i.msg === 'Must be "UnionCaseA" or "UnionCaseB"')
      .length.should.equal(1)
  })
})
```

However, when I'm trying to test the union including its cases in a modular manner (the `switch` statement inside `validateUnion`), this test fails

```ts
it('should validate "UnionCaseA"', async () => {
    const req = createRequest({
      body: {
        type: 'UnionCaseA'
      }
    })
    await testExpressValidatorMiddleware(req, createResponse(), validateUnion())

    const result = validationResult(req)
    result
      .array()
      .filter((i) => i.msg === 'is required')
      .length.should.equal(1)
  })
```

`result.array()` is empty.

Looks like I'm doing something wrong but after a day of debugging I'm still not getting it.

I've created a repro here: https://github.com/AlexZeitler/express-validator-nested-repro

**Comment by fedeci** [comment]
> ```ts
> const validateUnion = (): ValidationChain[] => {
>   return [
>     body('type').custom(async (value: string, { req }) => {
>       const result = await check('type')
>         .isIn(['UnionCaseA', 'UnionCaseB'])
>         .withMessage('Must be "UnionCaseA" or "UnionCaseB"')
>         .run(req)
> 
>       const isValid = result.isEmpty()
>       if (!isValid) return [result]
> 
>       switch (value) {
>         case 'UnionCaseA':
>           return validateUnionCaseA()
>         case 'UnionCaseB':
>           return validateUnionCaseB()
>       }
>     })
>   ]
> }
> ```
Does this work, instead?
```ts
const validateUnion = (): ValidationChain[] => {
  return [
    body('type')
        .isIn(['UnionCaseA', 'UnionCaseB'])
        .withMessage('Must be "UnionCaseA" or "UnionCaseB"')
        .bail()
        .custom(async (value: string, { req }) => {
          switch (value) {
          case 'UnionCaseA':
            return validateUnionCaseA()
          case 'UnionCaseB':
            return validateUnionCaseB()
          }
        })
  ]
}
```
If it does there are some other ways you could achieve this using just a `custom` validator. For example you may throw `'Must be "UnionCaseA" or "UnionCaseB"'` in the `default` switch case.

**Comment by AlexZeitler** [comment]
> 
> Does this work, instead?
> 
> ```ts
> const validateUnion = (): ValidationChain[] => {
>   return [
>     body('type')
>         .isIn(['UnionCaseA', 'UnionCaseB'])
>         .withMessage('Must be "UnionCaseA" or "UnionCaseB"')
>         .bail()
>         .custom(async (value: string, { req }) => {
>           switch (value) {
>           case 'UnionCaseA':
>             return validateUnionCaseA()
>           case 'UnionCaseB':
>             return validateUnionCaseB()
>           }
>         })
>   ]
> }
> ```
> 
> If it does there are some other ways you could achieve this using just a `custom` validator. For example you may throw `'Must be "UnionCaseA" or "UnionCaseB"'` in the `default` switch case.

@fedeci thanks for your answer. No, `result.array()` is still empty but the existing and already successful tests arent`t broken.

**Comment by AlexZeitler** [comment]
What does work as an experiment:

```typescript
return [
    body('type')
      .isIn(['UnionCaseA', 'UnionCaseB'])
      .withMessage('Must be "UnionCaseA" or "UnionCaseB"')
      .bail()
      .custom(async (value: string, { req }) => {
        throw new Error('is required')
      })
  ]
```

It looks like the `.custom` function doesn't handle the `ValidationChain` returned by `validateUnionCaseA()` properly (or I'm doing it wrong).

**Comment by fedeci** [comment]
Oh, I haven't seen that you are returning validation chains from those two methods. We do not support returning an array of `ValidationChain` from custom validators. You have to run those imperatively, instead.

```ts
return [
    body('type')
      .isIn(['UnionCaseA', 'UnionCaseB'])
      .withMessage('Must be "UnionCaseA" or "UnionCaseB"')
      .bail()
      .custom(async (value: string, { req }) => {
        switch (value) {
          case 'UnionCaseA':
            return body('propertyX').notEmpty().withMessage('is required').isString().trim().run(req),
          case 'UnionCaseB':
            return ...
          }
      })
  ]
```

**Comment by AlexZeitler** [comment]
Thanks, this way it works.

My solution now looks like this - do you see any room for improvements?
That way I can run `validateUnionCaseA` in a non imperative way or in the context of a custom validator.

```typescript
const validateUnionCaseA = async (
  req?: Request
): Promise<ValidationChain[]> => {
  const chain = [
    body('propertyX').notEmpty().withMessage('is required').isString().trim()
  ]
  if (req) {
    for (const validation of chain) {
      await validation.run(req)
    }
  }
  return chain
}

const validateUnion = (): ValidationChain[] => {
  return [
    body('type').custom(async (value: string, { req }) => {
      const result = await check('type')
        .isIn(['UnionCaseA', 'UnionCaseB'])
        .withMessage('Must be "UnionCaseA" or "UnionCaseB"')
        .run(req)

      const isValid = result.isEmpty()
      if (!isValid) return [result]

      switch (value) {
        case 'UnionCaseA':
          return validateUnionCaseA(req)
        case 'UnionCaseB':
          return validateUnionCaseB()
      }
    })
  ]
}

describe('validateUnionCaseA', (): void => {
  it('should validate "propertyX"', async () => {
    const req = createRequest({
      headers: {
        'accept-language': 'de-DE'
      },
      body: {
        type: 'UnionCaseA'
      }
    })
    await testExpressValidatorMiddleware(
      req,
      createResponse(),
      await validateUnionCaseA()
    )

    const result = validationResult(req)
    result
      .array()
      .filter((i) => i.msg === 'is required')
      .length.should.equal(1)
  })
})

describe('validateUnion', (): void => {
  it('should validate "type"', async () => {
    const req = createRequest({
      body: {
        type: ''
      }
    })
    await testExpressValidatorMiddleware(req, createResponse(), validateUnion())

    const result = validationResult(req)
    result
      .array()
      .filter((i) => i.msg === 'Must be "UnionCaseA" or "UnionCaseB"')
      .length.should.equal(1)
  })

  it('should validate "UnionCaseA"', async () => {
    const req = createRequest({
      body: {
        type: 'UnionCaseA'
      }
    })
    await testExpressValidatorMiddleware(req, createResponse(), validateUnion())

    const result = validationResult(req)
    result
      .array()
      .filter((i) => i.msg === 'is required')
      .length.should.equal(1)
  })
})
```

**Comment by fedeci** [comment]
The first part of `validateUnion` (up to the switch) still does not make sense to me :)
You are not checking `.isValid()` from a `validationResult` object, but from a `Promise.resolve()` which does not contain that method. I'd go with the approach suggested in the [previous answer](https://github.com/express-validator/express-validator/issues/1084#issuecomment-903923158) because you don't need to run the first check imperatively.
Also consider checking out [`oneOf`](https://express-validator.github.io/docs/check-api.html#oneofvalidationchains-message) middleware that does what you are trying to do in this issue.

**Comment by AlexZeitler** [comment]
Thanks, this has been a copy/paste issue.
