### ISSUE TITLE
How to use CheckSchema to validate isPostalCode

### ISSUE THREAD

**Issue by fngch** [express-validator/express-validator#1085]
Hi folks,
I am using checkSchema to validate request body, unsure how to define the  schema for those validators with locale, it is fine by using check(...).isPostalCode( the options automatedly popup here, but in the checkSchema,it  does not, and not accepted passing 'US', and did not find a way to reference to type PostalCodeLocale in the schema definition.

Any help would be appreciate.

Charles F

**Comment by fedeci** [comment]
Hi there, have you tried passing the `options: 'YOUR_LOCALE'`?
I know it is really annoying but we are (slowly 😞) working to fix it, there is a PR for v7 if I am not wrong.
```js
checkSchema({
	foo: {
		isPostalCode: {
			options: 'US'
 		}
	}
})
```

**Comment by fngch** [comment]
Tried it, works fine now, thank you very much!
