### ISSUE TITLE
Docs have an example that promotes bad practice

### ISSUE THREAD

**Issue by finction** [express-validator/express-validator#1087]
## Describe the bug

https://express-validator.github.io/docs/custom-validators-sanitizers.html

On this page there is an example where it is checked if an email is already in use by accessing a data repository from a validator. Practice like this is bad as you'll only get a validation error if your database connection is dead for example. Proper error handling in such cases could be problematic. Issue described here: 

https://stackoverflow.com/questions/69136203/service-data-layer-exception-handling-in-express-validator/69136384#69136384

Business logic related validation and error handling should happen in the service layer: 
https://stackoverflow.com/questions/16394296/in-which-layer-should-validation-be-performed

## Suggestion:

Add a note on the docs page of the implications of accessing the data layer from a validator.

**Comment by fedeci** [comment]
I agree with you. Furthermore in that page we are promoting the usage of [not-yet validated data](https://express-validator.github.io/docs/custom-validators-sanitizers.html#example-checking-if-password-confirmation-matches-password), we should change that too. Marking it as a good first issue!
