### ISSUE TITLE
Middleware fail fast

### ISSUE THREAD

**Issue by NeverwinterMoon** [express-validator/express-validator#1100]
I managed to find a way to fail-fast the validation chain with bail, but what about failing fast the middleware list?

Say, I have 

```javascript
.post(
  '/somewhere',
  body('name').exists(),
  body('phoneNumber').exists(),
  handleStuff
)
```

If the name validation fails, I don't care to check phoneNumber anymore... Wasn't able to find a way to fail fast in this case. In the case above, if both validations fail, I will get errors for both of them.

**Comment by fedeci** [comment]
Hi there, there is currently no way to accomplish what you are trying to.
This should be however fairly easy to implement directly in the check middleware or as a `ValidationChain` method (we need to bail early if the context contains errors) so I am marking this as a first good issue. We can discuss hereby about the implementation.

**Comment by kuldp18** [comment]
Hi @fedeci, I would like to work on this issue. Some guidance on how to solve this problem will be appreciated since I'm new to this type of stuff.

**Comment by Tariqu** [comment]
I think we could throw the error and can prevent the calling next function or we can call the next with and error argument

**Comment by tejastomarbyte** [comment]
I would like to work on this issue!

**Comment by gustavohenke** [comment]
hi @tejastomarbyte, take a look at #1214 🙂 
Any comments or improvements are welcome!

**Comment by gustavohenke** [comment]
Hi hi, https://github.com/express-validator/express-validator/releases/tag/v7.0.0 is out with a fix for this 🙂
