### ISSUE TITLE
Bump validator to 13.7.0

### ISSUE THREAD

**Issue by tux-tn** [express-validator/express-validator#1106]
Hello guys,

Validator [13.7.0](https://github.com/validatorjs/validator.js/releases/tag/13.7.0) has been published last week and is fixing two ReDOS vulnerabilities in `rtrim` and `isMagnetURI` that may affect `express-validator`.

I can work on it if nobody is already preparing a PR

**Comment by fedeci** [comment]
I was planning to do it two days ago, but I am super messed with Fig and school stuff and I have no time. Would love a PR!

**Comment by tux-tn** [comment]
Sorry didn't get back to you! I will gladly take the issue if you didn't start working on it yet.

**Comment by fedeci** [comment]
Thanks!

**Comment by fedeci** [comment]
@tux-tn have you started implementing this one? I can do it today and tomorrow.

**Comment by tux-tn** [comment]
Really sorry, i started working on it but didn't finish all the changes, work and personal stuff took all my time 😓  Feel free to take the PR. I don't want to delay this change.

**Comment by fedeci** [comment]
👍
