### ISSUE TITLE
Add (value, {req}) in isAfter and isBefore as optional value

### ISSUE THREAD

**Issue by fncolon** [express-validator/express-validator#1107]
## Is your feature request related to a problem? Please describe.

Sometimes we want to check date with other date fields, is it nice to have optional (value, {req}) in isAfter and isBefore instead of date string?

## Describe the solution you'd like

Add (value, {req}) in isAfter and isBefore as optional value

**Comment by fncolon** [comment]
related to https://github.com/validatorjs/validator.js/issues/1864

**Comment by fedeci** [comment]
Hi there! What do you mean by `isAfter` and `isBefore`? To have the possibility to access the value before and after that it is transformed to a string? I suppose you are referring to `.custom()` validator, right?

**Comment by fncolon** [comment]
> Hi there! What do you mean by `isAfter` and `isBefore`? To have the possibility to access the value before and after that it is transformed to a string? I suppose you are referring to `.custom()` validator, right?

I mean something like this, more efficient than using custom

```js
isAfter(({req}) => req.body.another_date_field);
```

**Comment by fedeci** [comment]
I can't get what you mean by `isAfter`, what should the method do?

**Comment by fncolon** [comment]
> I can't get what you mean by `isAfter`, what should the method do?

Receive callback of request and the current input value instead of date string value.

**Comment by fedeci** [comment]
`.custom` does exactly what you intend to do.

**Comment by fncolon** [comment]
> `.custom` does exactly what you intend to do.

it is more efficient.

**Comment by fedeci** [comment]
What is more efficient? What should do the implementation of `isAfter` and `isBefore`. Please, explain.

**Comment by fncolon** [comment]
> What is more efficient? What should do the implementation of `isAfter` and `isBefore`. Please, explain.

I think you should drink more water and read carefully what I explain above. Btw we are on the same age. Nice to meet you.

**Comment by fedeci** [comment]
I misread everything 🤦‍♂️. You meant a `Date` object. I would say that `isAfter` and `isBefore` is not the best choice of naming😆. I would not add such a specific validator to this library, it is designed to work on top of validatorjs (apart from a particular methods), so you should ask there to add the functions. However you can easily achieve that result using custom without boilerplate.
```js
const isBeforeDate((value, { req }) => { 
  // perform check
})

body('date_field').custom(isBeforeDate)
```
Sorry for the misunderstanding :)
Nice to meet you too.
