### ISSUE TITLE
can not read req.params

### ISSUE THREAD

**Issue by hjiseong** [express-validator/express-validator#1108]
## Describe the bug

When I use matchedData function, I can not read params attributes.

## To Reproduce

1. Request email confirmation url. - /user/emailConfirmation/12345

## Current behavior

I expect token url value.
const { token } = req.params; // 12345
const { token } = matchedData(req) as Params; (interface Params { token: string; }) // undefined

## Environment:

- Express-validator version: 6.13.0
- Express version: 4.17.1

**Comment by gustavohenke** [comment]
Hi @hjiseong, what does your validation code look like?

**Comment by gustavohenke** [comment]
Closed as it's stale.
