### ISSUE TITLE
.matches does not work correctly?!

### ISSUE THREAD

**Issue by DavideViolante** [express-validator/express-validator#1109]
## Describe the bug
`.matches` does not seem to work correctly, or am I doing a silly mistake somewhere?

## To Reproduce
```js
const express = require('express');
const { check, validationResult } = require('express-validator');

const app = express();
const port = 3001;

app.post('/test', async (req, res, next) => {
  await check('example').matches(/hello/).run(req); // same for [A-z0-9]+/g or any other regexp
  const result = validationResult(req);
  if (!result.isEmpty()) {
    return res.status(400).json({ errors: result.array() });
  }
  res.send('tested');
});

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`);
});
```

## Expected behavior

`curl -X POST 'localhost:3001/test' --data '{"example":"hello"}'`
to return `tested`

## Current behavior

`curl -X POST 'localhost:3001/test' --data '{"example":"hello"}'`
returns `{"errors":[{"msg":"Invalid value","param":"example","location":"body"}]}`

## Environment:
```
"dependencies": {
  "express": "^4.17.1",
  "express-validator": "^6.13.0"
}
```

**Comment by gustavohenke** [comment]
curl doesn't post as JSON by default.
You have to explicitly set the content-type as JSON so that express knows how to parse it.

---

Here's a fun test you can make, use [Postman's echo API](https://learning.postman.com/docs/developer/echo-api/):

```
$ curl -X POST "postman-echo.com/post" --data '{"example":"hello"}'
{"args":{},"data":"","files":{},"form":{"{\"example\":\"hello\"}":""},"headers":{"x-forwarded-proto":"http","x-forwarded-port":"80","host":"postman-echo.com","x-amzn-trace-id":"Root=1-619632ff-5e2486bf7047cd130d7a6c4b","content-length":"19","content-type":"application/x-www-form-urlencoded","user-agent":"curl/7.64.1","accept":"*/*"},"json":{"{\"example\":\"hello\"}":""},"url":"http://postman-echo.com/post"}
```

As you can see, it was posted as `application/x-www-form-urlencoded`, and that form had a field called `{"example":"hello"}` with an empty string value.

**Comment by DavideViolante** [comment]
Actually I was also missing this line in the app:
`app.use(express.json());`
because it was not working even with [httpie](https://github.com/httpie/httpie) that has json built in support.

Thanks

**Comment by fedeci** [comment]
Is it working fine right now? It isn't the first bug report of `.matches` not working properly with a Regex object.

**Comment by KikoCosmetics** [comment]
Do you think there might be a problem?
I have this:
![image](https://user-images.githubusercontent.com/93335982/147643900-5108fc1b-e543-420d-96a2-9fc8be0c75fc.png)
The matches control once in a while fails...I really don't see how could it...
I'm adding more info after doing some tests
