### ISSUE TITLE
Is it possible to do schema composition?

### ISSUE THREAD

**Issue by davidlunadeleon** [express-validator/express-validator#1111]
Hello, I would like to know if it's possible to combine multiple smaller schemas into one bigger schema, specially when dealing with nested fields. 

I currently do validations of nested fields using the dot (`parent.child`) notation or using wildcards, but all definitions are made in a single schema. I would like to reuse a smaller schema in multiple parts of my code. 

For example: An address schema that's reused when I receive user data, as well as restaurant data.
```
export const addressSchema: Schema = {
  "addressLine": {
    in: ["body"],
    isString: true
  },
  "zipCode": {
    in: ["body"],
    isPostalCode: true
  }
};

export const personSchema: Schema = {
  "name": {
    in: ["body"],
    isString: true,
  },
  "lastName": {
    in: ["body"],
    isString: true,
  },
  ...
  "address": addressSchema
};

export const restaurantSchema: Schema = {
  ...
  "address": addressSchema
}
```

So instead of defining `address.addressLine` and `address.zipCode` in the definition of `personSchema`, `address` would be defined somewhere else.

I looked through the previous questions and issues, but couldn't find similar cases to this.

**Comment by fedeci** [comment]
Schemas are still JS objects so you can use JS operators and constructs to manipulate them.
Like this below can help you add a prefixed schema for nested properties.
```js
const getAddressSchema: Schema = (prefix) => ({
  [prefix + "addressLine"]: [
    in: ['body']
  ]
})
```

**Comment by davidlunadeleon** [comment]
Thank you. This helped me to solve my problem :)

I ended up creating a `mergeSchemas` function to merge an array of schemas.

**Comment by fedeci** [comment]
Great!
