### ISSUE TITLE
normalizeEmail() API alters the email TLD (@yandex.com)

### ISSUE THREAD

**Issue by eazylaykzy** [express-validator/express-validator#1119]
## Describe the bug

The `normalizeEmail()` API alters some email TLD like @yandex.com

## To Reproduce

`check('email', 'email is required').normalizeEmail({ gmail_remove_dots: false })`
In the request body, enter any Yandex email that ends with ".com", example: "useremail@yandex.com"

## Expected behavior

It is expected to return a sanitised email with same TLD unaltered, that is: "useremail@yandex.com"

## Current behavior

When user(s) enter their Yandex email, say, "useremail@yandex.com", the result is altered during sanitation, we got this on the request body "useremail@yandex.ru" as the user's email.

## Environment:

- Express-validator version: 6.12.1
- Express version: 4.17.1

**Comment by fedeci** [comment]
Hey there! You should try to update express validator to the latest version (`npm i express-validator@latest`), or open an issue at https://github.com/validatorjs/validator.js because we rely on that library.
