### ISSUE TITLE
Why does "+xyz" in query params are decoded as "[space]xyz"

### ISSUE THREAD

**Issue by jatinmehrotra** [express-validator/express-validator#1122]
```
query('sort_by')
    .optional()
    .isIn([' originalUrl'])
    .withMessage({
      error: 'Invalid parameter value',
      detail: {
        max_results: 'parameter value (+originalUrl|-originalUrl) is allowed',
      },
    }),
```

I am trying to validate query param which consists of `+something`, however the validator sees this as ` something.

how do we test for such parameter because if we check for this ` .isIn([' originalUrl'])`, a user can enter ' orginalurl' in the request and will be validated which is not expected behaviour

**Comment by jatinmehrotra** [comment]
the same has been posted on StackOverflow but no luck https://stackoverflow.com/questions/70364189/express-validator-how-to-check-for-xyz-using-query-check

**Comment by fedeci** [comment]
Please see section 2.2 of the [URI RFC](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2). This issue is not related with `express-validator`, you should encode the `+` and the `-` as they are reserved chars.
