### ISSUE TITLE
Validate an array prop if other prop inside the same object is true

### ISSUE THREAD

**Issue by thiagocolebrusco** [express-validator/express-validator#1126]
### Describe the bug
I'm trying to validate a few props inside an array object only if the `enabled` prop of that same object is true.

---

### To Reproduce
My request object looks like this.
```
{
    "propA": "",
    "propB": "",
    "items": [
         {
              "enabled": true,
              "name": "",
         }
    ]
}
```

I want to validate if the name prop of the array object is notEmpty only of the enabled property is set to `true`.

---

### Environment:
Express-validator version: 6.12.1
Express version: 4.17.1

**Comment by fedeci** [comment]
You can try using wildcard validation along with `.custom`.
If that doesn't work you should fallback to imperative validation using `.run()` in a custom middleware.

**Comment by thiagocolebrusco** [comment]
Right. I was able to solve it with a custom function and test each prop by myself. But I wanted to be able to use the builtin functions of express-validator (`isEmpty`, `isInt`, etc.) and I couldn't do it inside the custom function.

**Comment by fedeci** [comment]
You should try this one https://express-validator.github.io/docs/running-imperatively.html !

**Comment by thiagocolebrusco** [comment]
Thank you for your responses.

I tried this, but I couldn't make this work. My main issue is to be able to test properties of the array's object based on another prop value. In this example you sent, it just uses properties of the main object.

**Comment by fedeci** [comment]
I don't think it's possible then but for v7 we planned to improve support for `oneOf` with wildcards.
To use the same function that express-validator is using but without directly using express-validator you can import methods from 'validator' https://github.com/validatorjs/validator.js which is already packed up with express-validator as a dip.
