### ISSUE TITLE
.matches failing when passing regex instead of pattern

### ISSUE THREAD

**Issue by KikoCosmetics** [express-validator/express-validator#1127]
## Describe the bug

It appears that passing a regex causes the validation to fail sometimes

Here's the typings just to show that regexps are allowed:

![image](https://user-images.githubusercontent.com/93335982/147645612-1c10d74b-b8f5-4b84-9d62-1f02ee40809c.png)

## To Reproduce

**FAILS**

![image](https://user-images.githubusercontent.com/93335982/147643900-5108fc1b-e543-420d-96a2-9fc8be0c75fc.png)

![image](https://user-images.githubusercontent.com/93335982/147644124-293de743-a9e3-47cd-a901-9f373b55455a.png)

![image](https://user-images.githubusercontent.com/93335982/147644218-ac61f9cb-c844-4ed4-8459-5bae578bfe28.png)

**FAILS**
![image](https://user-images.githubusercontent.com/93335982/147644826-8b1f553b-2c74-4a72-998d-afc2aeaac153.png)

**PASSES**
![image](https://user-images.githubusercontent.com/93335982/147644636-4963ae53-4401-472a-ae5d-6220a89c0d1e.png)

## Expected behavior

The validation should always pass or always fail

## Current behavior

The validation fails sometime (it shouldn't)

## Environment:

- Express-validator version: 6.13.0
- Express version: 4.17.1
- Node 14.18.1

**Comment by gustavohenke** [comment]
hey @KikoCosmetics, that's awkward, are you sure that the input is really just that?

I tried your example and it seems to work?
https://runkit.com/gustavohenke/61f8747fdee3900008e482b5

Are you able to point out whether I'm missing anything?

**Comment by KikoCosmetics** [comment]
Hi @gustavohenke you can see that the input (body.user) is in the inspector...it's just "it046004".
Anyway it fails only sometimes, sometimes it passes...
I'm editing the runkit to achieve the same structure I have...
I'll keep you posted :)

Thanks

**Comment by KikoCosmetics** [comment]
hi @gustavohenke I discovered the mistery!!
Ahahah this was fun!
I noticed that the validation passed every other one time...so I had OK, KO, OK, KO, OK, KO.
Take a look:

https://runkit.com/kikocosmetics/61f8ecbcc7b2f9000827243e

The error happens because the instance of the regexp is the same, so since it contains the "g" flag, the "lastIndex" property is updated, but never reset.
I think that the validator should run with a fresh copy of the regex every time, since we don't usually have control over it after it's been passed to the validation chain...
What do you think?
I don't understand how I'm the first one noticing this 😂

**Comment by codemicah** [comment]
Thank you for bringing this up @KikoCosmetics.I have also been experiencing the same issue. The validation passes then fails then passes again and continues in that manner.

**Comment by mrd5591** [comment]
Adding on here that I am also seeing this issue. Thanks for the investigation @KikoCosmetics, I thought I was going crazy

**Comment by Tusharsharma144** [comment]
came here looking for the solution of the same problem i am facing right now. It fail once and passes the next time. Removing g at the end of regex solve my problem.

**Comment by gustavohenke** [comment]
PRs welcome, should be a simple fix 😃

**Comment by KikoCosmetics** [comment]
@gustavohenke I'll fix it by the end of this week. 
I have 2 solutions in mind already, just want to choose the cleaner.

Cheers

T.

**Comment by KikoCosmetics** [comment]
Ops, closed by mistake.
