### ISSUE TITLE
Need to transform the array response, validating array

### ISSUE THREAD

**Issue by jensysantana** [express-validator/express-validator#1133]
this is the response validating array.

```
[
  {
    value: '^$',
    msg: 'First name must contain letters and numbers.',
    param: 'products[0].fname',
    location: 'body'
  },
]
```

the problem is this line: param: 'products[0].fname'

since this line is string I can't get in the position number of it.

so I need to be able to get the number  0 on this element. I mean the index of the array.
so this is the Idea. how can I set this error in my FrondEnd app since I have the error loop index in string format ( param: 'products[0].fname').

I need the error index to be able to set the error message in my FrontEnd I can this but If I have an array like this: 

```
const products = [

        {
            name:'Orange',
            price: 0.98
        },
        {
             name:'Pineapple',
             price: 2.99
        },
        {
             name:'Melon',
             price: 1.85
        }
]
```

and let think we have an error in the index 1 of the array (Pineapple)

Now I need to show an error message in my FrontEnd so. the backend server send me 
```
[
  {
    value: '^$',
    msg: 'Pineapple must contain letters.',
    param: 'products[0].pineapple',
    location: 'body'
  },
]
```
and now I need to show this error and that specific element. how can I iterate this string?: 
param: 'products[0].pineapple'

I can use some javascript methods to do it but I would like to know if have some ease way to do it instead. thank you.

**Comment by gustavohenke** [comment]
I'd usually use Lodash's `_.get` and `_.set`, which work with this syntax.

https://lodash.com/docs/4.17.15#get
https://lodash.com/docs/4.17.15#set
