### ISSUE TITLE
IsIn options include only the first given option

### ISSUE THREAD

**Issue by gilm123** [express-validator/express-validator#1136]
## Describe the bug
when using the `isIn` and giving an array of strings as options, only the first item in the array is being taken.

## To Reproduce
validate this schema
```
const proxiedRequestBodyProperty = 'proxiedRequest';
export const proxyRequestValidator = checkSchema({
    [proxiedRequestBodyProperty]: {
        isObject: true,
        errorMessage: 'expecting an object',
    },
    [`${proxiedRequestBodyProperty}.url`]: {
        isURL: true,
        errorMessage: 'expecting a URL',
    },
    [`${proxiedRequestBodyProperty}.method`]: {
        isIn: {
            // options: [['get', 'delete', 'head', 'options', 'post', 'put', 'patch']], // works
            options: ['get', 'delete', 'head', 'options', 'post', 'put', 'patch'], // doesn't work
        }
    },
    [`${proxiedRequestBodyProperty}.body`]: {
        isJSON: true,
        optional: true,
    },
    [`${proxiedRequestBodyProperty}.headers`]: {
        isObject: true,
        optional: true,
    },
});
```
with a payload of this JSON on the body
```
{
    "proxiedRequest": {
        "url": "https://my-url.com",
        "method": "put"
    }
}
```

I put a breakpoint into the validator dependency and it seems it is always getting only the first element in the array
![image](https://user-images.githubusercontent.com/20421380/156421446-225575d4-fae0-4026-8a8a-10ad09bae462.png)

## Expected behavior
valid "method"

## Current behavior
error saying invalid

## Environment:
- Express-validator version: 6.14.0
- Express version: 4.16.2

**Comment by fedeci** [comment]
That's the correct way of doing it and it has been built like that!

**Comment by gilm123** [comment]
hey @fedeci thanks for the reply :) 
what is the reason for making the argument expecting an array of arrays ?

**Comment by gustavohenke** [comment]
@gilm123 there aren't many other ergonomic options when the validator expects a list of options...

Taking your example, for `isIn`, that could be `options: ['get', 'post', 'put',  etc]`, right, easy.

Now for other validators like `isAlpha`, how do you express both the locale and the validator options?

```js
options: {
	locale: 'en-AU', 
	options: {...}
}
```

OK, that looks great, but it also means that `checkSchema` needs to know how to work with the other validators that support multiple arguments... `isAlphanumeric`, `contains`, `isMobilePhone` and `matches`, from what I could spot skimming through validatorjs docs.

There might be some good ways out there, we just haven't found them yet.
