### ISSUE TITLE
trim: true in schema validation is changing one request field to "string" type from "object" type

### ISSUE THREAD

**Issue by KEHSIHBA-IGAYT** [express-validator/express-validator#1138]
Hi,

I am trying to validate one field "attachments" which has nested objects. Till version 5.3.1, it was working fine, but as soon as I updated to version 6.13.0 the behavior of **trim** is changed.

Code:

```
 "attachments.*": {
            optional: true,
            trim: true,
            notEmpty: true,
            errorMessage: "some message",
            isObject: {
                errorMessage: "some message"
            }
       }
      
      console.log(req.body.attachments);
```
      
## _**5.3.1**_

It results in:
       
```
[
{ filename: 'check1', path: 'check1' },
{ filename: 'check2', content: 'check2' },
{ path: 'check3' },
{ raw: 'hello world' }
]
```
       
## _**6.13.0**_

It results in:
       
```
[
'[object Object]',
'[object Object]',
'[object Object]',
'[object Object]'
]
```

As soon as I change trim to `false` for version 6.13.0, the output becomes same (correct object form).

**Comment by gustavohenke** [comment]
This was a breaking change of v6.0.0.
https://github.com/express-validator/express-validator/releases/tag/v6.0.0

Previous to it, non-string values were never sanitised, which has been deemed a vulnerability.
There are several issues linked in the changelog to see examples of times that this behaviour presented difficulties.
