### ISSUE TITLE
Show only one error per validation

### ISSUE THREAD

**Issue by AlbaSly** [express-validator/express-validator#1140]
I'm making a validation chain for a SignUp Middleware:
```
export const SignUpValidator: ValidationChain[] = [
    body('email')
        .exists().withMessage('1st Error')
        .not().isEmpty().withMessage('2nd Error')
        .isEmail().withMessage('3rd Error')
        .trim()
        .toUpperCase()
];
```
I only want the first error found to be displayed, and in case the first error does not exist, display ONLY the next one.

For example: 
-if my email key doesn't exists: show only '1st Error'.
-if my email key exists, but its value doesn't: show only '2nd Error'.
-if my email key exists as its value, but isn't a valid email structure: show only '3rd Error'.

How can i do a thing like this?

**Comment by killyouare** [comment]
use [bail()](https://express-validator.github.io/docs/validation-chain-api.html#bail)
