### ISSUE TITLE
Reusing validation rules on body array

### ISSUE THREAD

**Issue by ipratico** [express-validator/express-validator#1141]
Hello everyone,
I'm working with express validator, but I encountered an issue I would like to solve. 
I've an API which creates a product, in the request I send an object with all the information of the product and the validation chain seems like this:
```
const validatorsSchema = [
	body('name').exists({ checkFalsy: true }).withMessage(MSG_MANDATORY_PARAM).trim(),
	body('quantity').toInt(),
	body('description').trim(),
        ...
];
```
and it's working well.

The problem came when I needed to implement a BULK Create API for the products. In the request body I have an array of products instead of a single product object, so I want to validate the entire array of objects using the same validation schema the other API use to validate a single product without rewritring the validation schema for the array.

I know I can do the validation like this, but I don't want to duplicate the validation chain.
```
const validatorsSchema = [
	body('*.name').exists({ checkFalsy: true }).withMessage(MSG_MANDATORY_PARAM).trim(),
	body('*.quantity' ).toInt(),
	body('*.description').trim()
];
```
Can someone please help me?
Thank you.

**Comment by fedeci** [comment]
This may help you:
```ts
const validatorsSchema = (validateArrayItems: boolean) => [
	body(validateArrayItems ? '*.name' : 'name').exists({ checkFalsy: true }).withMessage(MSG_MANDATORY_PARAM).trim(),
  // ... and so on
];

```

**Comment by ipratico** [comment]
That's perfect!
Thank you very much, @fedeci
