### ISSUE TITLE
Add Postal Code Locale for Slovakia

### ISSUE THREAD

**Issue by tfilo** [express-validator/express-validator#1144]
## Is your feature request related to a problem? Please describe.

Hello, i try to use express validator for validating Postal Code in Slovakia. While validator.js has SK locale for postal code in source code for 4 years already. It would be great if you can add support to express-validator too with types definitions for typescript. Thank you.

## Describe the solution you'd like

Add support for SK locale based on validator.js https://github.com/validatorjs/validator.js/blob/master/src/lib/isPostalCode.js

**Comment by gustavohenke** [comment]
This totally slipped for this long!! Added it and released as v6.14.1.
