### ISSUE TITLE
Is there any other way to add custom error to validationResult(req) ?

### ISSUE THREAD

**Issue by ConfSlay** [express-validator/express-validator#1146]
Hi, 

i recently spent some time trying to add an error in the validationResult() without using check(). It was in order to display missing files in a form, trying to do a validation middleware based on express-validator middleware. Is there a more conventionnal way to do, or any method i could miss in the documentation ?

Have a nice evening,

```
`const { check, validationResult, matchedData } = require('express-validator');

exports.projectValidation = [
    check('project_name', 'Name is required').not().isEmpty(),
    check('project_description', 'Description is required').not().isEmpty(),
  (req, res, next) => {
    const e = validationResult(req);
    let errors = new Array();
    errors = e.array();
    //---------Files Validation-------------
    if(req.files["project_thumbnail_filename"] === undefined){
      errors.push({"param" : "project_thumbnail_filename", "msg" : "No file selected"});
    }

    if (errors[0] !== undefined) {
      return res.status(422).json({errors: errors});
    }
    next(); 
  },
]`
```

**Comment by fedeci** [comment]
Hi @ConfSlay, you can use [`buildCheckFunction(['files'])`](https://express-validator.github.io/docs/check-api.html#buildcheckfunctionlocations) to create a custom checker and then add a `.custom(...)` or `.exists()` validator to check for that parameter. This should work fine!

**Comment by fedeci** [comment]
Let me know if it helped!
