### ISSUE TITLE
Conditional validators

### ISSUE THREAD

**Issue by ssurve** [express-validator/express-validator#1149]
I have a single REST endpoint e.g. POST `/test-route` but it can service two different payloads.

E.g.
Payload A:
```
{
	name: 'entityA',
	type: 'typeA',
	config: {
		prop1: ...,
		prop2: ...,
                 prop3: ...,
	}
}
```

Payload B:
```
{
	name: 'entityB',
	type: 'typeB',
	config: {
		prop5: ...,
		prop6: ...,
	}
}
```

The payloads have some common properties (name, type) while the config can have completely different properties (dependent on type). I've created two different validators for these payloads -- `ValidatorA`, `ValidatorB`.

How can I make it so that the second middleware (i.e. either `ValidatorA` or `ValidatorB`) in the following is dynamically determined based on type?

`app.post('/test-route', ??, ControllerMethod)`

**Comment by fedeci** [comment]
Hi @ssurve, you can run validators imperatively in this way https://express-validator.github.io/docs/running-imperatively.html.
I'd suggest you to create a wrapper in a separate file that allows you to specify a predicate

e.g.
```js
const middlewareNameValidation = (req, res) => {
  let chain = []
  // validate type property
  if (req.body.type) {
    chain = [ ... ]
  } else {
    chain = [ ... ]
  }

  for (const item of chain) { // validate and eventually return error
  }
}
```
