### ISSUE TITLE
.replace() not working with regex on the body of the request?

### ISSUE THREAD

**Issue by NickWoodward** [express-validator/express-validator#1155]
I'm trying to use `.replace(/\s*/g,"")` on the body of my request to remove spaces before validation. I've only just noticed that `.replace` is an express-validator function (rather than the JS one), and the docs don't mention regex. Is there any easy way to remove spaces in this field? I've tried using a custom function with `.replace` and `replaceAll`, but with no luck
    
**_Doesn't work:_**
    body('phone')
        .isString()
        .replace(/\s*/g,"")
        .matches(/^0([1-6][0-9]{8,10}|7[0-9]{9})$/)
        .withMessage('Please enter a UK phone number'),
        
**_Or:_**
    body('phone')
        .isString()
        .custom(value => value.replaceAll(' ', ""))
        .matches(/^0([1-6][0-9]{8,10}|7[0-9]{9})$/)
        .withMessage('Please enter a UK phone number'),

**_Or:_**
    body('phone')
        .isString()
        .custom(value => value.replace(/\s*/g,""))
        .matches(/^0([1-6][0-9]{8,10}|7[0-9]{9})$/)
        .withMessage('Please enter a UK phone number'),
        
I've obviously got the wrong end of the stick somewhere - would appreciate being corrected!

Thanks,

Nick

**Comment by nukuutos** [comment]
`replace` sanitize method doesn't work with regex. It works only by replacing exact words

From docs:
```
app.post('/', body('username').replace(['bar', 'BAR'], 'foo'), (req, res, next) => {
  // 'bar_' => 'bar_'
  // 'bar'  => 'foo'
  // 'BAR'  => 'foo'
  console.log(req.body.username);
});
```

You're using `custom` validator but in this case you should use `customSanitizer`. `custom` validator is used for checking values(some condition) so your custom validator should return `boolean`, `promise` or `throw` something.

`customSanitizer` is used for transforming values, e.g. to remove whitespaces from string. It should work
```
  body("phone")
    .isString()
    .customSanitizer((value) => value.replace(/\s/g, ""))
    .matches(/^0([1-6][0-9]{8,10}|7[0-9]{9})$/)
    .withMessage("Please enter a UK phone number"),
```

**Comment by fedeci** [comment]
@nukuutos that's correct, thanks!

**Comment by NickWoodward** [comment]
@nukuutos ah, thanks for that

I ended up using this:

```
        .custom(value => value.replace(/\s*/g, "")
                                .match(/^0([1-6][0-9]{8,10}|7[0-9]{9})$/))
        .withMessage("Please enter a UK phone number"),
```

but it's good to know the correct approach, thanks!
