### ISSUE TITLE
Custom validator is not working when field has optional({nullable: true}) provided

### ISSUE THREAD

**Issue by romit-gandhi** [express-validator/express-validator#1157]
## Describe the bug
body("demo")
.optional({nullable: true}).
.custom() // custom function chceking for one thing
.isString()
.withMessage("demo")

This is the validator that I'm using where I have optional({nullable: true}) then custom validator applied but if I pass null value in this then custom validator is not executing.

## Expected behavior

It should execute the custom validator no matter whether the value is null or string.

## Environment:

- Express-validator version: 6.14.0
- Express version: 4.17.3

**Comment by nukuutos** [comment]
Why it should execute custom validator? if you pass to `optional` as argument `{ nullable: true }` it means that you say to express validator that it mustn't touch `demo` field with `null` value. But if we go by your logic so it would be run of custom middleware also as following chaining methods such as `isString` and you would got an error even you said to express to not touch `demo` field with `null` value.

From the docs:
> nullable: if true, fields with null values will be considered optional

**Comment by gustavohenke** [comment]
as @nukuutos said.
