### ISSUE TITLE
Reusing validation for nested object validation

### ISSUE THREAD

**Issue by cnpatric** [express-validator/express-validator#1162]
Hi,

I tried finding a solution here but couldnt find a clear one.

I have two entities lets assume they are both validated with

Entity A

```
[
body("website").optional().isLength({min: 3}).trim(),
body("createdBy").exists().notEmpty(),
body("address").exists().isObject(),
];
```

Entity B

```
[
body("street").exists().isLength({min: 3}).trim(),
body("streetNumber").exists().trim(),
body("additionalAddress").optional().isLength({min: 3}).trim(),
body("zipcode").exists().isPostalCode("US").trim(),
body("city").exists().isString().trim(),
body("country").exists().isString().trim(),
body("state").exists().isString().trim(),
];
```

since Entity B can be part of Entity A in the address field but can also be a standalone Entity that needs to be validated, I'd rather not duplicate my already existing validation for Entity B into A.

Is there a way to validate "address" field from A with all the validations from Entity B?

Thanks a lot!

**Comment by gustavohenke** [comment]
Hey, it's a bit cumbersome, but the way is to prefix those fields with the path of the parent, perhaps with a function.

for example:

```js
const createAddressValidators = (path: string) => [
	body(`${path}.street`).isLength({ min: 3 }),
	body(`${path}.number`).exists(),
	// ...and so on.
];

app.post('/profile', [body('address').isObject(), ...createAddressValidators('address')]);
```

**Comment by gustavohenke** [comment]
Closing for now.
