### ISSUE TITLE
Sensitive Data Exposure through Syntax Error

### ISSUE THREAD

**Issue by user123pp** [express-validator/express-validator#1163]
## Describe the bug

I would like to show you a bug that can lead to Sensitive Information Disclosure.
The express validator raises exception which developer can not handle, and this error is being returned to the sender.

## To Reproduce

1. Make a default express app
2. Set app.use(express.json({ extended: true }));
3. Create any endpoint, such as
router.post(
  '/login',
  [
    check('email')
      .trim()
      .normalizeEmail()
      .isEmail()
      .withMessage('Incorrect email'),
    check('password').trim().not().isEmpty().withMessage('Incorrect password'),
  ],
  async (req, res) => {
    try {
     } catch (error) {
    }
  }
);
4. Set in request Content-Type: application/json
5. Send to this endpoint payload: {,,}
![image](https://user-images.githubusercontent.com/110176530/182554578-c5f06d31-188a-45f1-b03c-40875e26906d.png)
6.Check the response: SyntaxError...
![image](https://user-images.githubusercontent.com/110176530/182554924-1b07de36-7434-4e18-873a-5bb82543501a.png)

## Expected behavior
Express-validator raises exception inside async (req, res) => {} body, so it's possible to handle it.

## Current behavior
Express-validator raises exception somewhere inside it is, so we can't handle error and this error can lead to Sensitive Data Exposure.

Is it possible to have a bug bounty on this report? I would appreciate it.

## Environment:

- Express-validator version: 6.14.2
- Express version: 4.18.1

**Comment by gustavohenke** [comment]
express-validator doesn't do body parsing at all.
That's the job of the `express.json()` middleware you've added in your example, which internally uses `body-parser` package (you can clearly see that in the stack trace in your screenshot).

Even then, it's not a bug (not express', not express-validator's, not body-parser's). You should use an error handling middleware instead.
https://expressjs.com/en/guide/error-handling.html
