### ISSUE TITLE
Adding custom key in error object

### ISSUE THREAD

**Issue by bertdida** [express-validator/express-validator#1164]
Is it possible to add custom `key` in error object?

For example I currently have this error,
```json
{
  "location": "body",
  "msg": "DeviceNotSufficient",
  "param": "users",
  "value": ["62eb2c518feadaf9132273f6"]
}
```
I wonder if it's possible to add a `totalDevice` in the object, like below
```json
{
  "location": "body",
  "msg": "DeviceNotSufficient",
  "param": "users",
  "value": ["62eb2c518feadaf9132273f6"],

  "totalDevice": 0,
}
```

I believe this is  a common usecase, but I haven't found a similar discussion.

I know I could use [`withMessage`](https://express-validator.github.io/docs/validation-chain-api.html#withmessagemessage), but that would result to `msg` being an Object 🫤

**Comment by gustavohenke** [comment]
did you give this a try?
https://express-validator.github.io/docs/custom-error-messages.html#dynamic-messages
