### ISSUE TITLE
should add support for DR Congo mobile phone validation

### ISSUE THREAD

**Issue by coolbeatz71** [express-validator/express-validator#1168]
## Is your feature request related to a problem? Please describe.
I just realized there is no support for a bunch of local phone numbers in Africa (most of them are french speaking), such as RD Congo, Congo Republic, Central African Republic, etc.
## Describe the solution you'd like
The ICU country code for DR Congo is `fr-CD` and the regex should be `/^(\+?243|0)?(8|9)\d{8}$/`. I can raise a PR for this one. But I need to make more research on other french speaking african countries.

**Comment by gustavohenke** [comment]
Hey! Sorry but this needs to be implemented over in validator, as most of those are there.

Here's their file as of today for `isMobilePhone`:
https://github.com/validatorjs/validator.js/blob/86a07ba4f3f710f639e92a62cf81dd3321ef9ee8/src/lib/isMobilePhone.js

Once that's done I can update the dependency here.
