### ISSUE TITLE
Validate array of numbers as request body

### ISSUE THREAD

**Issue by QuentinLuc** [express-validator/express-validator#1171]
Hey, I'd like to create the validation schema object to validate a body looking like this:
```
[12,15,16]
```
So far, this solution works:
Hey, I'd like to create the validation schema object to validate a body looking like this:
```
const schema: Schema = {
    '': {
        in: ['body'],
        isArray: true,
        errorMessage: '*ids* array is required',
    },
};
```

And to get the matched data:
```
matchedData(req)[''] // notice the ""
```

The validation object seems a bit weird to me.  At first I had tried with `"*": {...}` but it wasn't working.  On top of that, with my actual solution, I cannot check if items in the array are numbers.

How could I improve it?

**Comment by gustavohenke** [comment]
Hey! I think that the solution here atm would be to not use schemas, but rather `body()` directly.
Docs example: https://express-validator.github.io/docs/whole-body-validation.html
