### ISSUE TITLE
How to make sure the field is must have using optional() ?

### ISSUE THREAD

**Issue by ningji** [express-validator/express-validator#1172]
I cannot fully understand the doc

https://express-validator.github.io/docs/validation-chain-api.html 

By default, fields with undefined values will be ignored from the validation.
You can customize this behavior by passing an object with the following options:

nullable: if true, fields with null values will be considered optional
checkFalsy: if true, fields with falsy values (eg "", 0, false, null) will also be considered optional

My pseudo code is like this, basically we want to have a common validator, but sometimes the body field is optional.

```
...
const { body, validationResult } = require('express-validator');


const myValidator = (v, isOptional) => {
    return body(v).optional({nullable: isOptional}).isNumeric();
    // more validations will be added here
}

app.post('/info',
    myValidator('value1', false), // must have value1
    myValidator('value2', true),  // might have value2
    (req, res) => {
        res.status(200).json({
            success: true,
            message: 'success',
        })
    });
...
```
shall i use nullable or checkFalsy in the parameter for optional() ?

**Comment by gustavohenke** [comment]
> shall i use nullable or checkFalsy in the parameter for optional() ?

None. These configure how "optional" you want the value to be.
- `.optional()` => only `undefined` values are skipped;
- `.optional({ nullable: true })` => `undefined` and `null` values are skipped;
- `.optional({ checkFalsy: true })` => falsy values (e.g. `null`,`undefined`, `""`, `0`, `false`) are all skipped.

You'd want to do something else in your validator builder, e.g.

```
const myValidator = (v, isOptional) => {
    const chain = body(v).isNumeric();
	if (isOptional) {
		chain.optional({nullable: isOptional});
	}
	return chain;
}
```
