### ISSUE TITLE
Look for data within a custom field 

### ISSUE THREAD

**Issue by TannerS** [express-validator/express-validator#1174]
Hello! I had a quesiton, for us we need to validate data that is not within the body, query, cookies, etc

so something like this 

```
checkSchema({
    id: {
      in: ['api.body'], <---------
      isInt: true,
    },
```

This api we use does not have a body within a request object, instead it is embedded within a field called `api`.

(I know i didnt make this but we are forced ot use it), is there any way around this?

to clarify, our request data is within the body, but body is within another filed on the request/response object

**Comment by gustavohenke** [comment]
Hi @TannerS!
I think that what you're looking for is to use nested fields:

```js
checkSchema({
  "api.id": {
    isInt: true
  }
})
```
