### ISSUE TITLE
Is there a way to set the rules in the Schema?

### ISSUE THREAD

**Issue by Quin452** [express-validator/express-validator#1176]
I can run the validator as middleware just fine, but I was wondering if there is a way to make it look tidier than the examples I've seen online.

Currently, I can use:
```
router.post('/[route]',
     [
         check('name')
             .not()
             .isEmpty()
             .withMessage('Name is required'),
     ],
     [controller].create);
 ```
 
 And:
 ```
router.post('/[route]',
    checkSchema({
        Name: {
            isLength: {
                errorMessage: 'Name should be at least 6 chars long',
                // Multiple options would be expressed as an array
                options: { min: 5 },
            },
        },
    }),
    [controller].create);
 ```
 
 Both of these become very long when checking all the validation rules.
 The "create" method is `async (req, res)` and does return the error messages.
 
 My IDE does highlight "schema" when within the brackets of "checkSchema".  And I was wondering if there is a way to set the rules in the schema, with error messages, etc.  I can not find anything online.
 Currently, the only method with consistent success is the first "check" one, as not all the "checkSchema" rules seem to fire.

**Comment by gustavohenke** [comment]
Hi @Quin452!

> I was wondering if there is a way to set the rules in the schema, with error messages

Can you explain what exactly you are looking for? I'm not sure I understand what kind of syntax you want.

**Comment by Quin452** [comment]
So this is my current User Schema (pretty simple):

```
const UserSchema = new Schema({
        name: {
            type: String,
            trim: true
        },
        email: {
            type: String,
            required: true,
            trim: true
        },
        phone: {
            type: String,
            trim: true
        },
        role: {
            type: String,
            default: 'user',
        },
        password: {
            type: String,
        },
        deletedAt: {
            type: Date,
            default: null
        },
    },
    { timestamps: true }
);
```

I'd like to have it that the rules are set there, so I only need to declare the fields once instead of having to write them out in different routes (thus becoming a very long file).
Then, the validation rules checks against the ones set in the Schema and returns any error messages.

Something like:
```
const UserSchema = new Schema({
        name: {
            type: String,
            trim: true
            validation: {
                notNull: true,
                required: true,
                isLength: {
                    errorMessage: 'Name should be at least 6 chars long',
                    options: { min: 5 },
               }
           },
        },
});
```

**Comment by gustavohenke** [comment]
Can you parse that 3rd-party schema yourself and build an express-validator schema out of it?

For example:

```js
function dbSchemaToExpressValidator(schema) {
	const out = {};
	for (const [key, definition] of Object.entries(schema)) {
		out[key] = {
			notEmpty: definition.required,
			trim: definition.trim,
			// ...etc etc
		}
	}
	return out;
}

const schemaDefinition = {
	name: {
		type: String,
		required: true,
	},
	// ...
};
export const UserSchema = new Schema(schemaDefinition);
export const routeSchema = checkSchema(dbSchemaToExpressValidator(schemaDefinition));
```

Closing for now as this doesn't sound like will need any changes to express-validator. Feel free to continue commenting!
