### ISSUE TITLE
How to test my validation middleware?

### ISSUE THREAD

**Issue by awm086** [express-validator/express-validator#1178]
Is this the correct way to test my validation middleware:

```

  body('name')
      .exists({ checkNull: true, checkFalsy: true })
    .withMessage("name is missing.")
```
```
  it(" test name is required ", async () => {
    // eslint-disable-next-line no-var
    var httpMocks = require("node-mocks-http");
    const mockReq = httpMocks.createRequest({
      method: "post",
      body: { name: "" }
    });
    const mockNext = jest.fn();
    const mockRes = jest.fn();
    await nameValidator("name")(mockReq, mockRes, mockNext);
    const valid = validationResult(mockReq).isEmpty();
    expect(valid).toBe(false);

```
When I try to access the errors in returned from `validationResult` I get an error that error is private. 

What is the best way to test validators middleware. The example above is a simple one and not representative of some complex validation that require tests.

**Comment by gustavohenke** [comment]
What about leveraging [imperative validations](https://express-validator.github.io/docs/running-imperatively.html)?

```js
const mockReq = httpMocks.createRequest({
      method: "post",
      body: { name: "" }
    });
await body('name').notEmpty().run(req);
expect(validationResult(req).isEmpty()).toBe(true);
```

[Demo](https://runkit.com/gustavohenke/6338e9a613b8aa000803fc2b)

**Comment by awm086** [comment]
Thank you. I will try this method out with my validators.
