### ISSUE TITLE
isStrongPassword needs to provide all options to work as expected

### ISSUE THREAD

**Issue by SuriSureda** [express-validator/express-validator#1181]
## Describe the bug

isStrongPassword  validation chain is not working when i provided custom options. It seems to be using always the default values.

## To Reproduce

To test, i'm just trying with the validation of at least 2 characters : 
`
body('password').exists().withMessage('"password" is required').isStrongPassword({
        minLength: 2,
      }),
`

But if i provide password : "password", validation fails ("Invalid value").

But if i provide : 
`
body('password').exists().withMessage('"password" is required').isStrongPassword({
        minLength: 2,
        minLowercase: 0,
        minUppercase: 0,
        minNumbers: 0,
        minSymbols: 0,
        returnScore: false,
        pointsPerUnique: 0,
        pointsPerRepeat: 0,
        pointsForContainingLower: 0,
        pointsForContainingUpper: 0,
        pointsForContainingNumber: 0,
        pointsForContainingSymbol: 0,
      }),
`
It works.

## Environment:
- Express-validator version: 
- Express version:

**Comment by gustavohenke** [comment]
Unfortunately the default options get in the way for this validator, so unless you configure everything, you really need a password that has at least 4 characters (1 lower, 1 upper, 1 number, 1 symbol)

```
Default options:
{ minLength: 8, minLowercase: 1, minUppercase: 1, minNumbers: 1, minSymbols: 1, returnScore: false, pointsPerUnique: 1, pointsPerRepeat: 0.5, pointsForContainingLower: 10, pointsForContainingUpper: 10, pointsForContainingNumber: 10, pointsForContainingSymbol: 10 }
```
