### ISSUE TITLE
ISO8601 strict not working

### ISSUE THREAD

**Issue by firattaskin** [express-validator/express-validator#1183]
## Describe the bug

I am using body parser like this
``
  router.post(
    '/create',
    body('date').isISO8601({ strict: true }).toDate(),
    asyncHandler(xController.create)
  );
``
But if payload is like this 
``
{
 "date": "2012-12"
} 
``
then it is accepted. I wanna force users to "2012-12-12T12:12Z" format

## Environment:

- Express-validator version:  6.14.1
- Express version: 4.16.4

**Comment by gustavohenke** [comment]
From https://github.com/validatorjs/validator.js#validators, it seems to me that `strict: true` means that the date must be a valid one, so February 29 on a non-leap year will be invalid.

Also note that ISO 8601 has a bunch of formats, so `2012-12` is actually valid.
https://en.wikipedia.org/wiki/ISO_8601

If you really want to accept only that format, I recommend you to use a regular expression instead.
E.g.

```js
body('date').matches(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}Z$/)
```
