### ISSUE TITLE
isDate validation not working with format

### ISSUE THREAD

**Issue by silvio-gratani** [express-validator/express-validator#1188]
I'm trying to have `isDate` working with custom pattern cannot figure out I still get errors, the docs are not very clear plus there is no example.

#### The router
```javascript
router.post(
    '/',
    body('from').notEmpty().isDate({ format: 'YYYY-MM-DD HH:MM:SS', delimiters: ['-', ' ', ':'] }).toDate(),
    body('to').notEmpty().isDate({ format: 'YYYY-MM-DD HH:MM:SS' }).toDate(),
)
```

#### Postman response
```json
{
    "errors": [
        {
            "value": "2022-01-01 10:10:00",
            "msg": "Invalid value",
            "param": "from",
            "location": "body"
        },
        {
            "value": "2022-01-01 12:10:00",
            "msg": "Invalid value",
            "param": "to",
            "location": "body"
        }
    ]
}
```

**Comment by gustavohenke** [comment]
The isDate functionality is provided by [validatorjs](https://github.com/validatorjs/validator.js).
This is stated in https://express-validator.github.io/docs/validation-chain-api.html#standard-validators.

Furthermore, there have been a number of reports around `isDate` before, see https://github.com/express-validator/express-validator/issues?q=is%3Aissue+sort%3Aupdated-desc+isdate+is%3Aclosed, it's a hard one to use and probably not very flexible.

[Here's its implementation](https://github.com/validatorjs/validator.js/blob/531dc7f1f75613bec75c6d888b46480455e78dc7/src/lib/isDate.js).

**Comment by silvio-gratani** [comment]
I solved my problem using `isISO8601()`.

**Comment by chelizichen** [comment]
> isISO8601

thanks
