### ISSUE TITLE
Validations problems with .optional()

### ISSUE THREAD

**Issue by guicompeng** [express-validator/express-validator#1206]
## Describe the bug

When create a const with validation and insert .optional() in just one route, this field is optional in all other routes 

## To Reproduce
```javascript

const validateName = body("name").isLength({ min: 3 });

app.post('/test', validate([
    validateName
]), async (req, res, next) => {
    res.json({ success: true });
});

app.patch('/test', validate([
    validateName.optional()
]), async (req, res, next) => {
    res.json({ success: true });
});
```
The `validate`function is equal this: https://express-validator.github.io/docs/running-imperatively#example-standardized-validation-error-response
## Expected behavior

The `name` in body should be optional only in patch and not in post

## Current behavior

The `name` in body is optional in post and patch

## Environment:

- Express-validator version:  6.14.3
- Express version: 4.18.2
- Node.js version: 16.19.0

**Comment by gustavohenke** [comment]
Yup, the chain reference is the same, so the any additional validations are carried over to all of them.

You can use a factory function instead:

```js
const createNameValidator = () => body('name').isLength({ min: 3 });

app.post('/test', validate([
    createNameValidator()
]), async (req, res, next) => {
    res.json({ success: true });
});

app.patch('/test', validate([
    createNameValidator().optional()
]), async (req, res, next) => {
    res.json({ success: true });
});

```
