### ISSUE TITLE
checkSchema unset validator

### ISSUE THREAD

**Issue by mjlehrke** [express-validator/express-validator#1223]
Hello,

Wondering the best way to do this with v7. I use generator functions that output re-usable schemas with some default validation and sanitization. Sometimes I want to disable a validator for a specific form field.

When upgrading to v7 I now get a console warning for the way I had been doing this, which leads me to believe I was doing it incorrectly. Below is a simplified version.

```js
const { checkSchema } = require('express-validator');

const sharedSchema= require('./shared-schema');

module.exports = checkSchema({
  first: {
    ...sharedSchema.text,
    // by default this output includes isLength validator
  },

  second: {
    ...sharedSchema.text,
    isLength: false,
  },
});
```

So if I wanted to disable a specific default, I would just set it to false as above. This now produces the console warning that 'isLength' is unknown. 

I suppose I could copy the generator schema output to a new object and do `delete copyOfSchema.isLength` and then use that in the final schema.

Is there a built in way to do this that I'm missing?

**Comment by gustavohenke** [comment]
> Is there a built in way to do this that I'm missing?

No, you just found a bug.

> I suppose I could copy the generator schema output to a new object and do delete copyOfSchema.isLength and then use that in the final schema.

If this works, for now..?

I'll get it fixed.

**Comment by gustavohenke** [comment]
done, released v7.0.1 with a fix 🙂

**Comment by mjlehrke** [comment]
Awesome, thanks for the quick work!

**Comment by mjlehrke** [comment]
@gustavohenke possibly another related bug.

"if" is showing as an unknown validator any time it is used in a schema.

**Comment by gustavohenke** [comment]
Correct 🙂
