### ISSUE TITLE
validationResult(req).array() return type

### ISSUE THREAD

**Issue by siddtheone** [express-validator/express-validator#1224]
As mentioned at https://express-validator.github.io/docs/migration-v6-to-v7#renamed-properties
When I try to read `errors[0].path` I got type error.

![image](https://user-images.githubusercontent.com/45398971/232797154-a649aec7-c3bb-46f2-8436-aafc57747a61.png)

Why the type of path is `any` instead of `string` as mentioned in https://express-validator.github.io/docs/api/validation-result#fieldvalidationerror
`Result<ValidationError>` may not always have path property.

**Comment by siddtheone** [comment]
![image](https://user-images.githubusercontent.com/45398971/233110380-f6aa9e6f-80e4-4593-b4e6-2a3f919d27ef.png)


![image](https://user-images.githubusercontent.com/45398971/233110667-739a21a2-de2f-4e32-8128-e0959b2cf1c0.png)

![image](https://user-images.githubusercontent.com/45398971/233111175-b1388510-dfd1-4f18-9bca-4ff248418d67.png)

As of now I'm not sure how to fix this error in `signup.ts`

**Comment by gustavohenke** [comment]
You still need to filter by the `type` property. This will make TS automatically infer that the type is `FieldValidationError`.
