### ISSUE TITLE
Does Express Validator runs all the validation in async mode? 

### ISSUE THREAD

**Issue by md-redwan-hossain** [express-validator/express-validator#1227]
Does Express Validator runs all the validation in async mode?  I went through the docs and saw that Express Validator v6 was using await check(field) syntax, but the latest version does not. Does that mean that all the validations are working in synchronous way?

**Comment by gustavohenke** [comment]
Within a validation chain, the validators and sanitizers are always run in sequence.

Multiple validation chains run in sequence too if they are passed directly to express (that's its own model with middlewares), but some of express-validator functions might run them in parallel, such as `oneOf()` and `checkExact()`.
