### ISSUE TITLE
Validate time

### ISSUE THREAD

**Issue by suzy-g38** [express-validator/express-validator#1228]
Does the express-validator have anything to validate the time?

If Yes, then it would be really helpful if anybody provide the details.
If No, then Why?

**Comment by gustavohenke** [comment]
You can try `isTime`. It's implemented in validator.js, which express-validator to provide much of the built-in functionality.

https://express-validator.github.io/docs/api/validation-chain/#istime
https://github.com/validatorjs/validator.js#validators
