### ISSUE TITLE
isMobilePhone rejects valid Sudanese numbers

### ISSUE THREAD

**Issue by Hussienma** [express-validator/express-validator#1232]
## Describe the bug

Valid Sudanese phone numbers are not being validated accurately with isMobilePhone

## To Reproduce

A phone number in the format +249XXXXXXXXX

## Expected behavior

validationResult() return no errors

## Current behavior

validationResult() returns errors

## Environment:

- Express-validator version: 7.0.1
- Express version: 4.17.1
- Node.js version: 16.16.0

**Comment by gustavohenke** [comment]
Hi, please see https://express-validator.github.io/docs/guides/validation-chain

> Please report bugs in the validators/sanitizers (such as a value that shouldn't be valid but is, or vice versa) to [validator.js](https://github.com/validatorjs/validator.js).
