### ISSUE TITLE
Schema doesn't suppor multiple custom validators

### ISSUE THREAD

**Issue by sombra-bykov-vladyslav** [express-validator/express-validator#1237]
## Expected behavior

Schema-supported custom validators array as mentioned in the change log  for v. 7.0.1

## Current behavior

I have a type issue:  "Type 'ValidatorSchemaOptions<"custom">[]' is not assignable to type 'ValidatorSchemaOptions<"custom">'."

## Environment:

- Express-validator version: 7.0.1
- Express version: 4.18.1
- Node.js version: 18.16.1

**Comment by gustavohenke** [comment]
What's your code like?
