### ISSUE TITLE
Property 'errors' is private and only accessible within class 'Result<T>'.

### ISSUE THREAD

**Issue by ctooley21** [express-validator/express-validator#1241]
## Describe the bug

The `errors` property for `ResultWithContext` is marked as private on package version `7.0.1` and TypeScript version `5.1.6`

## To Reproduce

Follow the TypeScript example on the [docs site ](https://express-validator.github.io/docs/guides/manually-running)

## Expected behavior

The property is accessible

## Current behavior

A typescript error is generated, and typescript building fails with the error:
`error TS2341: Property 'errors' is private and only accessible within class 'Result<T>'.`

## Environment:

- Express-validator version: 7.0.1
- Express version: 5.0.0-beta.1
- Node.js version: 18.16.1

**Comment by gustavohenke** [comment]
> The property is accessible

Nope, that's not desired behaviour - the docs are incorrect, they should be fixed

**Comment by ctooley21** [comment]
> > The property is accessible
> 
> Nope, that's not desired behaviour - the docs are incorrect, they should be fixed

Understood. Can you provide any guidance on how to exit a custom validation run if one of the validation chains fails?

**Comment by wmtrinu** [comment]
have you found a way to resolve this?

**Comment by gustavohenke** [comment]
Use [`Result#array()`](https://express-validator.github.io/docs/api/validation-result#array).

**Comment by gustavohenke** [comment]
The way I wrote this docs page was a bit nonsense too, so I fixed that up. Sorry team! 🫡
