### ISSUE TITLE
Validation on nested fields not working.

### ISSUE THREAD

**Issue by tony-sunny** [express-validator/express-validator#1245]
## Describe the bug

For some inputs, validation on nested fields accessed by dot (.) is not returning error
This was working in v6 but changed in  v7

## To Reproduce

Please check https://runkit.com/tony-sunny/6503695da7894b0008762533

## Expected behavior

Expected validation chain to return error

## Current behavior

There are no errors in validaiton result

## Environment:

- Express-validator version:  7.0.1
- Express version: 4.18.2
- Node.js version: 18.16.1

**Comment by fedeci** [comment]
Opened a PR

**Comment by gustavohenke** [comment]
This is fixed on https://github.com/express-validator/express-validator/releases/tag/v7.2.0
