### ISSUE TITLE
Empty array as default value not working.

### ISSUE THREAD

**Issue by yerycs** [express-validator/express-validator#1249]
```
checkSchema({
  field: {
    isArray: {
      bail: true
    },
    optional: true,
    default: {
      options: [],
    },
  },
}, ['query'])
```
`[]` as `default` value is not working. Other string, number default values are working

https://codesandbox.io/p/sandbox/gallant-smoke-r89hcy?file=%2Findex.js%3A29%2C9

How can I make it work?

**Comment by gustavohenke** [comment]
Hey! When you want to pass an array as argument to the validator/sanitizer, you need to wrap it in another array, so it looks like this

```js
default: {
  options: [[]],
}
```

There's a note under https://express-validator.github.io/docs/api/check-schema#validator-options which should maybe be made more prominent/duplicated around to make it more evident 😊
