### ISSUE TITLE
isDate() returns false on "2021-02-12" for express-validator v7

### ISSUE THREAD

**Issue by ningji** [express-validator/express-validator#1251]
## Describe the bug

Upgrading express-validator from 6.14.2 to 7.0.1 might break isDate()

## To Reproduce

Original working code on 6.14.2,
 
const dateValidator = check("date").optional({ checkFalsy: true }).isDate();

app.post(
    "/path1",
    [dateValidator], // simplified the code, just a very best validator
    async (req, res) => {
        ... process the req ...
    }
); 

1. on v6, unit test passes with this body
   req.body = { date: "2021-02-12", ... }
2. upgrade to v7 from
    yarn upgrade-interactive --latest
    only pick express-validator to upgrade
3. run unit test again, error message says
    text: '{"errors":[{"type":"field","value":"2021-02-12","msg":"Invalid value","path":"date","location":"body"}]}'

- Express-validator version: 7.0.1
- Express version: 4.18.2
- Node.js version: 16.16.0
- Yarn version: 1.22.19

**Comment by fedeci** [comment]
I am investigating

**Comment by fedeci** [comment]
@ningji i cannot repro this issue, this is what I tried
```js
const express = require('express')
const { check } = require('express-validator')

const app = express()

app.post('/patch1', [check('date').optional({ checkFalsy: true }).isDate()], async (req, res) => {
  res.sendStatus(200)
})

app.listen(3000, () => {
  console.info("Listening on port 3000")
})
```

I used the latest `express` and `express-validator` versions and the following curl command 
```bash
curl --location 'http://localhost:3000/patch1' \
--header 'Content-Type: application/json' \
--data '{
    "date": "2021-02-12"
}'
```

**Comment by ningji** [comment]
@fedeci Very interesting, did you use yarn install or npm install ? i kind of suspect this is a package issue now

**Comment by fedeci** [comment]
I am using `npm@10.1.0`

**Comment by ningji** [comment]
Thanks very much ! i'm closing it now.
