### ISSUE TITLE
Re-use validators on the front end?

### ISSUE THREAD

**Issue by ArkinSolomon** [express-validator/express-validator#1252]
Hello, 

I am currently writing my front-end in React, and instead of re-implementing all of my validators on the client, I would like to be able to reuse the validators. Currently each function takes in a `ValidationChain` and returns the `ValidationChain`, could I set up a wrapper function to create a wrapper chain and then return the result of the validation chain? Does such functionality exist?

For instance: 

```ts

/**
 * Ensure that a provided value can be a name.
 * 
 * @param {ValidationChain} chain The source of the value to validate.
 * @returns {ValidationChain} The validation chain provided to an Express route, or used for further modification.
 */
export function isValidName(chain: ValidationChain): ValidationChain {
  return chain
    .trim()
    .notEmpty().bail().withMessage('invalid_or_empty_str')
    .custom(value => !isProfane(value)).bail().withMessage('profane_name')
    .custom(value => /^[a-z][a-z0-9\x20-.]+[a-z0-9]$/i.test(value)).withMessage('invalid_name');
}
```

Ideally I should be able to write another function (or overload), and call it, like the following `isValidName(name: string): string | null;`, which will then call `isValidName()`. Does this functionality exist?

**Comment by fedeci** [comment]
Hello @ArkinSolomon you can execute this kind of logic by running chains in an imperative way, see [docs](https://express-validator.github.io/docs/guides/manually-running) for reference. Please ping me for further help!

**Comment by ArkinSolomon** [comment]
Thanks for your fast response, however this does not answer the question. I basically want to just pass a string in, not pull it from a body or anything. There is no request object as this is simply validating on the client side before submission.

**Comment by fedeci** [comment]
I have been quite absent from the project in the last year and a half, but at a quick glance it seems nothing changed to me and you still need to provide a req object, you can create a mock one just to be passed to validate to express-validator.
```ts
// data you need to validate
const name = 'Federico'
const age = 21

// helper function
const validate = validations => {
  return async (req, res, next) => {
    for (let validation of validations) {
      const result = await validation.run(req);
      if (result.errors.length) break;
    }

    const errors = validationResult(req);
    return errors.array()
  };
};

const validators = [
  body('name').isString().isLength({ min: 4, max: 20 }),
  body('age').isInt(),
]

const validationChain = validate(validators)
const req = {
  body: {
    name,
    age
  }
}
const errors = await validationChain.run(req) // You can then reuse req.body to compose the request to the server
if errors.length === 0 {
  // perform server request here
} else {
  // handle errors in the UI
}
```
