### ISSUE TITLE
How can I prevent isStrongPassword() accepting whitespaces?

### ISSUE THREAD

**Issue by EMILO9** [express-validator/express-validator#1263]
```js
body("password").isStrongPassword({
      minLength: 8,
      minLowercase: 1,
      minUppercase: 1,
      minNumbers: 1,
      minSymbols: 1,
      returnScore: false,
      pointsPerUnique: 1,
      pointsPerRepeat: 0.5,
      pointsForContainingLower: 10,
      pointsForContainingUpper: 10,
      pointsForContainingNumber: 10,
      pointsForContainingSymbol: 10,
    })
```

**Comment by gustavohenke** [comment]
Hey!
I think `isStrongPassword` only applies a series of heuristics to determine if the password might be good enough, according to your parameters. Whitespaces would probably fall under symbols.

It might be a better idea to use `.not().matches(/\s/)` as another validator.

---

But I'm curious... why make _any_ assumptions about a password? 🤔 
Pretty sure this might make your system less safe/inconvenient..
