### ISSUE TITLE
Able to use validation inside controller?

### ISSUE THREAD

**Issue by Rexyou** [express-validator/express-validator#1265]
Hi there,

I was trying to use one of the function from _**CommonController**_ in other controller, but I found out that express validator only can work in **_routing_** level. So may i know is this possible to use it in controller which act like routing level to filter request body?
Below provide some samples which generate from ChatGPT but I tested all cannot filter the req.

_**Validation**_
```
const { body, validationResult } = require('express-validator')

const SendEmailValidator = [
    body('to_address')
        .notEmpty().withMessage('email_cannot_be_empty')
        .isLength({min:8, max: 40}).withMessage('email_length_incorrect')
        .isEmail().withMessage('email_format_invalid'),

    body('subject')
        .notEmpty().withMessage('subject_cannot_be_empty')
        .isLength({min:10, max: 200}).withMessage('subject_length_incorrect')
        .matches(/^[\w\d\s\,\.\_\-\/]+$/).withMessage('subject_format_invalid'),

    body('text')
        .notEmpty().withMessage('text_cannot_be_empty')
        .isLength({min:1, max: 355}).withMessage('text_length_incorrect')
        .matches(/^[\w\d\s\,\.\_\-\/]+$/).withMessage('text_format_invalid'),

    // (req, res, next) => {
    //     const errors = validationResult(req);
    //     if (!errors.isEmpty()) {
    //         return res.status(422).json({ status: false, data: "", message: errors.array(), code: 422 });
    //     }
    //     next();
    // },
]

module.exports = {
    SendEmailValidator
}
```

**_CommonController_**
      
       const sendEmail = [SendEmailValidator, async (req, res) => {
                  
          const errors = validationResult(req)
          console.log(errors)
          if(!errors.isEmpty()){
              return { status: false, data: '', message: errors.array(), code: 422 }
          }
      
          console.log(req.body)
      
          const { to_address, subject, text } = req.body  
      
          const input = {
              "from": process.env.EMAIL_USER,
              "to": to_address,
              "subject": subject,
              "text": text
          }
      
          const transporter = nodemailer.createTransport(config)
          await transporter.sendMail(input)
      
          return { status: true, data: '', message: "success", code: 200 }
      }]
  
      module.exports = {
          sendEmail
      }

**_Other Controller Usage_**
```
        const result = await sendEmail[1]({  }, res)
        console.log(result)
        if(!result.status){
            return res.status(result.code).json(result);
        }
```

**Comment by fedeci** [comment]
Hi @Rexyou, I am not sure about what you are trying to achieve. Is the `sendEmail` function to be called imperatively? By "filter request body", do you mean removing params that do not match the validation chains?

**Comment by Rexyou** [comment]
hi @fedeci , 
yes the `sendEmail` will be use in other controller so I was try to validate the request body inside the `sendEmai`l function rather than use it in routing as middleware. So its possible to do it in controller?

**Comment by vpn** [comment]
Any update on this @Rexyou ?

**Comment by fedeci** [comment]
Hi, this is an example of how to run a validator/validation chain from the controller level (or from any piece of code other than the express routing level actually) https://express-validator.github.io/docs/guides/manually-running

Let me know if this helps.

**Comment by fedeci** [comment]
I'm closing this issue, let me know if you need any more help.
