### ISSUE TITLE
How to use if inside ParamSchema?

### ISSUE THREAD

**Issue by dfyz011** [express-validator/express-validator#1266]
Hello.
I have such construction in couple of places
```js
import type { Schema } from 'express-validator';

export const schema: Schema = {
  orderId: {
    // @ts-ignore TODO: no type in express-validator but works
    if: {
      options: (v, { req }) =>
        condition
          ? !v
          : false,
    },
    isInt: true,
    toInt: true,
  },
};
```
It worked before on version 6.2.0, but as you can see I used @ts-ignore because without it had error _"Object literal may only specify known properties, and 'if' does not exist in type 'ParamSchema<DefaultSchemaKeys>"_

But now, after I updated express-validator to 7.0.1 this not working anymore and also I have error inside my console after build _"express-validator: schema of "orderId" has unknown validator/sanitizer "if""_

That why i decided to finally create issue and ask: Is it me doing something wrong?
Link to documentation https://express-validator.github.io/docs/api/check-schema#if
Seems like I should use if only inside validator, like this?
```js
import type { Schema } from 'express-validator';

export const schema: Schema = {
  orderId: {
    isInt: {
      if: (v, { req }) =>
        condition
          ? !v
          : false,
    },
    toInt: true,
  },
};
```
But will it ignore everything(other validators, customs, sanitizers) after "isInt" key or only validators?

**Comment by fedeci** [comment]
> That why i decided to finally create issue and ask: Is it me doing something wrong? Link to documentation [express-validator.github.io/docs/api/check-schema#if](https://express-validator.github.io/docs/api/check-schema#if) Seems like I should use if only inside validator, like this?
> 
> ```js
> import type { Schema } from 'express-validator';
> 
> export const schema: Schema = {
>   orderId: {
>     isInt: {
>       if: (v, { req }) =>
>         condition
>           ? !v
>           : false,
>     },
>     toInt: true,
>   },
> };
> ```
> 
> But will it ignore everything(other validators, customs, sanitizers) after "isInt" key or only validators?

Yes it will ignore everything after `isInt`. We decided to move it because now you can add more than one `if` and place it accurately before a chosen validator.
Behind the scenes `checkSchema` behaves like a validation chain and validators are run in the same order they are added to the object. I know this is a little bit counter-intuitive because order in objects usually doesn't matter, but in this case it does.
