### ISSUE TITLE
 notEmpty Validation Fails to Detect Empty String with Spaces, Allowing Insertion of Empty  String into Database"

### ISSUE THREAD

**Issue by Rathan-07** [express-validator/express-validator#1283]
## Describe the bug

 **The notEmpty validation function in express-validator fails to correctly detect an empty string that contains only spaces. This issue leads to the improper validation of whitespace-only strings ("   "), allowing them to pass through the validation process and subsequently get inserted into the database as an empty string("")**

## To Reproduce

```js
const categorySchema = new Schema({
  name:String
}, { timestamps: true });

const Category = model('Category', categorySchema);
// create Validator schema

const categoryValidationSchema = {
  name:{
    in:['body'],
    exists:{
      errorMessage:'Name is required'
    },
    notEmpty:{
      errorMessage:'Name cannot be empty'
    },
    trim:true,
    custom:{
      options:function(value){
        return Category.findOne({name:value})
        .then((obj)=>{
          if(obj){
            throw new Error('category  name already exists')
          }
          return true
         
        })
      }
    },

  }
}
```

## Expected behavior

**The isEmpty validation should correctly identify a string containing only spaces as non-empty and reject it.**

## Current behavior

**The isEmpty validation incorrectly considers a string containing only spaces as empty, allowing it to pass validation and resulting in the insertion of empty strings into the database.**

## Environment:

- Express-validator version: 7.0.1
- Express version: 4.18.2
- Node.js version: [20.3.0]
-

# Images of script and  error response

![notEmpty-validation](https://github.com/express-validator/express-validator/assets/91273271/e69541b2-c617-4974-923c-a891576ccef4)

![error-response](https://github.com/express-validator/express-validator/assets/91273271/a6ba0c99-cb8c-4151-942a-189997a197af)

# Solution for the above bug   

**One of the solution for the above bug is custom validation as shown in the image below:**
![custom-validation ](https://github.com/express-validator/express-validator/assets/91273271/70b7dd8c-c8c0-4585-9575-24a5b7616f79)

**Achieved the correct response after applying custom validation as shown in the image below:**
![correct-response](https://github.com/express-validator/express-validator/assets/91273271/d1e4e64f-a1be-4ddf-8d1f-7097df71235b)

**Comment by gustavohenke** [comment]
Ordering matters.
See here https://express-validator.github.io/docs/guides/validation-chain#chaining-order
