### ISSUE TITLE
Apply bail to the whole chain

### ISSUE THREAD

**Issue by kratess** [express-validator/express-validator#1290]
## Is your feature request related to a problem? Please describe.

using a checkSchema like this:

```
checkSchema({
  category: {
    notEmpty: {
      bail: true,
      errorMessage: "must not be empty"
    },
    isString: {
      bail: true,
      errorMessage: "must be a string"
    },
    custom: {
      options: async (category, { req }) => {
        if (!req.author.categories.find((cat) => cat.name === category)) {
          throw new Error("not in your permissions");
        }
      }
    }
  }
})
```

It's redundant to use bail each time.

## Describe the solution you'd like

Add a property that instead apply automatically bail to all components of chain.

**Comment by gustavohenke** [comment]
Hey - I understand it's not optimal, but it's how you'd do without `checkSchema`, too.
You might want to tinker with your validators to make sure you're only setting it where it'll be the most impactful.

**Comment by az-oolloow** [comment]
This would've been amazing. I pretty much can barely think of a scenario where I wouldn't want `bail()`.
