### ISSUE TITLE
The isIn method mismatch the expectation result

### ISSUE THREAD

**Issue by kratess** [express-validator/express-validator#1291]
## Is your feature request related to a problem? Please describe.

The isIn method mismatch the expectation result.

```
    isIn: {
      options: ["PUBLISHED", "DRAFT"],
      errorMessage: "must be a valid type: 'DRAFT', 'PUBLISHED'"
    }
```
a code like this would only work with the first value in the array so with "PUBLISHED".
to make things work you should wrap into an array again:
```
    isIn: {
      options: [["PUBLISHED", "DRAFT"]],
      errorMessage: "must be a valid type: 'DRAFT', 'PUBLISHED'"
    }
```
this method is so ambiguous that you will not understand what it really does even if you search the problem through issues.
why i need to wrap it into an array again?

## Describe the solution you'd like

Change the method to take directly an array and check all its values

**Comment by kratess** [comment]
Another strange result is using `options: ["PUBLISHED,DRAFT"]` and this works? huh

**Comment by gustavohenke** [comment]
`isIn` is specifically called out in the docs:
https://express-validator.github.io/docs/api/check-schema#validator-options

As for `options: ["PUBLISHED,DRAFT"]` working - seems like indeed some weird behaviour of `isIn`. It's not documented well in validator.js docs either.

https://github.com/validatorjs/validator.js/blob/4197b8632522818164cc05d8d6cb44c98eb3decd/src/lib/isIn.js#L19-L20
