### ISSUE TITLE
Bug: Object as input, IsInt returning no error and passing validation.

### ISSUE THREAD

**Issue by mai1x9** [express-validator/express-validator#1293]
## Describe the bug

Applying IsInt on object is passing validation instead of throwing error. 

Code:
```
body("age").optional({nullable: true}).isInt({min:0, max:100}).custom(value => {
    console.log("Not throwing error" , value, typeof value) // age is [34] and it still passes validation without error.
    return true
  })
```

## To Reproduce

Its a development environment with lot of code, but its pretty straighht forward that object is passing validation for IsInt instead of throwing error.

## Expected behavior

- Throws validation error since object is not integer.

## Current behavior

- Passing validation.

## Environment:

- Express-validator version: 6.10.0
- Express version: 
- Node.js version:

**Comment by gustavohenke** [comment]
See https://express-validator.github.io/docs/6.10.0/validation-chain-api#bail

**Comment by mai1x9** [comment]
> See https://express-validator.github.io/docs/6.10.0/validation-chain-api#bail

Why was this closed and it has nothing to do with `bail`.

My simple question is POST  request is sending the data as `[34]` and i kept check isInt() and it is not falling, rather passing the step. Why ? thats my question. 


If i use .custom() and check if its integer and then throw error it is working. So technically the inbuild `isInt()` is not working.

**Comment by mai1x9** [comment]
@gustavohenke 
when the input is string it throwed the error, (param 'age')
```
{
    "errors": [
        {
            "value": "ageasstring",
            "msg": "Invalid value",
            "param": "age",
            "location": "body"
        }
    ]
}
```
But when the input is `[35]`, it passed validation. I think the check for integer is not done properly and please check the code, else update the document. Even array of integers are passing `isInt()`. Its better to update the document to say, it will validate every element in the array if array is passed or be specfic that , it is only for the integer.

### This has literally killed hours of time to debug why the validation was passed and apparently the issue is in the code.

**Comment by mai1x9** [comment]
it has nothing to do with `bail`, you should have provided the reference to: https://github.com/express-validator/express-validator/issues/791 and told to update to v7.0.0.
