### ISSUE TITLE
Please add index in Meta custom Validation

### ISSUE THREAD

**Issue by solanoize** [express-validator/express-validator#1297]
The case here, I want to check the stock item in the array, on the next check, I need an index to retrieve the previous stock data.

```
body("items.*.stock")
    ....,
body("items.*.qty")
    ....
    .custom(async () => { 
      // i need to get stock for check qty,
      // how i get stock ?, i not found index items to get stock
    })
```

For example:

```
.custom((stock, { path, req }) => {
      const index = Number(path.replace(/\D/g, "")); // ?? hardcode? 
      const price = req.body.items[index].price;
      console.log(price, stock);
    }),
```

**Comment by gustavohenke** [comment]
Hey. Thanks for the suggestion, it's a great one.

**Comment by gustavohenke** [comment]
This is implemented on https://github.com/express-validator/express-validator/releases/tag/v7.2.0.

Check out the relevant docs [here](https://express-validator.github.io/docs/api/validation-chain#custom)
