### ISSUE TITLE
Calling `.trim().isString()` passes for numbers

### ISSUE THREAD

**Issue by juan-cyb** [express-validator/express-validator#1303]
Given `myfield=123`, I've noticed that calling `body('myfield').trim().isString()` passes, because `trim()` turns `123` into `"123"` (a string), which passes the `isString()` check.

Is it recommended to call `body('myfield').isString().trim().isString()` instead, or would a dedicated `.isSTrimmedString()` make more sense here (if so, I can send PR)?

**Comment by chonydev** [comment]
I have the same problem. Did you try with the body('myfield').not().isNumeric() ?. At least, it will filter numbers.

**Comment by juan-cyb** [comment]
> Did you try with the body('myfield').not().isNumeric() ?. At least, it will filter numbers.

Unfortunately, `body('myfield').trim().isString()` succeeds when I submit `123`, `true`, `{}`, so it might become a bit unwieldy to have a `.not` for each type :)

It's OK - I'll just use the workaround in the meantime.
