### ISSUE TITLE
In custom() validator, please add option not to include its value in response

### ISSUE THREAD

**Issue by skysign** [express-validator/express-validator#1304]
## Is your feature request related to a problem? Please describe.
In ValidationChain, we might want to keep that certain query parameter is secured.
To secure query parameter, it should not be included HTTP response, even its custom validator is finalized as reject().

We can assume that the query parameter is API key.
If the API key is included in HTTP response, it can be written in a kind of log message.
It means that API key is exposed.

I mean API key query parameter should be handled like github action secret.

## Describe the solution you'd like
In ValidationChain, I hope to add new parameter in query() function.
To notice that the query parameter should be secured.

**Comment by gustavohenke** [comment]
Hey, without looking at your code, can you take a look at `ValidationResult#formatWith` and let me know if that works for you?
Here's it in the docs: https://express-validator.github.io/docs/api/validation-result#formatwith

**Comment by skysign** [comment]
Hi @gustavohenke 

Thanks for your comment.
I think that [formatwith](https://express-validator.github.io/docs/api/validation-result#formatwith) might be used for my problem.

However, I still think that this feature is good for express-validator.
To explain my issue, I've written example code below.

`
const router = express.Router()

async function myValidationResult(req: Request, res: Response, next: NextFunction) {
  const result = validationResult(req);
  if (!result.isEmpty()) {
    return res.status(400).json({ errors: result.array() })
  }

  return next();
}

function validationRules(): any[] {
  return [
    query('api_key', 'api_key is invalid.') <- Adding parameter here, to make api_key like github action secret
      .custom(async (api_key) => {
        const userldapDN = getLDAPDNfromAPIkey(api_key) <- This is our own logic for authentication
        const b = await IsValidAPIKey(api_key, userldapDN)

        return new Promise((resolve, reject) => {
          if (b) {
            resolve(b)
          }
          else {
            reject()
          }
        })
    })
  ]
}

router.get('/example-endpoint', validationRules(), myValidationResult, doExampleEndpoint)
`

Here is my example code to explain this issue.
we keep using myValidationResult() as there are a bit long validation rules.
Just we handle api_key something like github anction secret.

**Comment by skysign** [comment]
It's very hard to write example code pretty.
Please see my gist below, to see my example code with pretty format.
https://gist.github.com/skysign/bf783d5df1b62260c5e0db0f3d119f6c

**Comment by gustavohenke** [comment]
I see. It'd be a bit cumbersome to manually filter out using `formatWith`.

Maybe something like `ValidationChain#hide()` would be good here.

**Comment by skysign** [comment]
I'd like to contribute for implementing this feature,
Could you describe a bit more about your idea?

**Comment by gustavohenke** [comment]
1. Add a method named that to the `ContextHandler` interface, which sets a `hidden` flag to the context:
  https://github.com/express-validator/express-validator/blob/bec1dcbaa29002dcd21093ec84818c4671063b5d/src/chain/context-handler.ts#L47
2. When `Context#addError()` is called, if the context is hidden, omit the value:
  https://github.com/express-validator/express-validator/blob/bec1dcbaa29002dcd21093ec84818c4671063b5d/src/context.ts#L116-L123

**Comment by skysign** [comment]
Thanks for your comment, let me start to implement it.

**Comment by powersjcb** [comment]
oh thanks for tackling this. This is very similar to an issue I raised against joi.

**Comment by gustavohenke** [comment]
This is fixed on https://github.com/express-validator/express-validator/releases/tag/v7.2.0 😃

**Comment by skysign** [comment]
> This is fixed on https://github.com/express-validator/express-validator/releases/tag/v7.2.0 😃

Thanks for quick release 👍
