### ISSUE TITLE
default property is not recognized

### ISSUE THREAD

**Issue by itayzemah** [express-validator/express-validator#1306]
## Describe the bug

I want to add a `default` value to my validator. 
The TS compiler says that the type is not valid.

## To Reproduce
```
checkSchema({
 pageSize: {
        in: 'body',
        toInt: true,
        optional: true,
        default: 25,
        isInt: { options: { min: 1, max: 500 } },
        errorMessage: 'Invalid pageSize. Range is 1 to 500',
    },
})`
```
## Expected behavior

The `pageSize` property in the `body` will be replace into `25` when the value is '', null, undefined or NaN

## Current behavior

Type error

## Environment:

-   "express-validator": "^7.1.0",
-   "express": "^4.19.2",
- Node.js version: 20

![image](https://github.com/user-attachments/assets/81c8becf-55f0-4b90-a12a-4a662f030620)

**Comment by gustavohenke** [comment]
Hey. You're close, you need to set `{ options: 25 }` instead.

https://express-validator.github.io/docs/api/check-schema#validator-options
