### ISSUE TITLE
Validation in/after get/post routes

### ISSUE THREAD

**Issue by Bimbimz** [express-validator/express-validator#1311]
Is it possible to do something like this below?
```
router.get('/', notHere, (req, res) => {
   // VALIDATION HERE
   // Example:
   // req.body.email.isEmail()

    res.send('Hello')
})
```

**Comment by gustavohenke** [comment]
Yes, just follow https://express-validator.github.io/docs/guides/manually-running and adapt it.

https://express-validator.github.io/docs/api/misc#contextrunner is short, but might also be useful.
