### ISSUE TITLE
default object for default() sanitizer

### ISSUE THREAD

**Issue by zahari4i** [express-validator/express-validator#1316]
## Describe the bug

I believe this is critical.

Providing an object as a default value for a field (ex: .default({}) ) will keep the same exact object between requests instead of creating a new object for every request.

## To Reproduce

Create a validation chain providing an object as the default value for a field. Change or add any value to the object. Repeat the request, now the default object is the object from the previous request.

## Expected behavior

A new object should be created on every request.

## Current behavior

The object is created only on the first request, then the same object is used in every subsequent request.

Example here: https://codesandbox.io/p/devbox/express-js-forked-l567pp
Reload the same page and you'll see the id incrementing between requests.

## Environment:

- Express-validator version: 7.2.0
- Express version: 4.16.4
- Node.js version: 20.11.0

**Comment by gustavohenke** [comment]
Hey, thanks for reporting this. It's been fixed and published as v7.2.1.
