### ISSUE TITLE
Support for Restify (Typescript)

### ISSUE THREAD

**Issue by mitjarogl** [express-validator/express-validator#407]
I try to use this package as middleware in Restify project written in Typescript. There are some problems with casting of Request handlers. In order to work with Restify I had to use this hack. 

   `api.use(expressValidator() as any);`

Is it possible to change  to work with Restify. Thanks.

**Comment by gustavohenke** [comment]
It's nice to see that you can actually use express-validator with a server framework that's not express 😃 

After a quick scan of the restify docs, it seems like most of the API is identical.
However, some changes would require typings to be sacrificed - for example, using custom validators, or requesting the validation result.

**Comment by mitjarogl** [comment]
Yes. Restify is lightweight version based on Express. It would be nice to have one package for both frameworks :)

**Comment by gustavohenke** [comment]
Hello!
Nearly 2 years later.. v6.0.0 is out. It is fully written in TypeScript, and is friendly to Restify and other libraries that also pass a request object like express!
