### ISSUE TITLE
Should .exists() check for null values as well? 

### ISSUE THREAD

**Issue by moliver-bb** [express-validator/express-validator#473]
Currently the .exists() validator only checks for undefined, does it make sense to add an option to also check for null? Something like:
`
check('id').exists({ checkFalsy: true }) //or
check('id').exists({ checkNull: true })
`

or should we be using a different validator like notEmpty() or not().optional() ? 

Thanks so much for your help.

**Comment by dszmaj** [comment]
Would be extremely helpful.

**Comment by gustavohenke** [comment]
This issue is now up for grabs! Want to implement it? Please go ahead -- shouldn't be very difficult!

**Comment by sant123** [comment]
What about `.not().isEmpty().withMessage("The field cannot be empty")`?

**Comment by gustavohenke** [comment]
@sant123 `false` or `0` would succeed when check with `.not().isEmpty()`, as it will only check the string representation of the value has something in it (`null` and `undefined` are both represented as an empty string).

A `checkFalsy` option for `exists` would work differently, failing the validation if the value is falsy.
