### ISSUE TITLE
Better docs structure

### ISSUE THREAD

**Issue by gustavohenke** [express-validator/express-validator#515]
As the API surface grows, the docs get more difficult to read and navigate.

Some ideas to enhance the experience include:
- Add a small "Go to top" link after each section, so that the reader can use the table of contents more commonly
- Break the docs into multiple markdown files
- Publish the docs to an external tool like [Read the Docs](https://readthedocs.org/), or even use GitHub Pages for that.

Any other ideas, folks?

**Comment by danger89** [comment]
I like to see this again: https://npmdoc.github.io/node-npmdoc-express-validator/build/apidoc.html

But for version 5.. That would be my idea. Using markdown is not good, it's outdated and especially its not COMPLETE.
