### ISSUE TITLE
check properties with special character

### ISSUE THREAD

**Issue by togonow** [express-validator/express-validator#544]
one of the request.body properties i need to check has special characters e.g.
request.body["http://www.somesite.com"].data
so checkBody('request.body["http://www.somesite.com"].data').exists();
always fails

**Comment by gustavohenke** [comment]
I couldn't replicate this:

<img width="1178" alt="screen shot 2018-03-22 at 20 15 46" src="https://user-images.githubusercontent.com/826553/37761455-d77e733e-2e0d-11e8-8c71-f42331fc2b33.png">

**Comment by togonow** [comment]
so it appears the issue arrise when the property is a nested value inside the body json object, check this out:
`
const {check , validationResult} = require('express-validator/check');
const {matchedData} =require('express-validator/filter');
const express = require('express');


const app = express();
app.use(express.json());
app.post('/*', [
    check('profile.visits'                      ,'param body.profile.visits not an int').isInt(),
    check('profile["visits"]'                   ,'param body.profile[visits] not an int').isInt(),
    check('profile["http://www.somsite.com"]'   ,'param body.profile["http://www.somsite.com"] not an int').isInt(),
    check('profile.\"http://www.somsite.com\"'  ,'param body.profile.\"http://www.somsite.com\" not an int').isInt(),
    check('profile[http://www.somsite.com]'     ,'param body.profile[http://www.somsite.com] not an int').isInt(),
    check('http://www.rootsomsiteInt.com'       ,'param body["http://www.rootsomsite.com"] not an int').isInt(),
    check('http://www.rootsomsiteShoudpass.com' ,'param body["http://www.rootsomsiteShoudpass.com"] not an int').isInt(),

], (req,res)=>{

    console.log(req.body);
    const data = matchedData(req);
    const result = validationResult(req);
    res.json({
        errors: result.mapped()
    });
})

app.listen(4000);
`

this is my post body
`{
  "profile": {
    "visits": 10,
    "http://www.somsite.com": 10
  },
  "hello.world": 5,
  "http://www.rootsomsite.com": "notInt",
  "http://www.rootsomsiteShoudpass.com": "5"
}`

and this is the response

`
{
    "errors": {
        "profile.http://www.somsite.com": {
            "location": "body",
            "param": "profile.http://www.somsite.com",
            "msg": "param body.profile[\"http://www.somsite.com\"] not an int"
        },
        "profile.\"http://www.somsite.com\"": {
            "location": "body",
            "param": "profile.\"http://www.somsite.com\"",
            "msg": "param body.profile.\"http://www.somsite.com\" not an int"
        },
        "http://www.rootsomsiteInt.com": {
            "location": "body",
            "param": "http://www.rootsomsiteInt.com",
            "msg": "param body[\"http://www.rootsomsite.com\"] not an int"
        }
    }
}
`
![screen shot 2018-03-22 at 10 41 32 am](https://user-images.githubusercontent.com/4708158/37788040-a5dc33c0-2dbd-11e8-9d82-a23540bdf2c6.png)
