### ISSUE TITLE
Issues with isIn()

### ISSUE THREAD

**Issue by n1mda** [express-validator/express-validator#574]
I'm having issues on getting `isIn()` to work as intended.

This is my method:
```javascript
const { body, validationResult } = require('express-validator/check')

app.post('/api/reports', [
    body('report_type').isIn(['DAILY', 'WEEKLY']),
], (req, res) => {
    const errors = validationResult(req)
    if (!errors.isEmpty()) {
        return res.status(422).json({ errors: errors.mapped() })
    }
})
```

This is a request (with valid `report_type`):
```bash
curl -X "POST" "http://localhost:9400/api/reports" \
     -d $'{
  "report_type": "WEEKLY"
}'
```

This is the response:
```json
{
  "errors": {
    "report_type": {
      "location": "body",
      "param": "report_type",
      "msg": "Invalid value"
    }
  }
}
```

**Comment by gustavohenke** [comment]
I'm afraid you're not adding a body parser, because there's no `value` in your `report_type` error. To solve this, add `app.use(express.json())` to your server code.

If you already have this line, then it must be because you didn't specify a `Content-Type` header in your request.

**Comment by n1mda** [comment]
Aha @gustavohenke, that is correct. I was not specifying `Content-Type: application/json` in my request, hence it failed. It works with this header.

This is most likely off-topic, but shouldn't express return `415 Unsupported Media Type` instead of failing at what appears to be random places?

**Comment by gustavohenke** [comment]
I don't think express gets that much into the way of the user... the only thing I know it does is respond with `404` when you don't handle the request.

Also, it wouldn't be very wise for a library to reject the request if it doesn't have the correct `Content-Type`.
You, as a user of the library, may parse the request body however/wherever/whenever you want, and rejecting it prematurely would need knowledge of all MIME types you're willing to parse at that point.

I hope you can see how this could easily become a monster 😄

**Comment by gustavohenke** [comment]
On a side note: #518 is likely a duplicate of this one.
It might be good to update the docs to show the body parsing... 😉 


<sub>_(PRs accepted!)_</sub>
