### ISSUE TITLE
sanitizers does not run if the value is not a string

### ISSUE THREAD

**Issue by Bene-Graham** [express-validator/express-validator#580]
I noticed the following when writing unit test for my middleware.
Take the following example:

Excerpt from body:
```
req.body = {
     isHappy: 1234
}
```
Excerpt from middleware array
```
checkBody("isHappy")
        .toBoolean(true)
        .not().isEmpty()
        .withMessage((value, { req, location, path }) => req.__("ValFieldIsRequired", req.__("isHappy")))
        .isBoolean()
        .withMessage((value, { req, location, path }) => req.__("ValFieldIsBoolean", req.__("isHappy"))),
```

The sanitized output is still 1234. When going through the documentation for validator it states under strict mode only 1 and true will return true all other values are false.

After a hour or so of debugging the express validator code I think I found the line responsible for what I am seeing 
https://github.com/express-validator/express-validator/blob/2cb4bcd7770329450b8e0880811d8390ebde41bd/utils/select-fields.js#L71

It looks like it by passes the santizer if the value passed in is not a string. I am wondering should this follow the same way the check function is done, by casting the value to a string?

**Comment by gustavohenke** [comment]
Hello! A fix should has been published in [`v6.0.0`](https://github.com/express-validator/express-validator/releases/tag/v6.0.0) 🚢, please try it out!
