### ISSUE TITLE
Add toUpperCase/toLowerCase sanitizers to validation chain

### ISSUE THREAD

**Issue by dxmaxwell** [express-validator/express-validator#581]
I am attempting to simplify my existing validation logic by using this library. However, I soon realized that my code uses trim() and toUpperCase() in many places, but express-validator does not have a sanitizer that corresponds to toUpperCase(). 

For now I have used a custom sanitizer, but this seems like something that would be generally useful.

**Comment by liqiang372** [comment]
What's the status of this issue? It's been open for over 2 years. Wonder if these methods should be added to express-validator or validatorjs itself as it is so generic

**Comment by chinesedfan** [comment]
Closed by #899.

**Comment by gustavohenke** [comment]
Out in [`v6.7.0`](https://github.com/express-validator/express-validator/releases/tag/v6.7.0)!
