### ISSUE TITLE
Chain order in schema

### ISSUE THREAD

**Issue by amberlionk** [express-validator/express-validator#582]
Is there a way to execute sanitizers and validators in the same order as they listed in schema?
Here I have schema:
```
const schema={ 
 RegDate:{
    trim:true,
    escape:true,
    isEmpty:{
      errorMessage: 'date field is empty',
      negated: true,
    },
    matches:{
      errorMessage: 'date field has to be  in format dd.mm.yyyy',
      options: /^\d\d\.\d\d\.\d\d\d\d$/i,
    },
    customSanitizer: {
      options: (value) => {
        let val=value.split(".");
          return val[2]+'-'+val[1]+'-'+val[0]+'T00:00:00.000Z';
      }
    },
}
```
and i want first to check users input, and then, if all is OK, convert value to format to store in database.
Now as I understand all sanitizers executed first, and then all validators does.
How to make them work in order?

**Comment by gustavohenke** [comment]
Hello @amberlionk,
You are correct when you say that sanitizers execute first.
Now, because schemas generate a single chain per field, there's no way around this _yet_, except using multiple `checkSchema()` calls.

Anyway, I'm open to hear suggestions.

**Comment by amberlionk** [comment]
Thank you for you reply. Multiple checkSchema is a good option, did not thought about it.
Any way i think i should use express-validator for what it suppose to - validate and escape user's input, not for describing database schema. Sorry for opening issue, i think it should be closed.
Also workaround way to achieve what i want,  in one schema:
```
  RegDate:{
    trim:true,
    escape:true,
    customSanitizer: {
      options: (value) => {
        let regex1 = RegExp(/^\d\d\.\d\d\.\d\d\d\d$/i);
        if(!regex1.test(value)) return '';
        try{
          console.log(value);//print to console
          let val=value.split(".");
          return new Date(val[2]+"-"+val[1]+"-"+val[0]+"T00:00:00.000Z");
        }catch(e){return '';}
      }
    },
    isEmpty:{
      errorMessage: 'date field has to be  in format dd.mm.yyyy',
      negated: true,
    },
  },
```

and one more thing, not sure if its important, but I have placed console.log in customSanitizer, and i see in console double lines of value, but made one request. so it looks like while field was validated, customSanitizer was called 2 times.

**Comment by gustavohenke** [comment]
Can you please check if your issue isn't the same as #554, and that you have an up-to-date version of express-validator installed?

If you still find it happening, please open a new issue with more reproduction steps.

**Comment by imShara** [comment]
How to make this?

1. Sanitze `value !== "" ? value : null`
2. Check if `value.length > isLength.options.min && value.length < isLength.options.max`
