### ISSUE TITLE
Discuss: sanitization of & symbol

### ISSUE THREAD

**Issue by amberlionk** [express-validator/express-validator#585]
Perhaps symbol of ampersand & should be excluded from escaping in to ``&amp;`` in escape sanitizer?

here is user case:
we have field Description on the form.
user enters text ``I'd like to...``
press submit, 
for example validation of some other field on form did not pass, form refreshed, and fields was populated with submitted values. 
Description was sanitized while that submit, and now holds ``I&#x27;d like to...`` - which is cool.
now user corrects his mistake and make second submit
Description is escaped again and we have ``I&amp;#x27;d like to...`` - which is not cool.
and field contend will continue mutate whit each additional submit.

Is it so important to escape &?

**Comment by amberlionk** [comment]
Could anyone tell me how to use ``whitelist`` sanitizer in schema?
i'm truing to do this
```
  DocType:{
    whitelist:{
      options:'&',
    },
    isEmpty:{
      errorMessage: 'error!!!!',
      negated: true,
    },
    trim:true,
    escape:true,
  },
```

but it dont whitelist it.

**Comment by fedeci** [comment]
@amberlionk have you solved 😄? I think so after almost a couple of years.

**Comment by amberlionk** [comment]
Hi, no I didn't solve it. Abandoned build in sanitizing and implemented it as middleware on router level.
