### ISSUE TITLE
Expose `check()` and `validationResult()` to all routes

### ISSUE THREAD

**Issue by fsultani** [express-validator/express-validator#586]
I'd like to expose `check()` and `validationResult()` to all routes form within my main `server.js` file.

`server.js`:
```
const express = require('express');
const { check, validationResult } = require('express-validator/check')

app.use(check()) // This will allow me to use check('name') in a specified route
app.use(validationResult())
app.use('/', index);
```

`index.js`:
```
const router = express.Router()

// This works
// const { check, validationResult } = require('express-validator/check')

router.post('/register', [ check('name').not().isEmpty() ], function(req, res) {
  const getErrors = validationResult(req)
  console.log(getErrors.array())
})
```
Currently, I have to include `check()` and `validationResult()` in my `index` file for this to work, but I'd like to avoid having to import these methods in every file that requires them.  Pretty sure I'm using `app.use()` incorrectly, so I'm looking for insight.  Thanks!

**Comment by marcospgp** [comment]
Indeed, this library is a little weird when it comes to handling validation in different files.

We should be able to easily define a validator and `require` it from multiple files, so we don't have to repeat validation code. I'm doing that right now by doing this:

```
// Inside helpers.js
exports.validateSiteName = util.promisify(
  body('name')
    .not()
    .isEmpty()
    .withMessage('The name can\'t be empty.')
    .isLength({ max: 256 })
    .withMessage('The name is too long.')
);
```

But unfortunately this means `helpers.js` also has to expose `validationResult` and all that. It would probably work to `require` the library again on every file that `require`s `helpers.js`, I suppose.

**Comment by gustavohenke** [comment]
Hello folks!
I'm sorry for the delay in getting back to you here.

Your issues here are all a tad unclear to me.
If you guys still use express-validator and face the same issues with it, please let me know what they are.

In the meantime, I hope something like [this, from v6](https://express-validator.github.io/docs/running-imperatively.html) can help.
