### ISSUE TITLE
normalizeEmail() is not documented

### ISSUE THREAD

**Issue by danielkhan** [express-validator/express-validator#590]
normalizeEmail() is used in examples but it's not part of the API documentation.

**Comment by gustavohenke** [comment]
Just like all other validator APIs we inherit.
But we do say this on the sanitization chain page:

> Any of the sanitization methods listed by validator.js are made available in all sanitization chains created by express-validator, as long as we're supporting the most up-to-date validator version.

Would making this stand out ease your comprehension of the API surface?

**Comment by danielkhan** [comment]
I think it would help to make that stand out. E.g. I still can not find this remark in the docs. I ended up using this package without knowing validator.js. I would crosslink wherever you refer functions inherited by the validator.js API.

**Comment by ToNyOyO** [comment]
I've scoured Google and I have no idea what isEmail() accepts as options and I don't know what normalizeEmail() even does, it's just mentioned in an example. 

There doesn't seem to be an easy to find reference for how this system works in these docs: https://express-validator.github.io/docs/ 

Am I missing something? Any help appreciated...

**Comment by gustavohenke** [comment]
@ToNyOyO please have a look at https://github.com/chriso/validator.js for all the standard validators and their options.

**Comment by pratik8787** [comment]
if we use normalizseEmailOptions , is it always mandatory to pass an email in it?
I remember it used to work earlier if no email was passed but not anymore.
here is my code

check('contact.email', 'email is required')
    .optional({ checkFalsy: true })
    .isEmail()
    .trim()
    .normalizeEmail({ gmail_remove_dots: false })


earlier, it would pass this check as it was optional, but now it stops here.
