### ISSUE TITLE
Where do we send donations?

### ISSUE THREAD

**Issue by mckenzieja** [express-validator/express-validator#591]
Love this project, and I want to send a donation to encourage it being maintained. How can we send   donation?

**Comment by gustavohenke** [comment]
Hello @mckenzieja. Thanks for this issue -- this is so awesome to read! One of the best ever created here.

I have created a simple [OpenCollective](https://opencollective.com/express-validator). This is the first time I'm on the maintainer side of donations, so please let me know if something doesn't work properly there!

**Comment by gustavohenke** [comment]
Hey @mckenzieja, thanks again for your desire to donate to this project!
Unfortunately I'm shutting this OpenCollective down, as this is a breach of my 🇦🇺 visa conditions.

**Comment by mckenzieja** [comment]
Understood! If there's anyway we can support that wont cause you to breach your visa conditions, let us know!

**Comment by gustavohenke** [comment]
...if anyone's reading this in 2023, situation has since changed 😄 

OpenCollective is up again: https://opencollective.com/express-validator
