### ISSUE TITLE
isInt work for both string and number type

### ISSUE THREAD

**Issue by WangHansen** [express-validator/express-validator#596]
isInt function works for both string and number type, is this the expected behavior? I am asking this because validator.js only works for string. However, when I pass in an int, it also works. 
Both these gives the same result:
![image](https://user-images.githubusercontent.com/15679461/41744634-3cf08742-7559-11e8-8b20-cacea7c264e8.png)
![image](https://user-images.githubusercontent.com/15679461/41744650-4d817490-7559-11e8-84df-943954b0d45e.png)
If this is true, does this apply to other function as well. For example, does `isBoolean` works for boolean type

**Comment by gustavohenke** [comment]
Hello @WangHansen!
Yes, every standard validator (those inherited from validator.js) get string inputs. You can see how we do such stringification here: https://github.com/express-validator/express-validator/blob/master/utils/to-string.js

In the other hand, custom validators will always receive the value as is; if you submit a number, that's what you will be validating.

**Comment by WangHansen** [comment]
I see, thanks for letting me know. But why? I mean, in this case, I will need to write custom verification method for specific datatype like boolean, date or number. Could you please elaborate more on why is the decision made this way? Much appreciated.

**Comment by WangHansen** [comment]
More specifically, how do I know if this check methods turn the data into string type? For instance, if i use `isMongoId()` on a field, this field needs to be passed as an mongo id object instead of string, otherwise, it would fail the test

**Comment by gustavohenke** [comment]
First of all, there's some long history of backward compatibility at express-validator; it has been like that for most of its ~7 years of existence (I have only contributed to it the last 1.5 years).
Plus, validator.js (back to v4 I think) itself used to validate all data types, not only strings.

In addition, you give the users more freedom: if they input JSON, they can send data in whatever format, as long as they match your validator rules.

Finally, you can always use sanitizers to have the data in the right format.

**Comment by WangHansen** [comment]
Thanks so much for you explanation and all the work. Sorry if the questions sound stupid, I am still new to the area

**Comment by gustavohenke** [comment]
No worries. Hopefully you will have an easy time using express-validator 🙂
