### ISSUE TITLE
whole body validation adding empty string property on req.body

### ISSUE THREAD

**Issue by xlc** [express-validator/express-validator#598]
with validator, `body().isString()` the persist-values function incorrect set empty string path on the `req.body` and causing circular reference error later when I want to convert it to JSON string.

The fix should be not setting the value when `instance.path` is empty string
https://github.com/express-validator/express-validator/blob/eaae68a9d39a0698f5cd1e0be5c0f3f1f8b8c0ae/utils/persist-values.js#L8

**Comment by gustavohenke** [comment]
Shipped on [v5.3.0](https://github.com/express-validator/express-validator/releases/tag/v5.3.0)! 🚢
