### ISSUE TITLE
matchedData removes optional nullable/checkFalsy body attributes

### ISSUE THREAD

**Issue by JoseExposito** [express-validator/express-validator#605]
My validation:

check.body('attribute').isString().optional({nullable: true})

I'll like to be able to send a null attribute and set it in my model as null.
However, the attribute is removed by matchedData rather than leaving it as null.

**Comment by wakiem** [comment]
Try this:
`matchedData(req, {includeOptionals: true})`

See: [https://github.com/express-validator/express-validator/issues/568](https://github.com/express-validator/express-validator/issues/568)

**Comment by JoseExposito** [comment]
Thanks for the feedback, looking forward for the next release 😀
