### ISSUE TITLE
How to use withDefaults

### ISSUE THREAD

**Issue by jackkitley** [express-validator/express-validator#606]
Hello

I would like to set a default response structure for my errors globally and im having trouble getting withDefaults to work.

Im currently using the following which works.

`            const errorFormatter = ({ location, msg, param, value, nestedErrors }) => {
                return {"title":param,"detail":msg};
              };
              const results = result.formatWith(errorFormatter);`

I want to use with defaults to output the same structure. An example would be great to define in the server.js file.

Thanks

**Comment by gustavohenke** [comment]
Can you be clear about _what_ is not working?

`validatorResult.withDefaults()` has some docs [here](https://express-validator.github.io/docs/validation-result-api.html#withdefaultsoptions).

**Comment by ansidev** [comment]
This issue should be closed

**Comment by gustavohenke** [comment]
Sure thing!
