### ISSUE TITLE
"optional" with parameters "checkFalsy", "nullable" seems not work again.

### ISSUE THREAD

**Issue by GitStorageOne** [express-validator/express-validator#608]
Hello!

In data below, fields `external_id` and `external_system_id` may be `null` or not present or contain proper value. So, i use `checkFalsy: true` and `nullable: true` but that not work and validation returns error:

```
{
:   "errors":
:   [
:   :   {
:   :   :   "location":"body",
:   :   :   "param":"external_id",
:   :   :   "value":null,
:   :   :   "msg":"Invalid value"
:   :   },
:   :   {
:   :   :   "location":"body",
:   :   :   "param":"external_system_id",
:   :   :   "value":null,
:   :   :   "msg":"Invalid value"
:   :   }
:   ]
}
```

**Data:**
```
{  
   "id":"23efb1b1-c195-472c-b43e-f2c4ed26fa6e",
   "external_id":null,
   "external_system_id":null,
   "name":"test"
}
```

```
{  
   "id":"23efb1b1-c195-472c-b43e-f2c4ed26fa6e",
   "name":"test"
}
```

**Rule** (typescript):

```
export const checkSchema: ValidationSchema = {
    id: {
        in: ['body'],
        isUUID: true
    },
    external_id: {
        optional: {
            checkFalsy: true,
            nullable: true
        },
        in: ['body'],
        isString: true
    },
    external_system_id: {
        optional: {
            checkFalsy: true,
        },
        in: ['body'],
        isUUID: true
    },
    name: {
        in: ['body'],
        isString: true,
        isLength: {
            options: {
                min: 1,
                max: 100
            },
            errorMessage: 'Accepted length 1-100'
        }
    }
};
```

**Comment by gustavohenke** [comment]
Hi @GitStorageOne, thanks for reporting this.
Looks like a bug in TypeScript. Correct usage should be this:

```js
external_id: {
  optional: {
    options: { checkFalsy: true }
  }
}
```


...but the typings force you to use it like you did.

**Comment by jeromecauchon** [comment]
Have the same issue with the typing. Someone have figured out how to fix it?

**Comment by matiasnl23** [comment]
The problem is in line 25 of file `express-validator/check/schema.d.ts` and is:
`optional?: boolean | ValidatorOptions.OptionalOptions;`
but should be:
`optional?: boolean | ValidatorSchemaOptions<ValidatorOptions.OptionalOptions>;`

**Comment by jeromecauchon** [comment]
Thanks matiasnl23, i did the same fix on my side last week and it works for my needs. I don't known if it cover all possible situations.

**Comment by stanislasdrg** [comment]
Yep thanks @matiasnl23, works on my side too. Did you submit a PR ?

**Comment by GitStorageOne** [comment]
https://github.com/express-validator/express-validator/pull/693
