### ISSUE TITLE
A sanitizer should run at its place in the chain?

### ISSUE THREAD

**Issue by slimee** [express-validator/express-validator#616]
hi, using 5.3.0, thanks you for making a love library

I saw #571 related and closed by f1f57d5 but I face the problem today.
Maybe it's not isMongoId do not break the chain, but the sanitizer that do not run at its place in the chain.

Does this chain sounds goods for you? _id must be a present objectID string, and **after** is sanitized as an objectID.
```
check("_id").exists().withMessage("missing")
    .isMongoId().withMessage("invalid")
    .customSanitizer(id => new mongo.ObjectID(id));
```

**_OK test with posting_** `{name:"bryan"}` 
=>exists break the chain.
`"errors": {
            "_id": {
                "location": "body",
                "param": "_id",
                "msg": "missing"
            }
        }`

**_OK test with posting_** `{_id:"5b574e725013c9f90a24af99",name:"bryan"}`
=> The request continues with _id as an objectID.

_**KO test with posting**_ `{_id:"BAD_ID",name:"bryan"}`
=>It causes an exception about the ObjectID constructor claiming the format is KO.
**The sanitizer should not run** since the isMongoId validator is KO?

**Another test:** if I remove the customSanitizer and send `{_id:"BAD_ID",name:"bryan"}` again, the isMongoId validation error occurs as expected.

Don't know where is the bug can you help?

**Comment by gustavohenke** [comment]
As stated on the docs, the sanitizers run first.
There are some ways around that; you could split it from the validators chain, but wrapping `ObjectId` with with `try..catch`, so that it doesn't throw. At least you can get your field sanitized and validated somehow.

I've been thinking about changing this behaviour, so that it does exactly what you suggested: run validators/sanitizers in their order of appearance in the mixed chains.
Obviously this will imply a new major version (v6.0.0).

**Comment by slimee** [comment]
Currently instead of try catch I add a regex validation inside sanitizer,
but not very satisfied with my code.

Thanks you for this nice lib.
I will be nice if runs are done in order, I think many people will
appreciate the coherence.

Le ven. 27 juil. 2018 à 18:06, Gustavo Henke <notifications@github.com> a
écrit :

**Comment by gustavohenke** [comment]
Hello @slimee!
I'm sorry that I took so long to ship another major version, but [`v6.0.0`](https://github.com/express-validator/express-validator/releases/tag/v6.0.0) is out and it has taken your idea in consideration 🔥, sanitizers can now run _after_ validators if they are after them in the chain!
