### ISSUE TITLE
Middleware for catching validation errors

### ISSUE THREAD

**Issue by spech66** [express-validator/express-validator#617]
We define a lot of different rules across multiple files and wanted to have a single middleware to handle all express-validator errors. So we came up with putting this in the express app like:

```
    this.app.use((req, res, next) => {
        const errors = validationResult(req);
        if (!errors.isEmpty()) {
          return res.status(400).json({ errors: errors.array() });
        }
        next();
    });
```

As the validations are provided on the routes they seem to be undefined at hat point in the chain. Is there a clean way to have the response handling for errors in a centralized way?

**Comment by edwinnnss** [comment]
I also tried to have a single middleware, but not work  
And then I create something like:
```
const MiddlewareValidation = require('../middlewares/Validation')

const combineValidationMiddleware = validation => [validation, MiddlewareValidation]

app.post('/users', combineValidationMiddleware(UserController.validateStore), UserController.store)
```

**Comment by gustavohenke** [comment]
Yeah, that's a problem with the way express middlewares definition works.
Best thing, currently, is to export the validation error catching middleware from some module and import it everywhere you define routes.

I know this is not great, so any ideas are more than welcome.
I would like to avoid implementing a default middleware for that within express-validator, as that would either require too much customisation, or be too constraining.

**Comment by spech66** [comment]
Thank you. We implemented this as suggested. Works stable for quite some time.
