### ISSUE TITLE
customSanitizer

### ISSUE THREAD

**Issue by slimee** [express-validator/express-validator#618]
Hi,

customSanitizer is not called with array GET params, if there is multiple values.

My chain with just a validation and a sanitization:
![image](https://user-images.githubusercontent.com/3200482/43206447-0f0d2280-9026-11e8-9ee9-f303b53b8cfc.png)

Sanitization is ignored when params are an array. Responses are allways 200.

![image](https://user-images.githubusercontent.com/3200482/43206537-41d5c2da-9026-11e8-9724-8f061709a61a.png)
![image](https://user-images.githubusercontent.com/3200482/43206573-580c0578-9026-11e8-987b-a20793336464.png)

**Comment by Otto-AA** [comment]
Same happend to me. The `isArray` validation and the `custom` validation both works, but the `customSanitizer` won't get called for an array.

Did you find a fix for this by now, @slimee ?

**Comment by slimee** [comment]
Hi

I wrote a middleware instead :(
It does the validation and the sanitization.

The sanitization update the req.param directly

Middleware contains param("_ids").exists()() like that matchedData returns the _ids (ignored oherwise)

The middleware throws the same exceptions than my normal validation circuit does.

Hope this help, sorry I am in vacation today and I am on my phone.

**Comment by Otto-AA** [comment]
Regarding to this PR, sanitzers only work with strings: https://github.com/express-validator/express-validator/pull/622

**Comment by fedeci** [comment]
Fixed by #711
