### ISSUE TITLE
invalid value in custom validator

### ISSUE THREAD

**Issue by HamidTanhaei** [express-validator/express-validator#619]
hi everyone
in this code i'm trying to show errors in response when the form is not valid.
in one step it's trying to check if the password is equal to confirmation password using custom validations.

```
router.post('/register', [
    check('name', 'the name field is required').isLength({ min: 1 }),
    check('email', 'the email field is required').isLength({ min: 1 }),
    check('email', 'the email must be a valid email address').isEmail(),
    check('password', 'the password field is required').isLength({ min: 5 }),
    check('password_confirmation', 'the password confirmation field is required').isLength({ min: 1 }),
    body('password_confirmation').custom((value, { req }) => {
        if(value != req.body.password){
            throw new Error('Password confirmation does not match password');
        }
    }),
], function(req, res){
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        return res.status(422).json({ errors: errors.array() });
    }
})
```

when the user enters different passwords, he will get an error:
Password confirmation does not match password

everything till now is ok.

but when user enter's the same password into password_confirmation,he'll get "msg":"Invalid value"
i couldn't find anything in docs to prevent show error in none error situations;

**Comment by gustavohenke** [comment]
Hi @HamidTanhaei, looks like you aren't using the latest express-validator. Update to v5.3.0 now to get rid of it!

This was a known issue with the way some custom validators are implemented.
See #593 for context.

**Comment by HamidTanhaei** [comment]
my current version is v5.3.0.
the problem solved by adding an `else` with `return true` after checking password conditions.
```
if(value != req.body.password){
            throw new Error('Password confirmation does not match password');
}else{
            return true;
}
```

**Comment by TheShadowfax** [comment]
Hi Everyone,
I was trying tryout this validation check, inspite of providing source as dApp
im getting the error saying **invalid value** for source.
here's my validation code 
`body("source")
          .exists()
          .withMessage("Source field is mandatory")
          .isIn(["dApp", "stanAPI"])
          .withMessage("Value for source type is unknown")
          .custom((value, { req }) => {
            if (value == "dApp") {
              console.log(value);
              body("deviceID")
                .exists()
                .withMessage("Device id is required to login")
                .not()
                .isEmpty()
                .withMessage("Device id cannot be empty"),
                body("loginType")
                  .exists()
                  .withMessage("Login type is mandatory")
                  .isIn(["qr", "pwd"])
                  .withMessage("Login type is of unknown type")
                  .custom((value, { req }) => {
                    console.log(value);
                    if (value === "qr") {
                      body("qrCode")
                        .exists()
                        .withMessage("Qr-Code is required to login")
                        .not()
                        .isEmpty()
                        .withMessage("Qr-Code is cannot be empty");
                    } else {
                      body("ambID")
                        .exists()
                        .withMessage("AmbID is mandatory")
                        .not()
                        .isEmpty()
                        .withMessage("AmbID is cannot be empty"),
                        body("pwd")
                          .exists()
                          .withMessage("pwd is mandatory")
                          .not()
                          .isEmpty()
                          .withMessage("pwd is cannot be empty");
                    }
                  });
            } else return true;
          })`

and here is my request

`curl -X POST \
  http://localhost:5000/subscription \
  -H 'cache-control: no-cache' \
  -d 'source=dApp'`
