### ISSUE TITLE
access express.Response in CustomValidator

### ISSUE THREAD

**Issue by timothyallan** [express-validator/express-validator#621]
Hi! I've checked the docs/workarounds, and I think I already know the answer, but here goes: I've got a middleware setup which does authentication, and populates `res.locals` with a user object after authentication. The next middleware in the chain is express-validator. 

I'm not able to access my user object in `res.locals` in a custom validator to validate user specific checks, as the custom validator only exposes the `req` object. Is there any current way to get access to the `res` object in a custom validator? 

I could always do something like store it in Redis, or somewhere else, but it's a 3rd party auth library and the less hacks the better.

**Comment by gustavohenke** [comment]
Hello,
Currently, that's not possible. express-validator hasn't made any use of the response object to day, as we're dealing with what comes _before_ the request is responded.

I don't agree with pushing data from the request to the response object, and would like to avoid making that change to express-validator.

Is that auth library open source? Do you mind saying its name?

**Comment by timothyallan** [comment]
Yep, that's what I figured. The auth library is the express oAuth package, it's open source: https://www.npmjs.com/package/express-oauth-server 

So the middleware flow ideally is `request -> oauth check(populates user obj) -> express-validator (checks certain values according to the logged in user) -> response`. 

I can always store the user in Redis/HTTP context or something, I just thought it'd be easier if I could validate what I need to using express-validator :)

**Comment by gustavohenke** [comment]
Thanks for pointing me to the library.
You could just add your own middleware between express-validator and express-oauth-server:

```js
app.use(oauth.authorize());
app.use((req, res, next) => {
  req.locals.oauth = res.locals.oauth;
});
// routes, validations, etc
```

This might work for others in the same situation, too.

Navigating the response object down where the custom validators are invoked would be quite some work. In terms of API change, it would be non-breaking, so it's fine to have it.

However, I'm happy to see PRs for this; I'm quite low on time for this kind of maintenance at the moment.

**Comment by timothyallan** [comment]
The 'ol switcharoo! That would work as well, good idea.
I'm also strapped for time, so no PR from me in the near future. There's plenty of workarounds here though, so I think we can close this up for now.
