### ISSUE TITLE
How can build dynamic validation messages based on multiple language ?

### ISSUE THREAD

**Issue by RebazRaouf** [express-validator/express-validator#623]
Hello
I want to build custom validation message but i don't find any good example, how can separate language file and load based on selected language automatically ?

thanks

**Comment by nguyentien1995** [comment]
You can pass a parameter call "language" which determine which language is using in every request.
Then write a function that deal with language selection and call it in function withMessage().
I bet that you already know how to make a validator

```
req
    .check('name')
    .notEmpty()
    .withMessage(selectMessageBaseOnLanguage(req, message))
    
```    
```
var enFile = require("path-to-file");
.....
selectMessageBaseOnLanguage = (req, message) => {
// base on you send language parameter through params, query or body....
    if (req.body.language == "en") return enFile.message1;
    if (req.body.language == "fr") return frFile.message1;
}
```
your language file look like this
```
var file = {};
file.message1 = "m1";
file.message2 = "m2";
...
module.export = file;
```

**Comment by RebazRaouf** [comment]
Thanks for your reply..
I solved by using i18n library using custom validator. I have one more question
do i need to sanitize all fields after checking for example like this =>

`export function checkIt() {
    return [
        body('id').isInt().withMessage((value, { req, location, path }) => {
        return req.t('id_check', { value, location, path })
        }), body('offset_check').isInt().withMessage((value, { req, location, path }) => {
            return req.t('offset', { value, location, path })
        }), body('stringData').not().isEmpty().withMessage((value, { req, location, path }) => {
            return req.t('empty_check', { value, location, path })
        }),
        ,sanitize('id').toInt()
        ,sanitize('offset').toInt(),
        sanitize('stringData').trim().escape()
    ]
}`

**Comment by nguyentien1995** [comment]
sanitize is optional, not requirement. If you want to ensure all the parameters have the type you want then sure, do it. If you can accept it as any type then you don't need it at all.

**Comment by gustavohenke** [comment]
Nice way of solving your issue, @RebazRaouf! That's the right thing 👍
