### ISSUE TITLE
intended behavior? 

### ISSUE THREAD

**Issue by chirastefan** [express-validator/express-validator#624]
I have this code: 
userRouter.js:
`router.route('/edit').post(editValidation, controller.editUser);
router.route('/add').post(addValidation, controller.addUser);`

with the base URL `/user`: 
app.js
`app.use('/user', userRouter);`

When I do a `validationResult(req)` inside controller.editUser function `const errors = validationResult(req);` I also get the errors from `addValidation`, I would expect to get only the errors from `editValidation`. Is this the intended behavior or a bug?

**Comment by gustavohenke** [comment]
Definitely not intended behaviour, but could depend on your usage.
Are you reusing the chains like below? Because they are not immutable, so you end up with a single object with all validations on it:

```js
const baseValidation = check('username').isEmail();
// Email must not exist, unless it's the user's current one
const editValidation = baseValidation.custom(emailNotExistsAndNotUsers);
// Email must not exist at all
const addValidation = baseValidation.custom(emailNotExists);
```
