### ISSUE TITLE
Express-validator blocks event loop on big objects

### ISSUE THREAD

**Issue by ArturPrzybysz** [express-validator/express-validator#625]
As in the title: app freezes for 2 minutes when express-validator validates relatively big object (2.7MB array of objects) .
Is there any way to make this middleware work asynchronously?

**Comment by gustavohenke** [comment]
Not at the moment. What are you doing?

Just so that related stuff stay linked: #569

**Comment by ArturPrzybysz** [comment]
@gustavohenke What do you mean? What am I going to do with the issue, or do you want me to give more information on my application?

**Comment by gustavohenke** [comment]
- What kind of validation are you applying?
- What is the shape of your data?

There must be some work-around optimisations I can suggest until proper fixes are applied.

Also, by "app freezes for 2 minutes", I imagine you mean the whole server process?

**Comment by gustavohenke** [comment]
I think the next step here is to identify where the bottleneck is.
I expect it to be either in the [`selectFields` function](https://github.com/express-validator/express-validator/blob/v5.3.0/utils/select-fields.js#L12-L17), or in the [validators calls](https://github.com/express-validator/express-validator/blob/v5.3.0/check/runner.js#L6-L17).

Changing the former is more difficult as there are a bunch of dependencies on it, expecting it to be a sync function; the latter could use some batching (say, process 100 fields then push the next batch onto the end of the async queue).

**Comment by ArturPrzybysz** [comment]
Thanks, I have ended up with my own, simplistic Stream-based express-validator :)

**Comment by gustavohenke** [comment]
Hello @ArturPrzybysz!
Nearly one year later. This might have been fixed -- check the commit 435f104 for explanation!

**Comment by ArturPrzybysz** [comment]
Nice!
