### ISSUE TITLE
Custom sanitizer does not run on non-string type value

### ISSUE THREAD

**Issue by tranvansang** [express-validator/express-validator#630]
It looks like [this line](https://github.com/express-validator/express-validator/blob/master/utils/select-fields.js#L73) produces the bug

`body('page').customSanitizer(page => page - 1)`

with `req = {body: {page: 1}}` ends up with `req.body.page` retains being 1 after sanitized

**Comment by gustavohenke** [comment]
Hello! A fix should has been published in [`v6.0.0`](https://github.com/express-validator/express-validator/releases/tag/v6.0.0) 🚢, please try it out!
