### ISSUE TITLE
isMongoId() not working

### ISSUE THREAD

**Issue by sszczep** [express-validator/express-validator#637]
Hi,
I have a problem while using isMongoId validator. Part of my code:
```js
const { body: bodyValidation, param: paramValidation } = require('express-validator/check');
router.get('/:id',
paramValidation('id')
.isMongoId()
 .withMessage('You need to specify valid post id'),
async(req, res, next) => {...});
```

No matter what I provide, it passes validation (eg. posts/invalidID). Do you have the same problem? All other validators work just fine. Express-validator version: 5.3.0.
Thanks in advance

**Comment by gustavohenke** [comment]
This isn't enough to prove a problem in express-validator.
Please add more sample code -- even better if you can create a test repository on GitHub.

**Comment by sszczep** [comment]
Well... I created test project and everything seems to work. Came out to be missing middleware for handling errors in that route, my mistake. Sorry guys

**Comment by gustavohenke** [comment]
No worries. I'm glad you let me know where your pain point was!
