### ISSUE TITLE
normalizeEmail() strips periods - option to opt out?

### ISSUE THREAD

**Issue by jimimaher** [express-validator/express-validator#644]
The below will remove periods from email addresses passed in.

`body('email')
    .isEmail()
    .normalizeEmail()`

`normalizeEmail` will take the input email of i.am.a.user@domain.com and output iamauser@domain.com. I believe services like Gmail do not count periods as a character in an email address, so maybe it's industry standard to strip out periods.

Is there currently a path to opt out of stripping periods?

**Comment by gustavohenke** [comment]
Looking at https://github.com/chriso/validator.js#sanitizers, this seems to be only a thing for `@gmail.com` and `@googlemail.com`.

express-validator doesn't own the implementations for `normalizeEmail` (just like most other standard sanitizers and validators), so you would need to check the behaviour with validator.js folks 🙂.
Sorry for the trouble!
