### ISSUE TITLE
Allow specific letter lire é or è

### ISSUE THREAD

**Issue by Cedric-Lefebvre** [express-validator/express-validator#646]
Hi,

I'd like to know the best way to check if a field isAlpha() but i know that the é is not recognize by default as a letter even if it is in specific language.

Is it better to create a custom filter or is there a way to add some character outside of the isAlpha()?

**Comment by gustavohenke** [comment]
`isAlpha` comes from [validator.js](https://github.com/chriso/validator.js#validators), so if specifying a locale doesn't solve your issue, it's better to create a custom validator.

But, I tried the validator module on Node REPL just to be sure that it works:

```
> v.isAlpha('áéíóúçã')
false
> v.isAlpha('áéíóúçã', 'pt-BR')
true
>
```

Have you tried specifying a locale with express-validator, too?

**Comment by Cedric-Lefebvre** [comment]
Ok it's working thank you!

i just had to select the isAlpha(['fr-FR']) and it's ok now :)
