### ISSUE TITLE
Change param names for error display?

### ISSUE THREAD

**Issue by timothyallan** [express-validator/express-validator#652]
I've got an array of multiple objects from various textboxes submitting via body:
```
[{
  name:'abc',
  value:123
},
  name:'def',
  value:456
}, ...
]
```
I'm checking them via `body('*.name').custom(async (prefName, { req, location, path }) => {...`

When an error occurs, I do a `throw new Error('Validation Error')` as I'm doing async DB checks.

The param that's returned to my client is `param:[0].name`, `param:[1].name` etc. What I need is the returned param name to be the "name" that's defined in the object so the appropriate field is highlighted on the client. i.e. `param:abc`

Can I modify the param somehow before I throw the error, so that my error formatter picks up the 'correct' name? I use a site wide error formatter, so I'd rather not pollute it by putting a bunch of specific `if`'s in it for this one page.

**Comment by gustavohenke** [comment]
There is no built-in way for this.
I'm also not sure if introducing this would be a good decision, as it really sounds like the error formatter is the best pick for it.

That's one way I would do it:

```js
const createErrorFormatter = (req) => {
    if (req.path === '/some/path') {
        return somePathFormatter;
    } else {
        return defaultFormatter;
    }
};

app.post('/*', (req, res) => {
    const result = validationResult(req).formatWith(createErrorFormatter(req));
});
```

Does it look bad to you by any chance?

**Comment by timothyallan** [comment]
Thanks for the fast response. If it can't be done natively, then I agree: a secondary custom error formatter is probably the way to go 👍 

Great work on this project!
