### ISSUE TITLE
Legacy custom validator not working with Typescript

### ISSUE THREAD

**Issue by NiccoloCase** [express-validator/express-validator#653]
Hi all, I'm getting typescript compiler errors and at runtime from node.js. What I would like to do is define new functions for validation. This is my code:

In the main file of my express app, I initialize the express-validator middleware. In the documentation, I did not find anything about it, but a long time ago, before moving to typescript I remember finding that the correct procedure was this. Then I initialize express-validator by passing an object with the options, which is in the validation.ts file:

`app.use(expressValidator(require("./validation")));`

This is the validation.ts file, where I export the express-validator configuration options and define all the custom functions.

```
 import User from "../models/User"

 export = {
      customValidators: {

        isUsernameAvailable(username: string) {
          return new Promise((resolve, reject) => {
            User.findOne({ username: username }, (err, user) => {
              if (err) throw err;
              if (user == null) {
                resolve();
              } else {
                reject();
              }
            });
          });
        }
      }
    };
```

After creating the custom functions, if I run the following code the compiler does not recognize the new function

```
import express, { Request, Response } from "express";
import User from "../../models/User";
import {
  checkSchema,
  check,
  body as checkBody,
  validationResult
} from "express-validator/check";

const router = express.Router();

router.post(
  "/validationTest",
  [
    checkBody("name").isUsernameAvailable() // not working
  ],
  (req: Request, res: Response) => {
    const err = validationResult(req).mapped();
    if (err) return res.json(err);
    res.json({ success: true });
  }
);
```

In the main file of my express app, I initialize the express-validator middleware

app.use(expressValidator(require("./validation")));
This is instead the express-validator configuration in the validation.ts file:

  import User from "../models/User"

        export = {
      customValidators: {

        isUsernameAvailable(username: string) {
          return new Promise((resolve, reject) => {
            User.findOne({ username: username }, (err, user) => {
              if (err) throw err;
              if (user == null) {
                resolve();
              } else {
                reject();
              }
            });
          });
        }
      }
    };
But when I try to use the function just created, typescript gives me an error

```
import express, { Request, Response } from "express";
import User, { UserModel } from "../../models/User";
import {
  checkSchema,
  check,
  body as checkBody,
  validationResult
} from "express-validator/check";
// router
const router = express.Router();

router.post(
  "/val",
  [
    checkBody("name")
      .isUsernameAvailable()
  ],
  (req: Request, res: Response) => {
    const err = validationResult(req).mapped();
    if (err) return res.json(err);
    res.json({ success: true });
  }
);
```
The compiler says: **Property 'isUsernameAvailable' does not exist on type 'ValidationChain'.**

**Comment by gustavohenke** [comment]
Just defining the custom validator on your `expressValidator()` options is not enough; you have to augment the `ValidationChain` interface like demonstrated on #378.
