### ISSUE TITLE
Runtime optional

### ISSUE THREAD

**Issue by vincentkwok** [express-validator/express-validator#657]
`.optional()` is quite useful. However, it does not support dynamic case.

#### Use case

form validation for saving draft (partial filled and save) and save all (fully filled and save) 

The same set of validations apply for both actions, except `.optional`.

The current solution is 
```js
function getCheckChain(field, isDraft = false) {
  return isDraft ? check(field).optional() : check(field);
}

getCheckChain('username', isDraft)
  .isString()
  // do many checking else
```

It would be good if there is something like `.optional(false)`, especially there is bulk of check fields

**Comment by gustavohenke** [comment]
Duplicate of #439

**Comment by gustavohenke** [comment]
> Duplicate of #439

Scratch that, not really. Conditional validations are a thing now, but they won't help in this case.
Supporting `.optional(false)` though should be fairly easy.

**Comment by gustavohenke** [comment]
I think this has been possible for a while.
If not, please open a new issue. Thanks!
