### ISSUE TITLE
Add the option to not echo back the value in error array

### ISSUE THREAD

**Issue by tiphedor** [express-validator/express-validator#659]
Say i validate this kind of input: 

````javascript
// { "field": "<script>alert()</script>" }
check('field').isEmail()
````

I'll get this error, as expected:
````javascript
{
  "errors": [{
    "location": "body",
    "msg": "Invalid value",
    "param": "field",
    "value": "<script>alert()</script>"
  }]
}
````

Is there an option to not echo-back the value the user passed, ie in my case:
````javascript
{
  "errors": [{
    "location": "body",
    "msg": "Invalid value",
    "param": "field"
  }]
}
````

I made the example dramatic to prove my point, but in general i think we can agree it's wise to treat user input as very very very dangerous, especially in the context of validating it.

❤️

**Comment by ojurkiewicz** [comment]
Was this issue resolved in any way or I should manually clean value?

**Comment by tiphedor** [comment]
AFAIK no solution yet

**Comment by ojurkiewicz** [comment]
So I'll just leave my simple solution. 
`function clearValue(errorArray) {
  return errorArray.map(error => {delete error.value; return error})
}`
usage:
`clearValue(errors.array())`

**Comment by gustavohenke** [comment]
Hello!
The preferred way would be to use an [error formatter](https://express-validator.github.io/docs/5.3.0/validation-result-api.html#formatwithformatter), a built-in feature of express-validator:

```js
validationResult(req).formatWith(error => ({
  param: error.param,
  location: error.location,
  msg: error.msg,
}))
```

While a call like `errors.map()` (as suggested by @ojurkiewicz) works when you have an array of errors, it won't be available when you prefer using `validationResult(req).mapped()` 😉 

Also, a few other things to keep in mind:
- Don't just print the input value on your HTML.
- [Sanitise your input](https://github.com/chriso/validator.js#sanitizers) (e.g. `check('email').escape().isEmail()`.

Thanks 😊

**Comment by tiphedor** [comment]
Didn’t know about error formatters, seems like it could work, thanks !
