### ISSUE TITLE
break validation chain

### ISSUE THREAD

**Issue by SiyahaS** [express-validator/express-validator#660]
Hello, I saw #235 but in order to make it more streamline maybe a `breakOnError(message?: string)` or another chain function to break chain if last stage already resulted in an error might help.

Use case would be:

`check('id').exists().withMessage('id cannot be null').isMongoId().breakOnError('id must be a valid ObjectId').custom(checkDB).withMessage('id not found').custom(checkLimit).withMessage('limit reached');`

Above case would be 
* check if 'id' exists in payload and is a mongoId, if not stop execution
* check if 'id' is exists in DB(custom) and check if limit has been reached(custom)

So it would be an alternative `withMessage` function that breaks the validation chain if an error occurred.

**Comment by gustavohenke** [comment]
That's what #500 is adding 🙂

**Comment by Igor-Lopes** [comment]
Hi, any updates on this issue ?

**Comment by gustavohenke** [comment]
Hey, sorry, not yet @Igor-Lopes.
