### ISSUE TITLE
isEmpty with PUT is failing

### ISSUE THREAD

**Issue by maamounapprise** [express-validator/express-validator#662]
I am using checkSchema across GET POST PUT, it doesn't check the field as expected with PUT and the isEmpty fails to check if field is empty 

Steps to reproduce: 
Use checkschema or any of the check api with a PUT similar to the following :
```
 const validation = checkSchema({
  username: {
    in: ['body'],
    exists: true,
    isEmpty: {
      negated: true
    },
    isString: true,
    escape: true,
    trim: true,
    errorMessage: 'ERROR'
  }})
app.put('/profile', validation, UserProfile)
```

**Comment by gustavohenke** [comment]
`PUT` is no different to a `POST`.

What does the rest of your express app setup look like?
Can you isolate the problem in a repo that I can clone and check it myself?

**Comment by gustavohenke** [comment]
@maamounapprise feel free to comment on this issue if you ever come back to it.
