### ISSUE TITLE
How to use custom validator for nested validate

### ISSUE THREAD

**Issue by alihesari** [express-validator/express-validator#663]
Hi, in this code the value of `hasLogin` is `true` or `false` and always it is a boolean value, but I get `Invalid value` error for it. what is wrong in my code? Can I use express-validator like this?
```
return [
     check("hasLogin", "Invalid data").isBoolean(),
     check("isInteraction", "Invalid data").isBoolean(),
     check("hasLogin").custom((hasLogin) => {
        if (hasLogin) {
            check("link").isURL().withMessage("Invalid website url");
            check("loginPage").isURL().withMessage("Invalid login page url");
            check("username", "Username must be string").isAlpha();
            check("password", "Password must be string").isAlpha();
            check("dataPage", "Invalid data page url").isURL();
        } else {
            check("pageUrl", "Invalid website url").isURL();
        }
      })
    ];
```

**Comment by Rouzz** [comment]
Hi,

I'm not entirely sure, but I think you're simply missing a `return` statement in your custom validator.
By default, if you don't return anything you will get an error from the custom validator. Since you didn't specify a string you get the default `Invalid value`

Simply add a `return true` where needed and it should work.

Regards,
Rouzz

**Comment by alihesari** [comment]
Hi, @Rouzz 
I did your suggested solution and it does not solved the problem. when I return `true` after the if/else. The custom validation is will be valid in any case.

**Comment by Rouzz** [comment]
Okay so you want the custom validation to be valid if all sub-validations are valid and false otherwise ?

If that's the case, I don't know if there is a proper way to do it. Basically you need to access the `validationResult` and make the return depend on it.

The issue is that as far as I can tell, `validationResult` requires `req` as a parameter. You could try using a custom function as a middleware :
`return [
     check("hasLogin", "Invalid data").isBoolean(),
     check("isInteraction", "Invalid data").isBoolean(),
     function(req, res, next) {
        // Guessing you get hasLogin from body, please align with your way to get hasLogin in the app
        if (req.body.hasLogin) {
            check("link").isURL().withMessage("Invalid website url");
            check("loginPage").isURL().withMessage("Invalid login page url");
            check("username", "Username must be string").isAlpha();
            check("password", "Password must be string").isAlpha();
            check("dataPage", "Invalid data page url").isURL();
        } else {
            check("pageUrl", "Invalid website url").isURL();
        }
        const errors = validationResult(req);
        return errors.isEmpty();
      })
    ];`

This would need to be tested. And based on what you want to do, you may want to count the current number of errors before your if/else condition and return true if the count went up after you added the new checks.

Hope this helps.

**Comment by alihesari** [comment]
@Rouzz 
I changed your code to this

> Okay so you want the custom validation to be valid if all sub-validations are valid and false otherwise ?
> 
> If that's the case, I don't know if there is a proper way to do it. Basically you need to access the `validationResult` and make the return depend on it.
> 
> The issue is that as far as I can tell, `validationResult` requires `req` as a parameter. You could try using a custom function as a middleware :
> 
> ```
> return [
>      check("hasLogin", "Invalid data").isBoolean(),
>      check("isInteraction", "Invalid data").isBoolean(),
>      function(req, res, next) {
>         // Guessing you get hasLogin from body, please align with your way to get hasLogin in the app
>         if (req.body.hasLogin) {
>             check("link").isURL().withMessage("Invalid website url");
>             check("loginPage").isURL().withMessage("Invalid login page url");
>             check("username", "Username must be string").isAlpha();
>             check("password", "Password must be string").isAlpha();
>             check("dataPage", "Invalid data page url").isURL();
>         } else {
>             check("pageUrl", "Invalid website url").isURL();
>         }
>         const errors = validationResult(req);
>         return errors.isEmpty();
>       })
>     ];
> ```
> This would need to be tested. And based on what you want to do, you may want to count the current number of errors before your if/else condition and return true if the count went up after you added the new checks.
> 
> Hope this helps.

I made little changes in the above code and finally, the below code worked correctly.
```
return [
      check("hasLogin", "Invalid data").isBoolean(),
      check("isInteraction", "Invalid data").isBoolean(),
      function(req: any, res: any, next: any) {
         if (req.body.hasLogin) {
          req.checkBody("link").isURL().withMessage("Invalid website url");
          req.checkBody("loginPage").isURL().withMessage("Invalid login page url");
          req.checkBody("username", "Username must be string").isAlpha();
          req.checkBody("password", "Password must be string").isAlpha();
          req.checkBody("dataPage", "Invalid data page url").isURL();
         } else {
          req.checkBody("pageUrl", "Invalid website url").isURL();
         }

         const errors = validationHandler(res, req, next);
         if (errors !== true) {
          res.status(403).json(errors);
          return false;
         }

         next();
       }
     ];
```

**validationHandler:**
```
const validationHandler = (res: any, req: any, next: any) => {
 const errors = req.validationErrors();
 if (errors) {
  return {
   error: errors.map((item: any) => {
    return { [item.param]: item.msg };
   })
  };
 }
```

Thank you for your reply. You save me!  🎉
