### ISSUE TITLE
checkSchema field option--withMessage fails silently

### ISSUE THREAD

**Issue by recyclingben** [express-validator/express-validator#664]
Had a bit of trouble coming up with a good title, so I'll just explain.
this:
```javascript
checkSchema({
    exists: {
        in: "query",
        isInt: true,
        couchPotato: "hello!"
    }
})
```
results in the warning message `express-validator: a validator with name couchPotato does not exist` as intented. However, this:
```javascript
checkSchema({
    exists: {
        in: "query",
        isInt: true,
        withMessage: "hello!"
    }
})
```
produces no warning message, which could lead a lot of newcomers confused, not understand an `errorMessage` property should be used instead.

The issue can be trached to these lines in `schema.js`:
```javascript
if (typeof chain[method] !== 'function') {
    console.warn(`express-validator: a validator with name ${method} does not exist`);
    return;
}
```
As you can see, it is checking whether or not a method `withMessage` is available on the chain. This may technically be predictable behavior, as you can get withMessage working by doing this:
```javascript
checkSchema({
    exists: {
        in: "query",
        isInt: true,
        withMessage: {
            options: "hello!"
        }
    }
})
```
but this can still lead to potential issues later if more non-validator methods are worked in.

I would be happy to submit a fix for this.

**Comment by gustavohenke** [comment]
Hello @recyclingben!
Thanks for tracking this one down 😃 I'm happy to have you fix it, if you have the time!
