### ISSUE TITLE
Make ErrorFormatter parameter type an interface

### ISSUE THREAD

**Issue by G-Rath** [express-validator/express-validator#669]
Currently the typescript definition for `ErrorFormatter` looks like this:

```
export type ErrorFormatter<T = any> = (error: {
  location: Location,
  param: string,
  msg: any,
  value: any
}) => T;
```

When attempting to write some tests for my formatter, typescript complains:

```
it('should return a well-formatted error object', function () {
    const rawError: {
        msg: string;
        param: string;
        location: Location;
        value: string
    } = {
        location: 'body',
        param: 'firstName',
        value: '',
        msg: 'must only contain letters'
    };

    const formattedError = errorFormatter(rawError); // Error - Types of property 'location' are incompatible. Type 'string' is not assignable to type 'location'.

    expect(formattedError.param).to.be.equal(rawError.param);
    expect(formattedError.message).to.be.equal(rawError.msg);
});
```

This is b/c I've not explicitly denoted the type of the variable, but since the type isn't exposed as an interface in `express-validator`, I have to do this:

```
const rawError: {
    msg: string;
    param: string;
    location: Location;
    value: string
} = {
    location: 'body',
    param: 'firstName',
    value: '',
    msg: 'must only contain letters'
};
```

It would be great if instead the type was an interface, letting me to do this:

```
const rawError: UnformattedError = {
    location: 'body',
    param: 'firstName',
    value: '',
    msg: 'must only contain letters'
};
```

**Comment by gustavohenke** [comment]
Hello @G-Rath!
This should now be possible with [`v6.0.0`](https://github.com/express-validator/express-validator/releases/tag/v6.0.0), as it has been fully rewritten in TypeScript.

You can import the types `ErrorFormatter<T>` and `ValidationError`, which should work for what you are asking.

Sorry for the delay!!
