### ISSUE TITLE
Documentation using Docusaurus

### ISSUE THREAD

**Issue by arijitthehacker** [express-validator/express-validator#670]
I would like to feature the express-validator documentation using [Docusaurus](https://docusaurus.io/en/).
Reference: [Link](https://github.com/facebook/Docusaurus/issues/1080)

I am pretty sure it would be a really interesting project to work upon. It would be great if I could get your permission for the same.

**Comment by gustavohenke** [comment]
Wow, thanks for letting me know about this initiative!
So nice to hear about this.

I'd be super happy to have it featured on Docusaurus!
Seems like you'll need a logo -- you can take it from here: https://github.com/express-validator/express-validator/blob/v5.3.0/website/static/img/logo.svg

**Comment by yangshun** [comment]
@arijitthehacker seems like we have the green light. Would you like to submit a PR to Docusaurus?

**Comment by gustavohenke** [comment]
Closing. But thanks so much, peeps ❤️
