### ISSUE TITLE
Message of thrown error only used when custom validator is returning a promise

### ISSUE THREAD

**Issue by G-Rath** [express-validator/express-validator#671]
I'd expect that the following two validator chains would result in the message `'Password confirmation does not match password'`:

```
body('passwordConfirmation')
    .custom((value, { req }) => {
        const { password } = req.body as API.Authorization.ResetPassword.Request;

        if (password !== value) {
            throw new Error('Password confirmation does not match password');
        }
    }),
body('passwordConfirmation')
    .custom(async (value, { req }) => {
        const { password } = req.body as API.Authorization.ResetPassword.Request;

        if (password !== value) {
            throw new Error('Password confirmation does not match password');
        }
    }),
```

However, only the second one results in that error message. The first does fail, but has the message `Invalid value`.

It seems only `Promise.reject` errors are having their messages used, which is contrary to the [documentation](https://express-validator.github.io/docs/custom-error-messages.html#custom-validator-level):

> If you're using a custom validator, then it may very well throw or reject promises to indicate an invalid value.
> In these cases, the error gets reported with a message that's equal to what was thrown by the validator

**Comment by gustavohenke** [comment]
Hm, that's a bit of a surprise for me. [This test](https://github.com/express-validator/express-validator/blob/v5.3.0/check/runner.spec.js#L124-L139) should ensure this behaviour.

Which express-validator version are you using?

**Comment by G-Rath** [comment]
Here's my dependencies:

```
"dotenv": "^6.2.0",
"express": "^4.16.4",
"express-bearer-token": "^2.2.0",
"express-delay": "^0.2.0",
"express-validator": "^5.3.0",
"http-errors": "^1.7.1",
"http-status-codes": "^1.3.0",
"lokijs": "^1.5.5",
"morgan": "^1.9.1",
"ts-node": "^7.0.1",
"ts-transformer-keys": "^0.3.3",
"tsconfig-paths": "^3.7.0",
"ttypescript": "^1.5.5",
"typescript": "^3.2.1"
``` 

I'm not sure how your test runner is working, but could `express` messing things up?

Here is a sample of one of my endpoints:
```
/**
 * Creates a new `User`.
 */
users.post('/', [
    body('email')
        .exists().withMessage('This field is required')
        .isEmail().withMessage('Must be a valid email')
        .custom(async email => {
            if ((await Db.users.find({ email })).length !== 0) {
                throw new Error('A user already exists with that email');
            }
        }),
    body('firstName')
        .exists().withMessage('This field is required')
        .isAlpha().withMessage('Can only contain letters'),
    body('lastName')
        .exists().withMessage('This field is required')
        .isAlpha().withMessage('Can only contain letters'),
    body('password', 'Must be at least 5 characters long, and made up of numbers, letters, & symbols')
        .exists().withMessage('This field is required')
        .isLength({ min: 5 }),
    body('passwordConfirmation')
        .exists().withMessage('This field is required')
        .custom((v, { req }) => req.body.password === v).withMessage('Password confirmation does not match password'),
    body('terms')
        .equals('true').withMessage('Terms must be accepted')
        .toBoolean()
], validatorRequestHandler, async (req: Request, res: Response) => {
    const {} = req.params as API.Users.CreateUser.Parameters;

    const {
        email,
        firstName,
        lastName,
        password
    } = req.body as API.Users.CreateUser.Request;

    const salt = generateStringToken();

    const user: Db.User = {
        id: `${Db.users.maxId}`,
        email,
        firstName,
        lastName,
        salt,
        password: hashPassword(password, salt),
        pages: [],
        notebooks: [],
        createdAt: (new Date()).toISOString(),
        updatedAt: null,
        deletedAt: null
    };

    const addedUser = await Db.users.insertOne(user);

    if (addedUser === undefined) {
        throw new Error('a database error occurred while trying to insert user');
    } // shouldn't ever happen..? but test just to be safe

    const body: API.Users.CreateUser.Response = {
        data: pickApiUser(addedUser)
    };

    return res.status(HttpStatus.OK).json(body);
});
```

**Comment by G-Rath** [comment]
Any update on this issue?

I had a quick look into the code for `runner`, and wonder if this could be arising as a result of `validatorCfg.message` coming before `err && err.message`:

https://github.com/express-validator/express-validator/blob/298177a7c85b90110fa480422ee3dde472fb3c14/check/runner.js#L23-L29

**Comment by gustavohenke** [comment]
The snippet above is correct. `validatorCfg.message` translates to `withMessage()`, which takes precedence.

What is the request body with which you are not seeing the messages being used?

**Comment by G-Rath** [comment]
> validatorCfg.message translates to withMessage(), which takes precedence.

That's what you get for glancing over code, and making shots in the dark 😊 

I'm feeling sheepish right now however, as I can't for the life of me reproduce this, but I swear it was happening 😕 

I've not touched any of the packages, but no matter what I try I can't get it happening.

I'm going to close this issue for now, and re-open it if it pops up again. Thanks for your time!

**Comment by gustavohenke** [comment]
No worries, sorry for my delay!
