### ISSUE TITLE
"isArray: true" does not prevent executing custom validator 

### ISSUE THREAD

**Issue by ignasposka** [express-validator/express-validator#672]
express-validator version: 5.3.0
I suppose that first unsatisfied criteria should prevent from checking other criteria.
In my case I am specifying that parameter should be an array, even it is not array, my custom criteria function is still being called. By that I have to add additional check in my custom function which makes using "isArray: true" option pointless.
```javascript
access: {
        in: ['body'],
        isArray: true,
        optional: true,
        custom: { // this validator should not be called if above criteria is not meet
            options: (input) => Array.isArray(input) && input.every((obj) => typeof obj === 'object'
                && obj.collaborator
                && obj.rights
                && ['admin', 'write', 'read'].includes(obj.rights))
        }
    }
```

Please let me know if that is expected behavior. Maybe I am wrong.

**Comment by gustavohenke** [comment]
[`.bail()`](https://express-validator.github.io/docs/6.14.0/validation-chain-api.html#bail) (introduced in v6.2.0) helps with this.
