### ISSUE TITLE
`toInt` in combination with custom validator fails for zero (0)

### ISSUE THREAD

**Issue by cwansart** [express-validator/express-validator#677]
I am using Express version 4.16.4 and express-validator version 5.3.1.

When I try to validate a schema with an input query, using the `toInt` sanitizer together with a custom validator it will fail for the value zero.

I created an example app: https://github.com/cwansart/express-validator-toInt-error-example

When I use `?limit=-1` or `?limit=11` I get my custom error message. When I use `?limit=1`, `?limit=2`, .., `?limit=10` I get "All good" returned. So far so good. But with `?limit=0` I get an `Invalid value` error message.

Am I doing something wrong or may this be a bug?

--------------------------

**Edit**
It seems that changing the type in the custom validator causes this error. I added two examples:
 * https://github.com/cwansart/express-validator-toInt-error-example/tree/error-on-custom-validator1
 * https://github.com/cwansart/express-validator-toInt-error-example/tree/error-on-custom-validator2

The first and second one are the same, except for the return value in the custom validator. In the first one I return the string, in the second one the number. Interestingly this only fails for the number 0. 

**Edit2**
It fails on this check: https://github.com/express-validator/express-validator/blob/master/check/runner.js#L14
When `result` is 0 and type of number, the check fails. Not quite sure what this line is supposed to do, but this is a null/undefined check, right? If so, this could be extended and it will work with returning number zero:

    if ((!validatorCfg.negated && result === undefined) || (validatorCfg.negated && result !== undefined)) {

**Comment by airstofather** [comment]
I'm facing an issue when the value of the parameter is 0 too.

In my case, I have an enum (0,1,2) and the validator has this defined:

```
"status": {in: ["body"], exists: {errorMessage: "missing"}, isInt: true,
      optional: {
        options: {checkFalsy: true}
      },
      custom : {
        options: (value) => {
          if ([0,1,2].includes(value)) {
            return true;
          } else {
            throw new Error("invalid");
          }
        }
      }
    },
```

Then in when I try to filter the data:
```
const paramFilter = require("express-validator/filter");
const params = paramFilter.matchedData(req, {location: ["body"]});
```
and if the parameter is set to zero, it is excluded. Other numbers go through.

**Comment by gustavohenke** [comment]
Hello folks!
I'm sorry for this looong time without replying.

@cwansart when you use synchronous custom validators, you have to return a truthy value in order for the validation to pass. **`custom` is only validating your input, it doesn't sanitize it**, so when you `return 0`, you are telling express-validator that the validation failed.

@airstofather can you please open a separate issue? Thanks!
