### ISSUE TITLE
 isJWT not a function

### ISSUE THREAD

**Issue by DISKONEKTeD** [express-validator/express-validator#678]
I'm getting a: isJWT not a function

Is it not available?

**Comment by gustavohenke** [comment]
It seems to have been included in [validator.js@`v10.9.0`](https://github.com/chriso/validator.js/blob/master/CHANGELOG.md#1090) only.

Can you please try reinstalling/updating your dependencies?
express-validator depends on [validator.js@`^10.4.0`](https://github.com/express-validator/express-validator/blob/v5.3.1/package.json#L33), what means you should get `v10.10.0` when reinstalling express-validator.

Keep in mind that if you have a `package-lock.json`/`yarn.lock`, npm/yarn will install the locked version if you don't explicitly tell them to update the dependencies.

**Comment by DISKONEKTeD** [comment]
I had a look in the package.json, and you are correct, I don't have 10.7.0 of validator installed. I failed to realize that. thank you, closing the thread then. appreciated.
