### ISSUE TITLE
toArray() sanitizer

### ISSUE THREAD

**Issue by soulchild** [express-validator/express-validator#679]
Given that there are sanitizers like `toBoolean()`, `toDate()`, etc. would it make sense to add a `toArray()` sanitizer as well? 

This would come in handy especially when dealing with multiple request parameters of the same name (for instance when using checkboxes) which are often transformed into an array, but will be left as a string if only one parameter was transmitted. (I guess this is a feature of express [body-parser](https://github.com/expressjs/body-parser) and similar middlewares…)

What do you guys think?

**Comment by gustavohenke** [comment]
That's a great idea -- tagged it as an enhancement!

**Comment by soulchild** [comment]
Cool! I could take a stab at it and submit a PR, if you like.

All current sanitizers seem to just delegate the hard work to the [validator](https://github.com/chriso/validator.js) library. Would it be okay to make an exception here and implement the `toArray()` functionality within [sanitizers-impl.ts](https://github.com/express-validator/express-validator/blob/master/src/chain/sanitizers-impl.ts) itself because `validator` does not offer it?

**Comment by gustavohenke** [comment]
Yup, that would be it!

express-validator gained some "custom standard validators" on demand as well: https://github.com/express-validator/express-validator/blob/56153943ea10a0bc505f5f63c0367341ce1462be/src/chain/validators-impl.ts#L27-L33

Maybe you could follow suit?
