### ISSUE TITLE
Question: How to use default value with checkSchema

### ISSUE THREAD

**Issue by christiansakai** [express-validator/express-validator#682]
Sorry I have tried googling, search through Github issue and StackOverflow, it seems there is no answer yet to this question. Sorry if there is

How do I use default value with checkSchema? Say

```
checkSchema({
  limit: { // I want to give a default value of 5 here if the `limit` does not exist
    options: {
       min: 1,
       max: 10,
    }
})
```

**Comment by gustavohenke** [comment]
It's not possible, although you can make it optional.

See https://express-validator.github.io/docs/validation-chain-api.html#optionaloptions and https://express-validator.github.io/docs/schema-validation.html for reference.
