### ISSUE TITLE
How to throw error if email contains specific domain?

### ISSUE THREAD

**Issue by hugeprestigellc** [express-validator/express-validator#686]
I'm struggling to figure out something that I think is probably really trivial to do. 

Pretty much I just want to check and throw an error if a submitted email address contains a certain domain.

req.check('email', 'Email is not valid').contains('spamdomain.com'); //This will throw an error if the email does not contain spamdomain.com. I want the opposite of this, throw an error if it contains spamdomain.com

I feel like I'm missing some super easy way to do this.

Thanks!

**Comment by sm00nie** [comment]
I think you could use a custom validator and test for the domain, something like:
```
req.check('email', 'Email is not valid').custom(value => {
    if(/spamdomain.com/.test(value)) {
        new Error('Domain Not Allowed')
    }
    return true
}),
```

**Comment by gustavohenke** [comment]
@hugeprestigellc You could just use `.not()` before a validator to negate it. [Docs](https://express-validator.github.io/docs/validation-chain-api.html#not)
