### ISSUE TITLE
customSanitizers not works

### ISSUE THREAD

**Issue by di-djon** [express-validator/express-validator#688]
I want to use multiple custom sanitizers
Here is my issue example:

```
const expressValidator = require('express-validator'),
    express = require('express');

const app = express();

app.use(expressValidator({
    customSanitizers:{
        toUpperCase: value => value.toUpperCase()
    }
}));

const { checkSchema, query } = require('express-validator/check')

app.get('/test1',
    checkSchema({ param:{ toUpperCase : true, trim: true}}),
    (req,res,next) =>{
        console.log(`'${req.query.param}'`); 
        res.end();
    }
);

/*app.get('/test2',[
        query('param').toUpperCase()
    ], async (req,res,next) =>{
        await req.check({ param:{ toUpperCase : true, trim: true}});
        
        console.log(`'${req.query.param}'`);
        res.end();
    }
);*/

app.listen(10000);
```
after start I see warning in console output "express-validator: a validator with name toUpperCase does not exist"

for GET http://127.0.0.1:10000/test1?param=%20test 
output is 'test' , trimed but not in uppercase
expected 'TEST' trimed and uppercase

if I uncomment test2, I receive "TypeError: query(...).toUpperCase is not a function"

node: v8.11.3
npm: v6.4.1
express-validator: v5.3.1

Also [Middleware options docs](https://express-validator.github.io/docs/legacy-api.html#middleware-options) about customSanitizers is not clear how to register named custom sanitizer.

Question: is this a bug or should I use validator in differently?

**Comment by benliu723** [comment]
@di-djon I guess this is a bug, if not, the design for global `customValidator` and `customSanitizer` are useless.

if you want to make it work, you may need to wrap your code insider a `express middleware` and call `req.checkSchema`, instead of calling `checkSchema` directly.

```
app.get('/test1',
    (req, res, next) => {
          req.checkSchema({ param:{ toUpperCase : true, trim: true}})
     },
    (req,res,next) =>{
        console.log(`'${req.query.param}'`); 
        res.end();
    }
);
```

Running 
```
app.use(expressValidator({
    customSanitizers:{
        toUpperCase: value => value.toUpperCase()
    }
}));
```
only binding `customSanitizers`  and `customValidators` with `sanidation chain` or `validation chain` with `req`.

**Comment by di-djon** [comment]
@benliu723 Thanks for good approach
 
one small change to your code:
`req.checkSchema` is not a function, you can use `req.check` or `req.checkBody` or `req.checkQuery` etc.. instead of `req.checkSchema`

**Comment by benliu723** [comment]
oooh, yes, you are right!

**Comment by gustavohenke** [comment]
Sorry for the confusion.

Legacy API (`req.check`, `expressValidator({ ... })`, etc) runs in isolation to the rest of the new APIs that were introduced as of `v4.0.0`.

It will be removed with v6, so no more confusion like this.
