### ISSUE TITLE
req.check doesn't support dynamic message

### ISSUE THREAD

**Issue by benliu723** [express-validator/express-validator#689]
Original `validation chain` support `dynamic validation`.
```
const {check} = require('expresss-validator/check');
router.post('*', [check('someField').custom(someValidator).withMessage(() => {return 'dynamic message'})]);
```

However, 
It is so wired that **`validation chain` called by `req`** doesn't support `dynamic message`.

```
router.post('*', (req, res, next) => {req.check('someField').custom(someValidator).withMessage(() => {return 'dynamice message'.})});
```

This annoys me so much. Hope someone fix it.

**Comment by gustavohenke** [comment]
Ah yeah, it doesn't and it won't -- the legacy API is deprecated. No new features to it are accepted since v5.0.0.

**Comment by gustavohenke** [comment]
Also: it should be removed in the next major version (with some long requested features added to the main API, of course)

**Comment by benliu723** [comment]
@gustavohenke 
Do you mean `customized sanitizer` won't be supported in the next major version?

For my experience, `customized validator` and `customized sanitizer` are really good features.

**Comment by gustavohenke** [comment]
Any features available now through `req` won't be available in the next major version.
They used to be the main API for using express-validator back in v3, but the check API evolved in parallel and it's not getting ported back.

The check API, however, is the one you should be using, if you started your project in the last 2 years. It has all the features and is well tested.
If you miss something or notice a bug in it, I'm happy to have a look.
