### ISSUE TITLE
How to get custom validator error as JSON ?

### ISSUE THREAD

**Issue by stanislasdrg** [express-validator/express-validator#692]
Hello,
first of all thank you for the awesome library.
I am using v5.3.1 with node 11 and express 4.16.4.
I am trying to validate a mongo Object id using [what I found in the docs](https://express-validator.github.io/docs/custom-validators-sanitizers.html#example-converting-to-mongodb-s-objectid).
The problem is that I always get returned an html template with my custom error message. 
My goal is to have that error formatted as JSON, in the same kind of way as what can be found in the docs : 
```
return res.status(422).json({
        message: 'Unprocessable entity - Check params',
        error: errors.array()
      });
```
My code is :
```
usersRouter.delete('/:id',
                  [
                    sanitizeParam('id').customSanitizer((value) => {
                      let sanitizedId: ObjectId;
                      try {
                        sanitizedId = new ObjectId(value);
                      } catch (invalidValueErr) {
                        console.log('Invalid id err');
                        throw new Error('Invalid id');
                      }
                      return sanitizedId;
                    })
                  ],
                  deleteUser());
```
Of course, the error is not passed to my delete function and I cannot handle the error there. I suspect that there is a  `next(err)` function to handle the error behind the curtains, which is why my `deleteUser()` function is bypassed.
But then, how to get that error returned as JSON and how can I format it the way above ?
Many thanks for your help.

**Comment by gustavohenke** [comment]
> The problem is that I always get returned an html template with my custom error message.

Hmm, curious. Maybe there is something else in your express app configuration that is making this not work.

Since this issue is a few months old, did you find the answer to it?

**Comment by stanislasdrg** [comment]
Thank you for your reply @gustavohenke  I have not investigated further the issue. But if its supposed to work I will give it a better look. Closing until then.

**Comment by gustavohenke** [comment]
No worries. Sorry for my delay. If you ever come back to this issue, feel free to reopen it/create a new one.
