### ISSUE TITLE
Inheritance property to validator

### ISSUE THREAD

**Issue by vikey913** [express-validator/express-validator#699]
I am trying to validate a CRUD operations schema

**create**
1. new: {
        query: {
            accountId: Joi.number().positive().required(),
            userId: Joi.number().positive().required(),
        },
        body: {
            name: Joi.string().required(),
            parentId: Joi.string().regex(UUID_REGEX_PATTERN)
        }
    },
2. newWithUUID: {
        query: {
            accountId: Joi.number().positive().required(),
            userId: Joi.number().positive().required(),
        },
       params: {
            uuid: Joi.string().regex(UUID_REGEX_PATTERN).required()
        },
        body: {
            name: Joi.string().required(),
            parentId: Joi.string().regex(UUID_REGEX_PATTERN)
        }
    }

**Read**
Same as the above 2 APIs without body

**Update**
Same as the above 2 APIs

**Delete**
Same as above 2 APIs without body.

Can we achieve this functionality in this framework ? Or is it a new feature ?

**Comment by gustavohenke** [comment]
Yup, something like this:

```js
app.post('/new/:uuid', checkSchema({
	accountId: {
		in: ['query'],
		isInt: {
			options: { min: 0 }
		}
	},
	uuid: {
		in: ['params']
	},
	name: {
		in: ['body']
	}
})
```

Please check the rest of the API on https://express-validator.github.io/docs/schema-validation.html
