### ISSUE TITLE
Docs need more examples and details

### ISSUE THREAD

**Issue by SergeyShablenko** [express-validator/express-validator#700]
How do I use schema validation on `req.query` or `req.body` separately?
If I understood correctly, then we don't need expressValidator middleware set up in 5x version.
Legacy api has `req.checkBody(schema)` and  `req.checkQuery(schema)`. Where can I find similar api in 5x version?
How to deal with async validation?

In documentation there are only simple examples which has no real value, what if I need to validate query, params, body with different schemas and async validators?

**Comment by gustavohenke** [comment]
Hi @SergeyShablenko.

> Legacy api has `req.checkBody(schema)` and `req.checkQuery(schema)`. Where can I find similar api in 5x version?

Maybe the example in https://express-validator.github.io/docs/schema-validation.html is not very thorough.

So you can specify at each field's level where you want it to be:
```js
app.post('/some-path', checkSchema({
  field1: {
    in: ['query'],
    isInt: true
  },
  field2: {
    in: ['body'],
    isEmail: true
  }
}), yourHandler);
```

> How to deal with async validation?

Async validation is done by writing custom ones.
E.g. https://express-validator.github.io/docs/custom-validators-sanitizers.html#example-checking-if-e-mail-is-in-use IMO shows a real world example. You can just transpose that to the schema API, which would be something like

```js
checkSchema({
  email: {
    custom: {
      options: value => {
        return User.findUserByEmail(value).then(user => {
          if (user) {
            return Promise.reject('E-mail already in use');
          }

          // e-mail not in use, all good
        });
      }
    }
  }
})
```

**Comment by gustavohenke** [comment]
Could you maybe suggest further examples that you would like added?

Also, improving the docs should be as simple as submitting a PR that touches the [`/docs`](https://github.com/express-validator/express-validator/tree/master/docs) directory, so feel free to submit one.

**Comment by gustavohenke** [comment]
Closing for now.
