### ISSUE TITLE
I have issue with email address format

### ISSUE THREAD

**Issue by hiep8024** [express-validator/express-validator#701]
My email in this format: **firstname.lastname@abc.cde1** 
I am using `isEmail()` function is return false and raise an error. 
I cannot check if I am wrong of email format or this is a real issue with express-validator.

**Comment by gustavohenke** [comment]
All standard validators (like `isEmail`) are sourced from the underlying dependency [validator.js](https://github.com/chriso/validator.js).
Please refer there for these kinds of issues.

**Comment by hiep8024** [comment]
Thank you for your response, Gustavohenke!
