### ISSUE TITLE
Validation chain inside custom validation

### ISSUE THREAD

**Issue by Obippin** [express-validator/express-validator#702]
Inside custom validation, I have lat-long as: 

`value = "40.712776, -74.005974"`

I want to use .isLatLong() inside custom validation 
`.custom(value => {
      .isLatLong(value)
}`

How do I use `.isLatLong()` inside custom validation ?

**Comment by mwergles** [comment]
This would also help me with https://github.com/express-validator/express-validator/issues/634.

**Comment by OmgImAlexis** [comment]
Since this is based on [validator.js](https://github.com/chriso/validator.js) you can just import the methods from there and use them as normal functions.

**Comment by OmgImAlexis** [comment]
@Obippin you can do what I showed in https://github.com/express-validator/express-validator/issues/634

This should be able to be closed now.
