### ISSUE TITLE
Wildcards do not work correctly for objects with dots in keys

### ISSUE THREAD

**Issue by PerfectPixel** [express-validator/express-validator#703]
On `express-validator@5.3.1`

With a body like
```
{
  "map": {
    "foo": "bar",
    "foo.bar": "my foo bar"
  }
}
```

wildcards on the objects properties fail because of the `.` in the key.

```
body('map.*').isString()
```

If I remove the `.` in the key `foo.bar` validation is passed. In the debugger the value for the key `foo.bar` is `undefined`.

**Comment by fedeci** [comment]
Working in v6, closing for now!
