### ISSUE TITLE
Unexpected behavior with optionals, sanitizers, and matchedData

### ISSUE THREAD

**Issue by sbutler** [express-validator/express-validator#707]
I think there's some bad behavior when working with optionals, sanitizers, and matchedData. Suppose I have this:

```javascript
const validateFoo = checkBody('foo').trim().customSanitizer(value => value === '' ? null : value).optional({ nullable: true }).isEmail();
# ... inside the handler after validation
const data = matchedData(req);
```

If we submit foo with something that trims to '' then I'd expect `data.foo` to be null (because of the custom sanitizer). But it's not, it's the original submitted value. It's almost as if the sanitizer result wasn't persisted back to the request.

And that's actually what happens. If you look in `select-fields.js` you can see that after it runs the sanitizers it will filter out values that fail the optionalityFilter. Since these values are filtered, they are never persisted. Later when `matchedData` is run it does not run the sanitizers (because it correctly thinks they should have been run), and the optionality filter also passed because the value is no longer null (because the sanitized value was not persisted in the req).

I think the only way for me to have sanitizers work with optionals is to run the sanitizer and validation phases independently and then have the optional only on the validation phase?

**Comment by gustavohenke** [comment]
Hello @sbutler! I'm sorry that I didn't reply here before.

So with v6.0.0, a few things changed, and one of them is that `matchedData` doesn't re-select the fields.
You should give it a try, and post here again if it doesn't help you.
