### ISSUE TITLE
Excluding Sensitive Fields 

### ISSUE THREAD

**Issue by lfernando-silva** [express-validator/express-validator#708]
Hey, I would like to know if is possible to protect some fields to be affected in the request if client sends it. For example, I have a request to update user data, but would like to deny the update if the client tries to update the user.id .

```
// validationMiddleware
// ...
{
     id: {
         in: ['body', 'params']
          deny: true,
          errorMessage: "The id cannot be changed"
     }
}


router.put('/users/:id', validationMiddleware, async (req, res) {/*...*/} )
```

**Comment by gustavohenke** [comment]
Hi @lfernando-silva!
Could you maybe try this?
```js
id: {
  exists: {
    negated: true
  }
}
```

**Comment by lfernando-silva** [comment]
Totally works. Thanks for the attention!
