### ISSUE TITLE
How to use the new api in a clean way

### ISSUE THREAD

**Issue by tjlian616** [express-validator/express-validator#709]
I have been using the legacy api so my current code looks like below. I'd like to migrate to the new format but I don't know how to do this in a nice way. It feels like I have to move the validation part out of each function and put them all into my router? 

It feels so weird and the result code is ugly and harder to maintain... I am sure there is another way to do this. Please help.

```
\\ a big router file
router.get('/writeBlog', blogController.writeBlog);

\\ many controller files(one for user, one for blog, one for tasks...etc)
exports.writeBlog=function(req, res){
  req.check('title')
  ... many checks
  req.check('date')
  if (checkError){res.status(403).send('oops')}
//continue with normal business logic
}
```
the official website example seems to propose a rewrite to this
```
router.get('/writeBlog', [
body('title).exists,
...many checks
body('data').exists
], blogController.writeBlog);
```
this make the router file very long and ugly looking. Also I have to looks at both files to understand the input and make any modifications.

**Comment by gustavohenke** [comment]
Hello @tjlian616!
You could make `blogController.writeBlog` an array that contains all those validation bits, what do you think?

```js
blogController.writeBlog = [
  body('title').exists(),
  (req, res) => {
    // save the blog entry
  },
];

router.get('/writeBlog', blogController.writeBlog);
```

**Comment by tjlian616** [comment]
Thanks! I didn't know this was possible.
