### ISSUE TITLE
No error if using external middleware

### ISSUE THREAD

**Issue by javanotti** [express-validator/express-validator#715]
Ok, so my problem here is that errors are not thrown when calling validation middleware functions that are using express-validator methods from an external module 

I'm using 

Here a bit of code insight:

**PACKAGE.JSON** 
```
..
"express-validator": "^5.3.1",
"express": "^4.17.0",
..
```

**1. Router code:**
```
..
const { testCheck } = require( `${ _middlewares }/validation.middlewares.js` );
``
testRouter.post(
        `/test` ,
        testCheck ,
        ( req , res ) => {
            
        return res.json( { message : `OK` } );
} );
```

**2. Middleware code:**
```
..
const { checkSchema , validationResult } = require( `express-validator/check` );
..

module.exports = {

    testCheck : ( req , res , next ) => {

        checkSchema({
            testField : {
                isInt : true ,
                errorMessage : 'XXXX'
            }
        } )

        const errors = validationResult( req );

        if ( !errors.isEmpty() ) {
            return res.json( { message : 'KO' } )
        }
        else { next(); }
    }
}
```

I have no errors when doing 
```
testRouter.post(
        `/test` ,
        check('testField').isInt()  ,
        ( req , res ) => {
            
        return res.json( { message : `OK` } );
} );
```

I'm sending 
`{ "test" : "23dq" } `
from Postman, and always getting 
`{ "message" : "OK" }`
for response

**Comment by gustavohenke** [comment]
Yeah, that's all expected.
For example, when you call `checkSchema`, you are just defining the schema -- you are not passing it to express. You have to pass it to the route handler, otherwise it is useless.

You can also take a look at [how to run your middlewares imperatively](https://express-validator.github.io/docs/running-imperatively.html) with v6+.
