### ISSUE TITLE
Schema Custom Validation Fails Checking If Is JWT Token

### ISSUE THREAD

**Issue by lfernando-silva** [express-validator/express-validator#717]
I have a schema validation like this one: 

```js
token: {
        in: ['body', 'header'],
        isJWT: true,
        optional: false,
        custom: { 
             options: async (value, { req }) => { 
                     const token = req.body.token || req.headers.authentication&& req.headers.authentication.split(' ')[1]; // Authentication: Bearer {token}
                     const isValidJWT = validator.isJWT(token) // returns true
                     return canUseThisToken(token) // It's a boolean method from app, works
             }
        },
       errorMessage: 'The token is invalid'
}
```

The problem is I noticed the `isJWT` from schema does not validates correctly the token when it comes from the body, but not when it comes from the header. And I receive the error message. But the token is valid, using the same validation lib.

Once I remove the `isJWT` from the schema validation, it works well.

**Comment by gustavohenke** [comment]
Hi @lfernando-silva,

> does not validates correctly the token when it comes from the body, but not when it comes from the header

please note that you have this in your code:

```js
const token = req.body.token || req.headers.authorization;
```

so from the headers, you're validating `authorization` -- not `token`.

**Comment by lfernando-silva** [comment]
Sure, actually was my mistake to simplify the code here. Just corrected, but even in case the token is in the body, the error still. The validatorJS says it is true, but the validation with isJWT does not perform correctly.

**Comment by gustavohenke** [comment]
Ah. So the token would need to be valid everywhere it is present.
This is a security measure -- see #331 for context.

So you seem to be doing some parsing to the token when it come from headers: `Bearer {token}`.

This is not valid JWT. One option is to omit it from either `req.body` or `req.headers`. Or, you could use a custom sanitiser to split the value before it's validated:

```js
token: {
	in: ['body', 'headers'],
	customSanitizer: {
		options: (value, { location }) => {
			return location === 'headers' ? value.split(' ')[1] : value;
		}
	},
	isJWT: true,
}
```

Hope it helps 😃

**Comment by lfernando-silva** [comment]
Sure, actually it could be avoided following this security tip. So seems it's refactoring time hehe. Thanks
