### ISSUE TITLE
How can i unit test the validators?

### ISSUE THREAD

**Issue by xtrememiners** [express-validator/express-validator#718]
Hi, I have an API with express validators, but i cannot figure out how can I unit test it.
I am using :
Validators -> _there is where i defined the schemas_
Controllers -> _simple CRUD layer over the moongoose which get a Model as parameter_
Routers -> _I call the validator and the controller in the route function. I pass the model in this file 
 to the controller_
Model -> _Simple mongoose model_
Test -> _Unit tests._

Here is an example from my router file:
```javascript
router.post('/register',
  checkSchema(userValidator.createUserValidationSchema),
  (req,res,next) =>{
    const result = validationResult(req);
    if (!result.isEmpty()) {
      return res.json({ errors: result.array() });
    }
  },

  (req, res) => {
    userController.createUser(req.body)
      .then(response => res.json(response))
      .catch(error => res.boom.badRequest(error));
  }
);
```

How can I test the validator without then router?

**Comment by xtrememiners** [comment]
Hi, i find the solution. 

validatorUtils.js
```javascript
validatorUtils.testExpressValidatorMiddleware = async (req, res, middlewares) => {
  await Promise.all(middlewares.map(async (middleware) => {
    await middleware(req, res, () => undefined);
  }));
};

module.exports = validatorUtils;
```

sometest.js
```javascript
    it('testsomething', async () => {
      await validatorUtils.testExpressValidatorMiddleware(req, res, checkSchema(userValidator.createUserValidationSchema));
      const errors = validationResult(req).array();

      expect(errors).to.be.an('array');
      expect(errors).to.not.be.empty;
    })
```

**Comment by gustavohenke** [comment]
express-validator is thoroughly tested, so you don't need to _unit test_ it. Just trust that it will work, and if it doesn't, then it might be a bug with it, not your codebase.

The validators will work if they are passed where they should.

As an API developer however, you are concerned that maybe not all validations documented by your API are in place.

In _my_ opinion what you **should** be doing instead is writing **integration tests**.

Use a tool like [supertest](https://www.npmjs.com/package/supertest), where you can pass an express app, a method/route, a query/body/headers/etc and test that the output is the one you expect.

for example:

```js
const express = require('express');
const { check } = require('express-validator');
const request = require('supertest');

const app = express();
app.post('/create-user', [
	check('email').isEmail(),
	check('password').isLength({ min: 5 })
], (req, res, next) => {
	// respond with 422 if there are errors
});

it('fails if invalid email or short password are passed', done => {
	request(app)
		.post('/create-user')
		.send({ email: 'not_an_email', password: '1234' })
		.expect(422, done);
});
```
