### ISSUE TITLE
Is there a build in check to validate that a number falls within a given range

### ISSUE THREAD

**Issue by kumar-muthu** [express-validator/express-validator#720]
I want to validate a field which contains percentage value. So I looking for a built in check which  will check if the input number is within a range (say between 0 to 100)

**Comment by gustavohenke** [comment]
Hello @kumar-muthu! Sorry for the delay in answering.

Yes, you would be looking at `isInt`. It takes a n object of options with `{ min: 0, max: 100 }`.

Also have a look at the [validator.js validators](https://github.com/chriso/validator.js#validators) for other validators and sanitizers.
