### ISSUE TITLE
how to set a reusable validation chain

### ISSUE THREAD

**Issue by fareshan** [express-validator/express-validator#725]
```
Keep this in mind and note that you probably want to use a factory function when reusing some base chain.
```
source: https://express-validator.github.io/docs/validation-chain-api.html

I did not understand this. Can you provide an example ?

**Comment by gustavohenke** [comment]
Sure! Here's a naive example to demonstrate what you highlighted:

```js
const userEmailChain = check('email').isEmail();

// new users can't use existing emails
app.post('/create-user', userEmailChain.custom(isEmailRepeated), routeHandler);
// existing users may not be changing their email, so the repeated email check is not necessary
app.post('/update-user', userEmailChain, routeHandler);
```

In the above example, one could expect that the route for _creating a user_ would validate that the email is an email, and that it is not repeated in the database.
And that the route for _updating a user_ only validates that the email is an email.

What actually happens is that both routes will validate that the email is not repeated. Every chain method mutates the original object.

What you probably want to do in this situation is this:

```js
const createUserEmailChain = () => check('email').isEmail();

app.post('/create-user', createUserEmailChain().custom(isEmailRepeated), routeHandler);
app.post('/update-user', createUserEmailChain(), routeHandler);
```

I hope it helps!
