### ISSUE TITLE
Calling imperatively from controller does not work

### ISSUE THREAD

**Issue by asolenzal** [express-validator/express-validator#728]
Hello:

I'm trying to use express-validator imperative call in a controller as described in here. https://express-validator.github.io/docs/running-imperatively.html . 

My code:

```
var myMethod = async function (req, res, next) {
  await body('email').isEmail().run(req);

  var errors = validationResult(req);
  console.log(errors);
}
```

The console will log an empty array if email is not present or email is invalid.

This code belongs to a controller, if I use the validation chain as a middleware it works as expected.

Thanks in advance.

**Comment by gustavohenke** [comment]
Hello @asolenzal, thanks for reporting! I'm looking at fixing it!

**Comment by llldar** [comment]
Experiencing the same problem here.

**Comment by gustavohenke** [comment]
👋 this has been published to [`v6.1.0`](https://github.com/express-validator/express-validator/releases/tag/v6.1.0) 🚢

**Comment by asolenzal** [comment]
Thanks @gustavohenke great response time. Will look at some issues to see on what can I help you.

**Comment by manekshms** [comment]
This issue is still not fixed
console.log shows empty array if email is empty
```
    if(req.body.email) {
        await body("email").isEmail().run(req);
     }
     const result = validationResult(req);
    console.log(result.errors)
   // empty array 
```
   Thanks

**Comment by gustavohenke** [comment]
Hi @manekshms, if email is empty you're not validating anything, as per your `if` condition 🙂

**Comment by manekshms** [comment]
Hai @gustavohenke 

If email is not empty and invalid something like "test" then validation is still empty array

i could do something like this
```
let validationError = null;
if(req.body.email) {
   validationError = await body("email").isEmail().run(req);
}
// validationError is not empty 

const result = validationResult(req);
// but result.errors is empty
```
In the documentation it says call validationResult function get those errors
https://express-validator.github.io/docs/running-imperatively.html#example-validating-with-a-condition

It would be great if i get those errors while calling validationResult method instead of get the error from the promise settle and return its result

Thanks

**Comment by gustavohenke** [comment]
> If email is not empty and invalid something like "test" then validation is still empty array

Then you have likely not updated to v6.1.0 yet, or there's another issue.
Could you maybe create an example repo that reproduces the issue?

**Comment by manekshms** [comment]
Deleted node_modules folder and reinstalled the packages solved the problem
Thanks
