### ISSUE TITLE
Is the parameter req passed to matchedData used ?

### ISSUE THREAD

**Issue by BigFax** [express-validator/express-validator#734]
Hi, 

Since i updated to 6.1.0 (no problem in 5.3.1), the `req.body` fields are immutable after calling their middleware validator. It looks like the parameter `req` passed to matchedData at the call is not used.

Example :

HTTP POST Request : 
```
{
    "visible": "on"
}
```

Middleware :
```javascript
body('visible', ' ') // From here, changes to req.body property "visible" won't be considered by matchedData(req);
    .custom(/* some code */),

function (req, res, next) {
    req.body.visible = false; // value 'on' sent by the client in the HTTP POST changed to false
    console.log(req.body.visible); // will display false
    req.body = matchedData(req);
    console.log(req.body.visible); // will display 'on' if no error
}
```

I would like to know if it is the expected behavior ?
It is linked with using Symbol ?

**Comment by gustavohenke** [comment]
`matchedData` returns the values used during the validation step.
If I'm not mistaken, in v5 it would re-select the values -- so it's a breaking change I didn't notice.

I'm inclined to think that this is the correct behaviour, as the function name is "matched data", and `false` wasn't there before. But I can see why it's a surprise.

What do you think?

**Comment by BigFax** [comment]
I understand the logic behind the function name which is "matched data". It returns request's datas which passed validations. The validations was done before and won't be done again. I don't know why I thought wrongly that `matchedData()` used `req.body` values from his parameter `req` to run validation again without really knowing how it worked behind.

Now, the same behavior happen inside validators : 

```javascript
body('visible', ' ') // From here, changes to req.body property "visible" won't be considered by matchedData(req);
    .custom(function (value, { req }) {
        req.body.visible = (value === 'on') ? true : false; // value 'on' sent by the client in the HTTP POST changed to false
        return !(req.body.visible === req.res.locals.user.visible);
    }),

function (req, res, next) {
    req.body = matchedData(req);
    console.log(req.body.visible); // will display 'on' if no error
}
```

To me, `.custom()` was a good place to format my datas like here with a HTML field `type="checkbox"`. I think it is an expected behavior from .custom() middleware of express-validator to change the field value. Or maybe `customSanitizer()` ? 

If a built-in sanitization middleware is used ( like toArray() or normalizeEmail() ), it will change the field value. In this logic the expected behavior from a custom sanitization middleware should be to allow to change value too. What do you think ?

**Comment by gustavohenke** [comment]
> I think changing field value in validators is an expected behavior from `.custom()` middleware

It isn't.
It was however a workaround for #592 that I have seen people do.

> Or maybe `customSanitizer()` ?

Yeah, use that. Just return the new value:

```js
body('visible').customSanitizer(value => value === 'on')
```

**Comment by BigFax** [comment]
Ok, it's clear now. 
Thank you :)
