### ISSUE TITLE
Secure HTML entities being escaped in version 5.3.1

### ISSUE THREAD

**Issue by federicosan** [express-validator/express-validator#740]
.escape() is scaping already scaped characters for example when escaping a string with an HTML entity &Kappa; it would output` &amp;Kappa;  `so it is escaping & character, this is good for escaping things like &gt, etc but what about greek letters how can I prevent this from escaping & in those cases where it is secure and not needed?

it seems something has unfixed this.

**Comment by gustavohenke** [comment]
This is a problem of the underlying library [validator.js](https://github.com/chriso/validator.js), but to be honest I don't think they can do anything about it anyway.
Reason being that the validator cannot know that it's dealing with an already escaped character. Maybe you should not escape them before submitting the request.
