### ISSUE TITLE
Custom validators ignore return value

### ISSUE THREAD

**Issue by j-o-d-o** [express-validator/express-validator#744]
I just updated from v5.3.1 to the latest v6.1.1. And I realized my custom validators are not working anymore. I used to just `return false;` to make the validator fail. But now I need to throw an exception.

To me this would be a "breaking change", but I couldn't find anything in the changelog. And another question would be if there is a particular benefit doing it that way? I find it cleaner to just return a boolean, cause that is exactly what one asks the validator: "Can you check if this check is true or false?"

**Comment by gustavohenke** [comment]
Hello @j-o-d-o!
Can you please demo your code? It might be a bug somewhere, because returning `false` should still be supported.

**Comment by j-o-d-o** [comment]
Alright, here is a reduced example: https://github.com/j-o-d-o/express-validator-example

It seems like the issue only happens if there is some waiting for an async function within the custom validator. In that case, I have to throw an error, otherwise returning a bool works.
e.g. I am using custom validators to check if there is a duplicate user in the database.

**Comment by gustavohenke** [comment]
Ah yup, when the custom validator is async a resolved promise means a successful result.
I guess it needs more extensive docs then.

**Comment by colinaaa** [comment]
I got the same issue. Really need more extensive docs.

**Comment by sheghun** [comment]
I got the same issue why was it changed it by the way?
The previous method is already good.

**Comment by gustavohenke** [comment]
@sheghun people used to complain that a custom validator needed a return value to tag their field valid.

E.g.
```
check('email').custom(email => findUserByEmail(email).then(user => {
	if (user) {
		throw new Error('email exists');
	}

	return true; // 😐
})
```

...whereas the docs have always stated (although not clearly) that a resolved promise means a valid field. So the return value shouldn't be important.

I have expanded the docs with clearer details on this.

**Comment by Poyoman39** [comment]
+1 I think promise return value should be took in consideration.
