### ISSUE TITLE
Upgrade lodash from v4.17.11

### ISSUE THREAD

**Issue by gustavohenke** [express-validator/express-validator#745]
https://github.com/lodash/lodash/issues/4348

**Comment by gustavohenke** [comment]
Because it was fixed by 92c6421. It just happens that there's no release yet.

**Comment by gustavohenke** [comment]
Fixed on [v6.2.0](https://github.com/express-validator/express-validator/releases/tag/v6.2.0)! 🚢

**Comment by rraallvv** [comment]
Thanks so much.
