### ISSUE TITLE
I want to set a rule that the user cant send a field other than the fields that I set to send to the server.

### ISSUE THREAD

**Issue by behzadnm99** [express-validator/express-validator#746]
I want to set a rule that the user cant send a field other than the fields that I set to send to the server. i want that user send only send this fields : {name: String, city: String}. no OTHER fields.

please help me to do this with express-validator

**Comment by gustavohenke** [comment]
This has been asked before: #266, and it is not something supported by express-validator yet.

Since then I haven't spent much time thinking about this. I welcome any ideas.

**Comment by gustavohenke** [comment]
Also, if you use [`matchedData()`](https://express-validator.github.io/docs/matched-data-api.html), you can pretty much solve the problem of getting more than you expect.

**Comment by gustavohenke** [comment]
Duplicate of #809
