### ISSUE TITLE
List of available validations?

### ISSUE THREAD

**Issue by SirCameron** [express-validator/express-validator#747]
I'm getting message in console telling me notEmpty doesn't exist as a validation.. But nowhere in your documentation can I find a list of available validations....

**Comment by gustavohenke** [comment]
Yep, `notEmpty` doesn't exist (see #476).

Also you can look at the [Validation Chain API docs](https://express-validator.github.io/docs/validation-chain-api.html) for the rest, most specifically the "Standard Validators" section.

**Comment by SirCameron** [comment]
Thanks @gustavohenke
