### ISSUE TITLE
Problem in checkSchema example

### ISSUE THREAD

**Issue by stelasido** [express-validator/express-validator#748]
Hi, I am following the example from here: https://express-validator.github.io/docs/schema-validation.html . It is the exact same example, but when I run the app, I am getting a warning in the console:  

> express-validator: a validator/sanitizer with name isUpperCase does not exist

When I make a request to this route, with invalid data, I am getting this error:

> TypeError: chars.replace is not a function
    at Sanitization.rtrim [as sanitizer] (\node_modules\validator\lib\rtrim.js:15:53)
    at Sanitization.<anonymous> (\node_modules\express-validator\src\context-items\sanitization.js:24:24)
    at Generator.next (<anonymous>)
    at\node_modules\express-validator\src\context-items\sanitization.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (\node_modules\express-validator\src\context-items\sanitization.js:3:12)
    at Sanitization.run (\node_modules\express-validator\src\context-items\sanitization.js:20:16)
    at ContextRunnerImpl.<anonymous> (\node_modules\express-validator\src\chain\context-runner-impl.js:31:43)
    at Generator.next (<anonymous>)
    at \node_modules\express-validator\src\chain\context-runner-impl.js:7:71

**Comment by stelasido** [comment]
It doesn't matter, if I send or no the username with the request.

**Comment by gustavohenke** [comment]
Hello!
`isUpperCase` indeed doesn't exist -- the right validator is `isUppercase`. I've fixed that and pushed a fix to the docs.

Now on to the `TypeError: chars.replace is not a function`, this is a problem I couldn't replicate. Are you using which version of express-validator?

**Comment by stelasido** [comment]
Hi, I am using `^6.1.1`. Is there a list of the validators, because I can't guess what I need ?
For the example, I am trying with `required`, `isRequired`,  but it says `express-validator: a validator/sanitizer with name isRequired does not exist`.

**Comment by sobiodarlington** [comment]
> Hi, I am using `^6.1.1`. Is there a list of the validators, because I can't guess what I need ?
> For the example, I am trying with `required`, `isRequired`, but it says `express-validator: a validator/sanitizer with name isRequired does not exist`.

Check this file for validators
[https://github.com/express-validator/express-validator/blob/master/src/chain/validators.ts](https://github.com/express-validator/express-validator/blob/master/src/chain/validators.ts)

Check this file for sanitizers
[https://github.com/express-validator/express-validator/blob/master/src/chain/sanitizers.ts](https://github.com/express-validator/express-validator/blob/master/src/chain/sanitizers.ts)

**Comment by gustavohenke** [comment]
Also on the docs: https://express-validator.github.io/docs/validation-chain-api.html#standard-validators

**Comment by souravray** [comment]
```
checkSchema({
    parama_name: {
        trim: {
           options: [[" ", "-"]],
        },
    },
 })
```

Giving me following exception-
> chars.replace is not a function

**Comment by fedeci** [comment]
@souravray 
This should work:
```js
checkSchema({
    parama_name: {
        trim: {
           options: " -",
        },
    },
 })
```
