### ISSUE TITLE
Documentation shows { check } = require('express-validator') but code says it's deprecated

### ISSUE THREAD

**Issue by hems** [express-validator/express-validator#752]
In many places on the docs it still shows this:

````js
const { check, oneOf, validationResult } = require('express-validator');
````

but when running the code it says:

>express-validator: requires to express-validator/check are deprecated.You should just use require("express-validator") instead.

**Comment by gustavohenke** [comment]
Hello!
I assume that was an oversight and you're using `require("express-validator/check")` call, which is the deprecated one. `require("express-validator")` is not and is good to use 👍

**Comment by hems** [comment]
you're right!
