### ISSUE TITLE
So the only way to validate with v6 is cluttering my routes???

### ISSUE THREAD

**Issue by kaloraat** [express-validator/express-validator#754]
Previously I applied validation as a middleware like so which is much cleaner...
`router.post('/signup', userSignupValidator, signup);`

```
exports.userSignupValidator = (req, res, next) => {
    req.check('name', 'Name is required').notEmpty();
    req.check('email', 'Email must be between 3 to 32 characters')
        .matches(
            /^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/
        )
        .withMessage('Please type your valid email address')
        .isLength({
            min: 4,
            max: 32
        });

    req.check('password', 'Password is required').notEmpty();
    req.check('password')
        .isLength({ min: 6 })
        .withMessage('Password must contain at least 6 characters')
        .matches(/\d/)
        .withMessage('Password must contain a number');
    const errors = req.validationErrors();
    if (errors) {
        const firstError = errors.map(error => error.msg)[0];
        return res.status(400).json({ error: firstError });
    }
    next();
};
```

But it does not work with version 6. So the only way to validate is cluttering my routes like so... as shown in documentation???

```
app.post('/user', [
  // username must be an email
  check('username').isEmail(),
  // password must be at least 5 chars long
  check('password').isLength({ min: 5 })
], (req, res) => {
  // Finds the validation errors in this request and wraps them in an object with handy functions
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(422).json({ errors: errors.array() });
  }

  User.create({
    username: req.body.username,
    password: req.body.password
  }).then(user => res.json(user));
});
```

**Comment by gustavohenke** [comment]
What is it that you don't like about it?

Anyway, you have escape hatches, like this:
https://express-validator.github.io/docs/running-imperatively.html

**Comment by l2ubin** [comment]
I dont like to be limited with only one way or style of validating things too. Before 6.x , I used to mount the express validator as a middleware and write a validation function which then was added onto the routes. The whole point of doing this was to maintain the code readability and make it look cleaner. Now we have to add all the validations on the routes itself and if there are tons of validations, the route looks lot more like a way big function and there goes your readability

**Comment by sseide** [comment]
Same for me - trying to convert from old 5.x to new style.
for some cases the new version looks better but we use this very case quit often too.
Having multpile different routes either needing the same set of validations was very clear with writing one middleware. And having to change/add one validation of this set there was only one place to modify...

Now we have to make shure ALL routes get updated validations and need to keep them in sync.... 
This is not error-prone...

And before it was quite easy to compare things with other values, not easily possible anymore.
Something like the following. And having to write a custom validator for that is way more work.
And custom validator only works for stuff accessible via req object, cannot add other parameters  to custom validators it seems...

```
let config = { x: "a"}
function userSignupValidator(req, res, next) => {
    req.check('aparam', 'is required').notEmpty().equals(config.x);
    req.check('anotherparam', 'Invalid value').equals(req.session.neededparam)
    ...
}
```

For most things the old api was better...

**Comment by j-o-d-o** [comment]
I find all the points brought up invalid or I don't understand the problems.

1) You can still pass any number of params to custom validators
2) You can still use the express validator "as middleware" just as nicely as before

```typescript
function checkValidation(req: Request, res: Response, next: NextFunction) {
    const errors = validationResult(req);
    if(!errors.isEmpty()) {
        res.status(400).json(errors.array());
    }
    else {
        next();
    }
}

function checkPwd(pwd: string, userName: string) {
  // ... do your password check
}

const val = [
	check('password', 'Wrong Password').custom((value: string, incomming: any) => checkPwd(value, incomming.req.body.user_name))
];

router.post('/user/login', val, checkValidation, (req: Request, res: Response) => {
	// ... api endpoint
});
```

The specific validation, the validation check itself as well as the custom validators can be reused in any number of request you wish without any "cluttering my routes".

For me, I prefer the new API over the old one.

**Comment by gustavohenke** [comment]
Yup, pretty much what @j-o-d-o said.
I have documented below _a lot_ of possible/common ways to run your validations, with both legacy and modern express-validator APIs. They are all doing the same thing. You can pick what you like the most 🙂 

<details>
<summary>1. Legacy style, in-route validations</summary>
```js
app.post('/create-user', (req, res) => {
	req.check('username').isEmail();
	req.check('password').notEmpty();
	const errors = req.validationErrors();
	if (errors.length) {
		return res.status(422).json({ errors });
	}

	// proceed with user creation
	userController.createUser(req);
});
```
</details>

<details>
<summary>2. Legacy style, in-controller validations</summary>
```js
class UserController {
	validateUser(req, res) {
		req.check('username').isEmail();
		req.check('password').notEmpty();
		const errors = req.validationErrors();
		if (errors.length) {
			return res.status(422).json({ errors });
		}
	}

	createUser() {
		// ...
	}
}

app.post('/create-user', (req, res) => {
	userController.validateUser(req, res);

	// proceed with user creation
	userController.createUser(req);
});
```
</details>

<details>
<summary>3. "Modern" style, on-route validations</summary>
```js
app.post('/create-user', [
	check('username').isEmail(),
	check('password').not().isEmpty()
], (req, res) => {
	const errors = validationResult(req).array();
	if (errors.length) {
		return res.status(422).json({ errors });
	}

	// proceed with user creation
	userController.createUser(req);
});
```
</details>

<details>
<summary>4. "Modern" style, on-route external validations</summary>
```js
const userValidations = [
	check('username').isEmail(),
	check('password').not().isEmpty(),
	(req, res, next) => {
		const errors = validationResult(req).array();
		if (errors.length) {
			return res.status(422).json({ errors });
		}

		next();
	},
];
app.post('/create-user', userValidations, (req, res) => {
	// this is guaranteed to run only when request is valid
	// proceed with user creation
	userController.createUser(req);
});
```
</details>


<details>
<summary>5. "Modern" style, on-route imperative validation function</summary>
```js
const validateUser = async (req, res, next) {
	await Promise.all([
		check('username').isEmail().run(req),
		check('password').not().isEmpty().run(req)
	]);

	const errors = validationResult(req).array();
	if (errors.length) {
		return res.status(422).json({ errors });
	}

	next();
}
app.post('/create-user', validateUser, (req, res) => {
	// this is guaranteed to run only when request is valid
	// proceed with user creation
	userController.createUser(req);
});
```
</details>

<details>
<summary>6. "Modern" style, in-route imperative validation function</summary>
```js
const validateUser = async (req, res) {
	await Promise.all([
		check('username').isEmail().run(req),
		check('password').not().isEmpty().run(req)
	]);

	const errors = validationResult(req).array();
	if (errors.length) {
		res.status(422).json({ errors });
		return false;
	}

	return true;
}
app.post('/create-user', (req, res) => {
	const valid = await validateUser(req, res);
	if (!valid) {
		return;
	}

	// this is guaranteed to run only when request is valid
	// proceed with user creation
	userController.createUser(req);
});
```
</details>

**Comment by caub** [comment]
Ideally this library shouldn't even write to `req`

I'd like to do something like:

```js
const validateUser = async (req, res, next) {
	try {
		await validate({
			username: isEmail().run(req),
			password: isEmpty().run(req),
		});
	catch (err) {
		return res.status(422).json({ errors: err.errors });
	}
	next();
}
app.post('/create-user', validateUser, (req, res) => {
	// this is guaranteed to run only when request is valid
	// proceed with user creation
	userController.createUser(req);
});
```

**Comment by sseide** [comment]
@j-o-d-o 
Thanks for the example but how do i use the predefined checks where i need to give additional parameters?

From your example 
<pre>
const val = [
	check('somecode', 'Wrong Code').equals(req.session.somecode)
]
</pre>

It always gives "ReferenceError: req is not defined". Do I have to wrap all standard-validations provided inside custom validation functions to use req/req.session variables?!?

**Comment by caub** [comment]
@sseide I'd advise you something like ajv and json-schemas

**Comment by gustavohenke** [comment]
@sseide 
https://express-validator.github.io/docs/custom-validators-sanitizers.html

**Comment by kaloraat** [comment]
Well the solution shared by @j-o-d-o is the best you can do with version 6. I am closing this now. Thx.
