### ISSUE TITLE
.custom not working on multipart/form-data

### ISSUE THREAD

**Issue by dzyubadmytro** [express-validator/express-validator#757]
Value parameter is undefined in custom validator when POST with form-data

1.Send myProp and mySecondProp as form-data
2.
```
const testValidationModel = [
  body( 'myProp' ).exists().custom( ( value ) => {
    console.log( value );
  } ).withMessage( 'test' ),
  body( 'mySecondProp' ).exists().withMessage( 'test2' ),
];
```
3. value is undefined

**Comment by TintKoKo** [comment]
I have the same issues?

**Comment by gustavohenke** [comment]
Can either of you clarify what your express app setup looks like?

**Comment by dzyubadmytro** [comment]
```
const formidable = require( 'express-formidable' );
const app = express();
app.use( express.json() );


router.post(
  '/test',
  testValidationModel ,
  formidable(),
  async ( req, res ) => { ...
```

**Comment by gustavohenke** [comment]
You specified the validation _before_ the formidable middleware. This means that when express-validator runs, `req.body` is empty, thus all of those validations will fail.

I have replied a similar question here:
https://stackoverflow.com/questions/49276284/express-validator-does-not-see-my-form-fields/49311367#49311367

And you can find lots of questions related to multipart here:
https://stackoverflow.com/search?q=%5Bexpress-validator%5D+multipart
