### ISSUE TITLE
Validate property names

### ISSUE THREAD

**Issue by TheEmrio** [express-validator/express-validator#764]
Hello, how can I validate the property names of an object?
I want to verify that all property names match `/^([a-z]{2,100})$/`
Right now, I am using this:
```ts
query('searchProperties', 'Incorrect property name').exists().custom(props => typeof props === 'object' && props && Object.keys(props).every(prop => /^([a-z]{2,100})$/.test(prop)))
```
Therefore, this query wouldn't pass:
```json
{
  "searchProperties": {
    "thisisok": "foo",
    "this1sN0!OK{}": "bar"
  }
}
```
I don't know if this is a better way of doing it. Any help would be appreciated :D

**Comment by willyboy** [comment]
@TheEmrio This is not an issue. Close it and post to stackoverflow please.
