### ISSUE TITLE
validate body numeric() > 0

### ISSUE THREAD

**Issue by PhuongThaoNguyen** [express-validator/express-validator#769]
I want to validate
 body('value'). exists().isNumeric() and that value have to '> 0'.
I tried to  body('value'). exists().isNumeric() > 0
 or 
body('value'). exists().isNumeric('>0') 
but it not run

**Comment by gustavohenke** [comment]
Take a look at [validator.js' validators](https://github.com/validatorjs/validator.js#validators), you may want to use `isInt`.
