### ISSUE TITLE
Please add optional parameters to custom validator function

### ISSUE THREAD

**Issue by sseide** [express-validator/express-validator#770]
With new API its not possible to add custom values to the validation function as parameters anymore. Please add a possibility to provide them to the custom function for more flexibility.

Example with old API - three different routes comparing the input value with some other values. 
The old API was extremly straigth forward and easy to implement/read.
With new new API i must write FOUR different custom validation functions to provide the same basic functionality...

```
route.post('/blah', function(req,res) {
  req.checkBody('new_pw_2', 'pws does not match').equals(req.body.new_pw)
    .notEquals(req.body.old_pw);
  ...
});
route.post('/blub', function(req,res) {
  req.checkBody('email_confirm', 'emails does not match').equals(req.body.email);
  ...
});
route.get('/yadda/:code', function(req,res) {
  req.checkParam('code', 'invalid request').equals(req.session.checkcode);
  ...
});
```
To make this easier and to need to implement one custom validation function only it should be possible to parametrize a custom validation function with values or allow setting request based values at the definition of the validation chain. This problem does not exists for `equals` function only, but this one is an easy to understand example...
```
// this is not working...
route.post('/blah', 
  [ body('new_pw_2').equals(req.body.new_pw) ],
  function(req,res) {
  ...
})

// other posibility with custom validator (not working right now)..
route.post('/blah',
  [ body('new_pw_2').custom(myCustomFunction, req.body.new_pw) ],
  function(req,res) {
  ...
})
```

Thanks.

**Comment by gustavohenke** [comment]
Hello @sseide, sorry for the delay.

There isn't anything stopping you from baking the condition directly in your custom validator:

```js
body('new_password_2').custom((value, { req }) => {
	if (!req.body.new_password) {
		return true;
	}

	return validateSomehow(value);
})
```

...although it's been possible since v6.1.0 to put conditions on parts of your validation chains:
```js
body('new_password_2')
	.if(body('new_password').exists())
	.custom(validateSomehow)
```

[`check().if()` docs](https://express-validator.github.io/docs/6.1.0/validation-chain-api.html#ifcondition)
