### ISSUE TITLE
Sanitizations are being ran even if validations fail.

### ISSUE THREAD

**Issue by jonterry-sans** [express-validator/express-validator#771]
Working with the following test case I've noticed some odd behaivor.
```
it("should be sanitized properly", async (): Promise<void> => {
  // Setup
  const validations = check("accountId").exists()
    .isString()
    .withMessage(" not a string")
    .isUUID("4")
    .withMessage("Is not v4 uuid")
    .customSanitizer((value): string => {
      console.log(`converting ${value} to lowercase`);
      return value.toLowerCase();
    });
  const originalRequestBody = {
    accountId: uuid.v4().toUpperCase()
  };
  const requestBody = Object.assign({}, originalRequestBody);

  // Test
  const errors = await validateAndReturnErrors([validations], requestBody, {});
  const validRequest = await isRequestValid([validations], requestBody, {});

  // Then
  console.log(`Is request valid? ${validRequest}`);
  console.log("Errors: ", errors);
});
``` 
Produces the following stdout:
```
    converting 717D5C57-7468-4288-9250-DA6305D664BE to lowercase
    converting 717d5c57-7468-4288-9250-da6305d664be to lowercase
    Is request valid? true
    Errors: []
```

If the `requestBody` is changed to the following resulting in a failing test case it still works as expected.
```
const originalRequestBody = {
  accountId: " this is not a uuid   "
};
```
Produces the following stdout:
```
    converting  this is not a uuid  to lowercase
    converting  this is not a uuid  to lowercase
    Is request valid? false
    Errors:  [ { value: ' this is not a uuid ',
        msg: 'Is not v4 uuid',
        param: 'accountId',
        location: 'body' } ]
```
If I use the above failing `requestBody` and update the validation chain to the following, I get a failure on the `trim()` instead of the `isUUID()` validation:
```
const validations = check("accountId").exists()
    .isString()
    .withMessage(" not a string")
    .isUUID("4")
    .withMessage("Is not v4 uuid")
    .trim()
    .withMessage("failed to trim string")
    .customSanitizer((value): string => {
      console.log(`converting ${value} to lowercase`);
      return value.toLowerCase();
    });
```
Produces the following stdout:
```
    converting  this is not a uuid  to lowercase
    converting  this is not a uuid  to lowercase
    Is request valid? false
    Errors:  [ { value: ' this is not a uuid ',
        msg: 'failed to trim string',  // <<<<< this should be "is not v4 uuid"
        param: 'accountId',
        location: 'body' } ]
```

The biggest issue is with the following request body
```
const originalRequestBody = {
  accountId: 1234567
};
```

If I retain the `trim()` sanitization the following stdout is produced:
```
    converting  this is not a uuid  to lowercase
    converting  this is not a uuid  to lowercase
    Is request valid? false
    Errors:  [ { value: 12345,
        msg: ' not a string',
        param: 'accountId',
        location: 'body' },
      { value: 12345,
        msg: 'failed to trim string',
        param: 'accountId',
        location: 'body' } ]
```

and even odder (although it makes sense) the following stdout is produced when I remove the `.trim()` sanitization:
```
    converting  this is not a uuid  to lowercase
    converting  this is not a uuid  to lowercase
    Is request valid? true
    Errors:  []
```
This last situation is due to the sanitizations running even though the validations have failed, and then node throws the following `TypeError: value.toLowerCase is not a function`

So my questions are the following:
1. Should failing validations prior to a given sanitizer prevent it from running?
   - This should retain the ability to do something like `check('uuid').isString().trim().isUUID();`
2. Should custom sanitizers be ran twice for a single field? I would assume no, although this is tertiary to my primary question.

**Comment by kelszo** [comment]
You should be able to use [.bail()](https://express-validator.github.io/docs/validation-chain-api.html#bail) to stop the validation chain on failure.

**Comment by gustavohenke** [comment]
Sorry for my delay. Short answer is use what @kelszo suggested.

Also, note that `.withMessage()` applies to the last validator used, so in the case of

```js
.isUUID()
.withMessage('bla')
.trim()
.withMessage('failed to trim')
```

you're overriding `isUUID`'s message yes 👍

And your sanitizer is running twice because you're seemingly running the chain twice. I'd have to see the definition of `validateAndReturnErrors` and `isRequestValid` to understand if there are issues or not.
