### ISSUE TITLE
Provide the 'pt-BR' mobile phone locale option

### ISSUE THREAD

**Issue by jeduardocosta** [express-validator/express-validator#772]
The [validator.js](https://github.com/validatorjs/validator.js) project already has the `pt-BR` mobile phone locale according to this file: [isMobilePhone.js](https://github.com/validatorjs/validator.js/blob/master/src/lib/isMobilePhone.js).

However, it is not possible to use this locale type since the express-validator library does not map this value in the MobilePhoneLocale options. I think that is necessary to update this file: [options.ts](https://github.com/express-validator/express-validator/blob/master/src/options.ts) 

Expected behavior:

```js
import { check } from 'express-validator';

check('attribute').isMobilePhone('pt-BR');
```

**Comment by gustavohenke** [comment]
Thanks for spotting -- feel free to submit a PR yourself 😃
