### ISSUE TITLE
Set value of `matchedData` `includeOptionals`

### ISSUE THREAD

**Issue by cjancsar** [express-validator/express-validator#774]
Is there a way to set the value of included optionals when using: `matchedData({includeOptionals: true})`

Currently all the optionals appear as `undefined` and I would like them to be null.

**Comment by gustavohenke** [comment]
Not quite using `optional`, but it might be possible with some more elaborate chain, such as this

```ts
check('foo').default(null).if(value => value !== null).isBlabla()
```
