### ISSUE TITLE
UUID validation is broken 

### ISSUE THREAD

**Issue by Sebi2020** [express-validator/express-validator#779]
**Version**: 6.2.0
express-validator does not recognize correct UUIDs and incorrectly identifies them as faulty.

For example: `59823018-9774-4562-a792-d10a15de5a43` (valid uuid v4)
You can test it at: https://www.freecodeformat.com/validate-uuid-guid.php

express-validator complains about the uuid not being a valid v4 uuid.

**Comment by gustavohenke** [comment]
Hello! This is not an issue of express-validator.
Can you please direct it to the underlying dependency [validator](https://github.com/validatorjs/validator.js)? 

Alternatively, try specifying the version as `4` if it helps, e.g.
`check('id').isUUID(4)`

Thanks in advance!
