### ISSUE TITLE
Use case of sanitize middlewares

### ISSUE THREAD

**Issue by BigFax** [express-validator/express-validator#781]
It's possible to use sanitize methods (trim, normalizeEmail, escape...) in validators :

```
body('q')
  .trim()
```

I don't understand when sanitize middleware are required : 

```
sanitizeBody('q')
  .trim()
```

These two examples are the same for me.

Someone could explain me ?

**Comment by usamamashkoor** [comment]
did you find solution i am facing the same problem...?

**Comment by BigFax** [comment]
I am using validator `body('q').trim()`, but i still don't get when to use `sanitizeBody('q').trim()`.

In the doc [here](https://express-validator.github.io/docs/sanitization.html), it is mentionned that if the field isn't validated we may use `sanitizeBody()`. But it looks like it is the same behavior as `body()`.

Maybe sanitize middlewares was useful in previous versions but not anymore.

**Comment by usamamashkoor** [comment]
@BigFax Thanks for quick reply but if it is not working then how we can handle the xss attacks on input...?

**Comment by BigFax** [comment]
It is working fine. My question isn't about XSS. 

Check here for XSS : [https://github.com/cure53/DOMPurify](url)

**Comment by usamamashkoor** [comment]
@BigFax the above link is not working can you please chcek it...?

**Comment by gustavohenke** [comment]
@BigFax indeed the sanitization middlewares don't have a big space these days.
They were mostly carried over from legacy APIs to the new ones, and they don't do anything special.
Will introduce some deprecation notices and eventually remove them.
