### ISSUE TITLE
Wildcard for values with "."

### ISSUE THREAD

**Issue by sajal50** [express-validator/express-validator#790]
For example, if I have objects - 
```
{ "foo.bar" :  { "x" : { "value" : 1 }  } }
```
and

```
{ "foobar" :  { "x" : { "value" : 1 }  } }
```

and in `checkSchema()` if I wanted to write a wildcard for `"value"`, `*.*.value` only works for the second object and not the first. Is there a way to make a single wildcard to work for both?

**Comment by gustavohenke** [comment]
That's possible now in v7.0.0, these are called globstars: `**.value`

[Docs here](https://express-validator.github.io/docs/guides/field-selection#globstars)
