### ISSUE TITLE
Update validator.js version to 12

### ISSUE THREAD

**Issue by MunifTanjim** [express-validator/express-validator#792]
https://www.npmjs.com/package/validator/v/12.0.0

**Comment by gustavohenke** [comment]
PR welcome. Example here: #723

**Comment by gustavohenke** [comment]
Upgraded via a1bb2553c1ee714e8b08f54d6b82e749d8a8ab8c

**Comment by gustavohenke** [comment]
Published as [`v6.4.0`](https://github.com/express-validator/express-validator/releases/tag/v6.4.0).
