### ISSUE TITLE
Error TS2339: Property 'value' does not exist on type 'ValidationError’ 

### ISSUE THREAD

**Issue by francjohny** [express-validator/express-validator#795]
# Current Behavior

Accessing property in union of object types fails for properties not defined on all union members.
```
error TS2339: Property 'value' does not exist on type 'ValidationError'.
  Property 'value' does not exist on type '{ location?: undefined; param: "_error"; msg: any; nestedErrors: ValidationError[]; }'.
```
# Possible Solution

https://github.com/express-validator/express-validator/pull/794

# Environment

TypeScript v3.7.2

**Comment by gustavohenke** [comment]
You would have to check the discriminator, so

```js
if (error.param === '_error') {
  // has nestedErrors
} else {
  // has value
}
```

but I can see how annoying it must be.
...and `location` is there for some reason I don't recall 🤷‍♂
