### ISSUE TITLE
A request is not being mutated (Sanitization)

### ISSUE THREAD

**Issue by alusev** [express-validator/express-validator#796]
I am using `express` "^5.0.0-alpha.7" and `express-validator` "^6.2.0".

When I do a sanitization of any parameter, the request is returned untouched when it quites a chain.

Here is an example of my route. Let's say I pass a query { "xxx" : "1" }. The value is a `string`.
```
 {
        path: "/api/points",
        method: "get",
        handler: [
            query("xxx")
                  .toInt(), // <-- here it's int
                  .customSanitizer( ... ) // <-- it's still integer
            async (req: Request, res: Response) => {
                res.status(200).json(req.query); // <-- here it's initial request (without any sanitizers)
            }
        ]
    },
];
```

**Comment by gustavohenke** [comment]
Closing as it's too old. Please reopen if this issue still persists.
