### ISSUE TITLE
query parameters can not be special characters

### ISSUE THREAD

**Issue by xhkocatepe** [express-validator/express-validator#799]
When I send a http request with query, I get an error due to '+' character is being replaced by white space.
 I expect
url : /clients?gsm=+905555555555
```
    try {
        validationResult(req).throw();
        next();
    } catch (err) {
        const errors = err.array();
       ...
       ...
        next(new BadRequestError(message, ERR_VALIDATION.code));
    }
```
Where value of 'errors' is:
```
{
  "location": "query",
  "param": "gsm",
  //expected value: '+905555555555' 
  "value": " 905555555555", // see the whitespace in the beginning of mobile number 
  "msg": {
    "tr": "Telefon numarası doğru girilmelidir.",
    "en": "Enter a valid phone number."
  }
}
```

**Comment by gustavohenke** [comment]
Hey! Sorry for the delay.
Did you ever fix this? What were your validations/sanitizations?

**Comment by xhkocatepe** [comment]
No problem :) 
I solved problem by doing strictMode:false options of isMobilePhone.
I think a generic solution will be found :)

**Comment by fedeci** [comment]
This was definitely caused by `validator.js`!
