### ISSUE TITLE
wildcard doesn't work on array

### ISSUE THREAD

**Issue by thbl** [express-validator/express-validator#800]
When trying to add wildcard on an array
```router.get('/test/', [
	check('fields').optional().toArray(),
	check('fields.*').optional().isIn(["name","mail","phone"])
  ],asyncHandler(async (req, res, next) => {.....
```
posting query params  ```fields: mail,phone```
i get this error
```
{
    "error": [
        {
            "value": "mail,phone",
            "msg": "Invalid value",
            "param": "fields[0]",
            "location": "query"
        }
    ]
}
```
like it dont take the query parm as an array ?

**Comment by gustavohenke** [comment]
`toArray` pretty much only ensures that the value will be an array; so if `'mail,phone'` was sent, the end value will be `['mail,phone']`.
If you had sent `['mail,phone']`, then the value wouldn't be changed.

It doesn't know about you separating values with commas.
