### ISSUE TITLE
.if(condition) not found

### ISSUE THREAD

**Issue by samvelian13** [express-validator/express-validator#801]
I'm trying to add if condition as it is written in Validation Chain API but this function was now found?
Does anybody know why?
My code is like that
[
   check('name').if( ( value ) =< {
   ...
  }),
]

**Comment by samvelian13** [comment]
P.s. I need that for the update request. Not all fields are required for this request, that's why I need to check the field only when it exists.
Thanks in advance.

**Comment by gustavohenke** [comment]
Which express-validator version are you using?

`check().if()` was only added on [v6.1.0](https://github.com/express-validator/express-validator/releases/tag/v6.1.0).

**Comment by samvelian13** [comment]
thanks a lot, I already saw this versioning thing and solve it in another way
