### ISSUE TITLE
checkSchema does not check named parameters

### ISSUE THREAD

**Issue by dlevacher** [express-validator/express-validator#802]
There seems to be an issue with named routes :
```js
router.get('/check/:hash', checkSchema({
  hash: {
    trim: true,
    isString: true,
    isLength: {
      errorMessage: 'Invalid value',
      options: { min: 8 },
    },
}), () => { ... })
```

When called with route `check/123467890ABCDEF`, `validationResult` returns an error for `hash` with value an empty string.
I checked the route params, and `hash` value is valid. 

The workaround is to use query instead of params : 

```
router.get('/check', checkSchema({
  hash: {
    trim: true,
    isString: true,
    isLength: {
      errorMessage: 'Invalid value',
      options: { min: 8 },
    },
}), () => { ... })
```

And call route `check?hash=1234567890ABCDEF`

Is it a known issue ?

**Comment by gustavohenke** [comment]
Hello! That's not a known issue no.
Which version of express-validator are you using please? I couldn't replicate it with latest on v6.3.0.

**Comment by dlevacher** [comment]
Hi, I am using v6.3.0.

**Comment by dlevacher** [comment]
Ok, my bad !
I tried the validation and it works !
The error is in my middleware... Sorry for the inconvenience.
