### ISSUE TITLE
Strange async custom validator behavior

### ISSUE THREAD

**Issue by Poyoman39** [express-validator/express-validator#803]
With the current implementation, async custom validators resolved result is not taken into account.

As i read in the documentation: 

> The custom validator may return a promise to indicate an async validation task. In case it's rejected, the field is considered invalid

So even with a `resolve(false)`, the validator will be considered as a success.

This leads to make mistakes when you implement validators with async/await style:
```
async isMyValidator() {
  const isAllGood = await someStuff();

  return isAlllGood;
}
```

It's a pain to make it works with the current implementation !
You have to throw an error on every test inside the validator.

**Comment by gustavohenke** [comment]
I remember that express-validator did have this bug at some point where the behaviour wasn't matching the documentation.

I couldn't find exactly which release fixed it, so if you still have this problem, please open a new issue 🙂
