### ISSUE TITLE
Bug: isIn check if all are matching

### ISSUE THREAD

**Issue by marcobiedermann** [express-validator/express-validator#805]
`isIn` does not check if every input matches the given criteria. As long as one matches, the second one is ignored.

Input

```html
<input type="checkbox" name="colors" value="red" checked />
<input type="checkbox" name="colors" value="green" />
<input type="checkbox" name="colors" value="blue" />

<input type="checkbox" name="colors" value="purple" checked />
```

Validation middleware

```js
body('colors').inIn(['red', 'green', 'blue'])
```

Output

```json
{
  "colors": ["red", "purple"]
}
```

Expect `OR` condition (at least one must match) to be replaces by `AND` (all must match)

**Comment by karolpad** [comment]
`isIn` is provided by [validator.js](https://github.com/validatorjs/validator.js#validators) and not defined in express-validator. Based on the documentation from validator.js, `isIn` checks "if the **string** is in a array of allowed values".

Hope that helps!

**Comment by gustavohenke** [comment]
@karolpad highlighted the key to the mistake here.
You should use `colors.*` if you want to validate every color that was submitted.

I will close this issue for now, as you can easily fix your problem by doing that.
But please let me know if you have suggestions on how to improve this feature express-validator -- this is becoming a common issue it seems.

**Comment by marcobiedermann** [comment]
@gustavohenke

Thank you, I figured out that you have to use a combination of both to make it work.

```js
body("colors")
  .toArray(),
body("colors.*")
  .isIn(["blue", "green", "red"])
```
