### ISSUE TITLE
check / ignore empty strings and NULL

### ISSUE THREAD

**Issue by thbl** [express-validator/express-validator#807]
Hi 
How can i ignore objects with empty string / null value ?

I tried:
**POST**
`{mai:""}`
**NODE**
`body('mail').exists({checkFalsy:true}).optional().normalizeEmail().isEmail().isLength({min:0, max: 40})`

but `if(req.body.mail)` returns **true**, but it should return **false** ?

**Comment by gustavohenke** [comment]
If you want the field to be ignored when it's empty string/null, then you must place `{ checkFalsy: true }` in `optional`. Otherwise it will still be validated.

**Comment by ImHarshad** [comment]
This works! Thanks @gustavohenke

**Comment by fedeci** [comment]
Closing this!
/cc @gustavohenke
