### ISSUE TITLE
optional validator within oneOf results in incorrect matchedData

### ISSUE THREAD

**Issue by jasonlaw-dev** [express-validator/express-validator#808]
Assume that there is nothing in req.query.

Say we have validator of the following
`query('testing').optional()`

running matchedData(req) will return {}, which is a correct behavior.

If we change the validator to 
`oneOf([query('testing').optional()])`
running matchedData(req) will return { testing: undefined }, which is not the case back in 5.x.x

**Comment by gustavohenke** [comment]
I believe this was fixed back in https://github.com/express-validator/express-validator/releases/tag/v6.5.0

Please a new issue if not
