### ISSUE TITLE
Checking a custom validator

### ISSUE THREAD

**Issue by jbgruenwald** [express-validator/express-validator#814]
Hi, I'm trying to build a register endpoint for an API. I want to check whether the username already exists. On the official website, I found this information concerning this exact problem:
https://express-validator.github.io/docs/custom-validators-sanitizers.html

Unfortunately if I run this code, I get an UnhandledPromiseRejectionWarning and the API still creates the user, which is not intended. I just found some short code examples where `return Promise.reject` was replaced by `throw new Error`, but with that my programm stops executing completely and doesn't send any response through the API. I'm sure, there's a mistake somewhere in my code, but unfortunately I couldn't find examples showing the full code. Could anybody please help me or send a link to a proper tutorial?

```
const express = require('express');
const router = express.Router();
const User = require('../models/userModel');
const { check, validationResult } = require('express-validator');

const checkUsernameExists = (value) => {
    return User.findOne({ name: value }, (err, user) => {
        if (user) {
            return Promise.reject('already in use');
        }
    });
}

router.post('/', [
    check('name').exists().custom(checkUsernameExists),
    check('email').isEmail(),
    check('password').exists()
], function(req, res, next) {

    // if validation failed, return errors
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        return res.status(422).json({ errors: errors.array() });
    }

    // convert json user to mongoose object
    let user = new User(req.body);

    // do something else
});

module.exports = router;
```

**Comment by gustavohenke** [comment]
Hey @jbgruenwald, I'm sorry that you're going through this problem.
There isn't anything wrong that is immediately obvious to me in your code. Did you find a solution yet?

**Comment by jbgruenwald** [comment]
Hi, no, I didn't find a solution. Now I'm just checking it manually after the validator is executed.

Do you have some sample code of a working program? Unfortunately in the documentation there are only incomplete code snippets

**Comment by savagedev** [comment]
@jbgruenwald I had the same problem and resolved it by wrapping the custom validation code in a promise.

`const checkUsernameExists = (value) => {
	return new Promise((resolve, reject) => {
		User.findOne({ name: value }, (err, user) => {
			if (user) {
				reject('already in use');
			}
			resolve();
		});
	})
}`
