### ISSUE TITLE
how to construct custom validator based on incoming req.body param values

### ISSUE THREAD

**Issue by nikocraft** [express-validator/express-validator#816]
Is it possible to call validation function inside the (req, res) =>{ }

I have some requirements where I need to check what has arrived in via req.body before I can construct the validation array. 

I need to construct validation array based on if one of the params has a specific value. I can't figure out how to do that with the first example since it seems req is not possible to access when taking this approach https://express-validator.github.io/docs/index.html

![image](https://user-images.githubusercontent.com/443080/71564286-a7678480-2a9e-11ea-85e6-72180580a480.png)

Basically I would like to be able to do this:

    app.post('/user', (req, res) => {

      const { importantParam, email, password, firstname, lastname } = request.body

      let validateThis = []
      
      if(importantParam == true)
         validateThis = [
            check('username').isEmail(),
            check('password').isLength({ min: 5 })
         ]
      else 
         validateThis = [
            check('username').isEmail(),
            check('password').isLength({ min: 5 })
            check('firstname').isLength({ min: 5 })
            check('lastname').isLength({ min: 5 })
         ]

      runValidationFunction(validateThis) // <-- is it possible to call validate function like this?

      //now below code can check for validation errors
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(422).json({ errors: errors.array() });
      }
    
      User.create({
        username: req.body.username,
        password: req.body.password
      }).then(user => res.json(user));
    });

**Comment by gustavohenke** [comment]
You can try this:
https://express-validator.github.io/docs/running-imperatively.html
