### ISSUE TITLE
Conditional validation on array/object validation

### ISSUE THREAD

**Issue by MrKaneki** [express-validator/express-validator#817]
I send multiple nested forms as an array of objects in my application.
here's an example:
`[
{"name": "A", "Pre": "", "_destroy": 0},
{"name": "B", "Pre": "", "_destroy": 1}
]`

I use the suggested way to check all the values in the array and it works fine, but I wanted to know that is there any way to only check the objects that their "_destroy" is equal to 1?
I tried some ways that were suggested for conditional validation but it didn't work for this case, maybe I did it the wrong way.

**Comment by gustavohenke** [comment]
At the moment, it isn't straightforward, but you can write something like this:

```js
check('array.*.name')
	.if((value, { req, path, location }) => {
		// Check the sibling .destroy property
		return req[location][path.replace('name', 'destroy') === 1;
	})
	.notEmpty()
```

**Comment by gustavohenke** [comment]
I think that passing the current object will help in such cases when there's a wildcard involved.

My rough proposal is this:

```js
check('array.*.name')
	// Note the new parent object available
	.if((value, { req, path, location, parent }) => {
		return parent.destroy === 1;
	})
	.notEmpty()
```

**Comment by MrKaneki** [comment]
Thanks for the reply,
I tried it for this cases and it didn't work:

Posted data:
`{"activities_attr":[{"name":"","pre":"","duration":"","resource":"","_destroy":""},{"name":"","pre":"","duration":"","resource":"","_destroy":"1"}]}`

In my router:
`router.post('/', [
  check('activities_attr.*.name')
    // Note the new parent object available
    .if((value, { req, path, location, parent }) => {
      return parent._destroy == "1";
    })
    .notEmpty()
], function (req, res, next) {
  const errors = validationResult(req)
  if (!errors.isEmpty()) {
    return res.status(422).json({ errors: errors.array() })
  }
  res.send(req.body);
});`

And it passes the validation without any errors, I tried both suggestions but the result is the same. Is there anything I'm doing wrong here?

There is an error I get in my console too (an error in setting headers, doesn't break the app):
`Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`

**Comment by gustavohenke** [comment]
I mean that that `parent` thing doesn't exist yet. You should try the other example.

**Comment by MrKaneki** [comment]
I had a mistake in requiring the lodash's package. The suggestion works fine.
Thank you.
