### ISSUE TITLE
matchedData still contains data for a validation chain using .if() that returns false.

### ISSUE THREAD

**Issue by karolpad** [express-validator/express-validator#819]
I'm not sure if this is a bug or if I'm not understanding the `onlyValidData` option for `matchedData()` correctly, but I have a validation setup like:

```
check('someObject.nestedObject.propertyA')
     .if((value, { req }) => req.body.someObject.nestedObject)
     .exists()
     ...
```

When I call `matchedData(req)`, I get back:
```
{ 
  ...,
  someObject: {
     nestedObject: {
          propertyA: undefined
     }
  },
  ...
}
```
though I would expect `matchedData` to **not** include the `propertyA` property. It’s not a huge deal as there are obvious ways to work with the output that’s currently being returned.

**Comment by gustavohenke** [comment]
It's definitely a bug. Thanks for reporting.

**Comment by gustavohenke** [comment]
@karolpad here's a potential fix: #821

It's a breaking change though. It seems that before one could have `check('foo')` and that would be a valid, non-optional field by itself.
I'll hold up on merging it for a bit, and maybe release it as a new major version.

**Comment by karolpad** [comment]
@gustavohenke thanks for looking into a fix so quickly! I think your changes look solid and I believe they actually address something else I was going to bring up which was that if all of an objects properties are invalid then do not include the object in `matchedData` either.

(Referencing my code above again as an example) Since `propertyA` is the only property of `nestedObject` and its validation failed AND I do not perform any validations or sanitations on `nestedObject` alone, then `matchedData` should not include `nestedObject` at all and look like:

```
{ 
  ...,
  someObject: {
    ...
  },
  ...
}
```

**Comment by zifeo** [comment]
@gustavohenke any news on this? also experiencing this issue

**Comment by gustavohenke** [comment]
This issue should have been fixed since https://github.com/express-validator/express-validator/releases/tag/v6.6.0, as `if` has been using dry-run validations.

Please open a new issue if this is not the case.
