### ISSUE TITLE
oneOf and checkSchema cannot easily be run imperatively.

### ISSUE THREAD

**Issue by adriantrunzo** [express-validator/express-validator#822]
We would like to make use of the the "Running validations imperatively" example [found here](https://express-validator.github.io/docs/running-imperatively.html), but are running into issues with `oneOf` and `checkSchema`. Simply stated the middleware functions returned by these two methods do not implement the [validation chain API](https://express-validator.github.io/docs/validation-chain-api.html#runreq), specifically the `run` method.

If we adapt the imperative example as follows there is a runtime exception because the `run` is not defined (this is just a contrived example):

```
const validate = validations => {
  return async (req, res, next) => {
    await Promise.all(validations.map(validation => validation.run(req)));

    const errors = validationResult(req);
    if (errors.isEmpty()) {
      return next();
    }

    res.status(422).json({ errors: errors.array() });
  };
};

app.post('/api/create-user', validate([
  oneOf([
    body('email').isEmail(),
    body('email').equals('admin')
  ]),
  body('password').isLength({ min: 6 })
]), async (req, res, next) => {
  // request is guaranteed to not have any validation errors.
  const user = await User.create({ ... });
});
```

Looking at the source code, it is clear that the middleware function returned by `oneOf()` does not have the same properties as those returned by `check()`.

```
const { body, oneOf } = require('express-validator')

body('test', 'Testing').isString().run
[Function: bound run]

oneOf([body('a').isInt(), body('b').isString()]).run
undefined
```

`checkSchema` is slightly easer to work around since it returns an array of validation chains that will have a `run` method, though the imperative example given in the documentation fails to handle this case as well if you mix `checkSchema` with other validations. `validate(checkSchema({...}))` works fine, but not `validate([param('example')..., checkSchema({...})])`. You need something like the following:

```
const validate = validations => {
  return async (req, res, next) => {
    await Promise.all(validations.map(validation => {
      // Handle a checkSchema
      if (Array.isArray(validation)) {
        return validation.map(subvalidation => subvalidation.run(req))
      }

      // Handle standard validation chain
      if (typeof validation.run === 'function') {
        return validation.run(req)
      }

      // Handle oneOf
      return validation(req, null, (err) => { ... }) // Dummy next method to handle possible error.
    }))

    const errors = validationResult(req);
    if (errors.isEmpty()) {
      return next();
    }

    res.status(422).json({ errors: errors.array() });
  };
};
```

I could not find any documentation stating that `oneOf` and `checkSchema` are not supported for running imperatively, at least per the example middleware for running validations imperatively. Can they be updated to include a `run` method? Or perhaps the middleware example for running validations imperatively could be updated to include handling for `oneOf` and `checkSchema` (when it is used in a mixed array of validation chains)?

**Comment by iyiolapeter** [comment]
Should work natively if you spread the result of checkSchema as follows
```validate([param('example').exists(), ...checkSchema({...})])```

**Comment by Mugilan-Codes** [comment]
I have this same problem. oneOf() is not supported by run(), it is frustrating because it stops me from keeping my code base clean. Help with this, please.

**Comment by bombillazo** [comment]
Any update on this? It would be great to have `oneOf` runnable imperatively to make it part of our custom middleware validations.
