### ISSUE TITLE
Reusing validation rules without request

### ISSUE THREAD

**Issue by AleksaStevic** [express-validator/express-validator#828]
Hi, I am not sure if this is a good place to ask questions about using the package, I apologize if this post is not in the right place.

I have written validation rules for the signup route:
```javascript
exports.signupValidationRules = () => [
  body("username")
    .isAlphanumeric()
    .withMessage("Username can contain alphanumeric characters only.")
    .trim()
    .custom(unique("username", User)), // TODO: test this.
  body("password")
    .isLength({ min: 8 })
    .withMessage("Password needs to be at least 8 characters long.")
    .isAlphanumeric()
    .withMessage("Password can contain alphanumeric characters only."),
  body("accountBalance")
    .optional({ nullable: true })
    .isInt({ min: 1 })
    .withMessage("accountBalance must be a positive integer")
    .toInt()
];
```

Here we see that the username should only contain alphanumeric characters and be unique (`unique(key, model)` just returns a custom validator which checks if the key with the value provided is unique in the collection).

These rules can also be run imperatively with `.run(req)`.

I also have a CLI utility (written in Node) for this application, which also has ability to perform CRUD. For example:

`my-cli create:user <username> <password> [accountBalance]`

I also need exactly the same validation rules like the ones above (for the API). My question is, is there a way to reuse the code above to work without `req`?

One possible solution is to actually rewrite the code (which I don't want to do) to just use `validator` package. In that case, validations can easily be written to be reusable with both API and CLI.

The second solution is to run those validation rules imperatively for the CLI and mock the req.
For example:
```javascript

const { signupValidationRules } = require('./path/to/rules.js');

const validateUser = async (username, password, accountBalance) => {
  const req = {
    body: {
      username,
      password,
      accountBalance
    }
  };

  await Promise.all(signupValidationRules.map(rule => rule.run(req));
  const errors = validationResult(req);

  // the rest of the code...

}
```
Is something like the second solution possible? Is it good practice?

**Comment by gustavohenke** [comment]
> Is something like the second solution possible? Is it good practice?

Doing that would work. That's the way that the express-validator tests are written.

Nonetheless, I guess that exporting the list of validations is desirable, so I'll consider it 👍

**Comment by AleksaStevic** [comment]
Thank you for your response.

Well, the main reason I was exporting validations is so `routes.js` wouldn't be crowded with big arrays of validations for every route. Instead, validations would go to a separate file.
