### ISSUE TITLE
How to use bail() in validation chain.

### ISSUE THREAD

**Issue by kaykhan** [express-validator/express-validator#833]
I want to bail before it reaches my custom validators.

```       
   public classification = () => [
        param("id").exists({ checkNull: true }).isMongoId().bail(),
        param("id")
            .custom(checkIfSessionExists)
            .custom(checkIfSessionIsCompletedOrFailed)
            .custom(checkIfSessionHasExpired)
            .custom(checkIfSessionContainsFrontImage),
        validationResultHandler,
    ]
```

Why can i not apply `.bail()` here:  `param("id").exists({ checkNull: true }).isMongoId().bail(),`

**Comment by karolpad** [comment]
You are applying `bail()` correctly, but your custom validators should be chained right after the bail and not as a seperate chain on the same param. Basically it should look like:

`param("id").exists({ checkNull: true }).isMongoId().bail().custom(...).custom(...)....`
