### ISSUE TITLE
Error in express-validator/src/middlewares/one-of.js:7

### ISSUE THREAD

**Issue by SztefkoKamil** [express-validator/express-validator#835]
After deploy i getting error like below.
Look at this part of error:
/usr/home/webkas/domains/development.webkas.pl/public_nodejs/node_modules/express-validator/src/middlewares/one-of.js:7
return async (req, _res, next) =&gt; {
SyntaxError: Unexpected token (

In hosting i using node 12+ & npm 12+

It's my app bug or express-validator?
How to fix it?

Entire error below

   "error" : {
      "category" : "INTERNAL_ERROR",
      "id" : "7b14da23",
      "problem_description_html" : "<p>The Phusion Passenger application server tried to start the web application through a Passenger-internal helper tool called the \"wrapper\". But Passenger was unable to execute that helper tool because it encountered an internal error.</p><p>The stdout/stderr output of the subprocess so far is:</p><pre>/usr/home/webkas/domains/development.webkas.pl/public_nodejs/node_modules/express-validator/src/middlewares/one-of.js:7\n    return async (req, _res, next) =&gt; {\n                 ^\n\nSyntaxError: Unexpected token (\n    at createScript (vm.js:56:10)\n    at Object.runInThisContext (vm.js:97:10)\n    at Object.vm.runInThisContext (/usr/local/lib/ruby/gems/2.5/gems/passenger-6.0.2/src/helper-scripts/node-loader.js:117:19)\n    at Module._compile (module.js:549:28)\n    at Object.Module._extensions..js (module.js:586:10)\n    at Module.load (module.js:494:32)\n    at tryModuleLoad (module.js:453:12)\n    at Function.Module._load (module.js:445:3)\n    at Module.require (module.js:504:17)\n    at Module.require (/usr/local/lib/ruby/gems/2.5/gems/passenger-6.0.2/src/helper-scripts/node-loader.js:80:25)\n    at require (internal/module.js:20:19)\n    at Object.&lt;anonymous&gt; (/usr/home/webkas/domains/development.webkas.pl/public_nodejs/node_modules/express-validator/src/index.js:6:10)\n    at Module._compile (module.js:577:32)\n    at Object.Module._extensions..js (module.js:586:10)\n    at Module.load (module.js:494:32)\n    at tryModuleLoad (module.js:453:12)\n</pre>",
      "solution_description_html" : "<p class=\"sole-solution\">Unfortunately, Passenger does not know how to solve this problem. Please try troubleshooting the problem by studying the <strong>error message</strong> and the <strong>diagnostics</strong> reports. You can also consult <a href=\"https://www.phusionpassenger.com/support\">the Passenger support resources</a> for help.</p>",
      "summary" : "The application process exited prematurely."
   }

**Comment by SztefkoKamil** [comment]
This was my mistake, bad configuration for application deployment.

**Comment by link867** [comment]
What configuration was bad on your end? I continue to get this error, even when simply running `node -e "require('express-validator');"`

**Comment by SztefkoKamil** [comment]
My hosting require to set special name for project & main app file.
I forgot to change project name, after fix my app runs ok.

**Comment by gustavohenke** [comment]
@link867 which NodeJS version do you have?

**Comment by link867** [comment]
Thank you @gustavohenke, your question made me look and realized my NodeJS version was older than the express-validator min. *facepalm* 

Updated node and its all good. Thank you again!
