### ISSUE TITLE
Validators on get calls?

### ISSUE THREAD

**Issue by fr6nco** [express-validator/express-validator#836]
Hi,

is it possible to check parameters in a get call? I have a feeling, that the validations are not working on get calls. I want to check the supplied parameter with a custom validator, however, I have a feeling that, validations are not working on GET calls. 

I have some custom decorators but basically I apply these middlewares

```
  @Get({
    path: '/role/:roleId',
    authenticated: true,
    validators: [
      param('roleId').isNumeric(),
```

The validator returns an empty array of errors, however the param is present in invalid format
```
 Result { formatter: [Function: formatter], errors: [] }
{ roleId: 'helloworld' }
```

I apply the middlewares this way: 
middlewares contain the auth, validation and permission checks. This method works fine in POST and PUT requests, however the parameters are not validated on a GET request
```
app[route.requestMethod](path, middlewares, async (req: Request, res: Response) => {
        //Validation chain
        const errors = validationResult(req);
        console.log(errors);
       //If validation had errors, return 400 bad request with the array of errors
        if (!errors.isEmpty()) {
          res.status(400).json({ errors: errors.array() });
```

**Comment by gustavohenke** [comment]
Hey @fr6nco, can you please share a reproducible repo? Your code looks alright without testing.

**Comment by fr6nco** [comment]
Hey,

sorry, I wasn't able to reproduce it again. But tested it now it works. So it's more likely was my bug somewhere. I think we can close this.

Thanks

**Comment by gustavohenke** [comment]
Glad you found the issue!
