### ISSUE TITLE
New version 6.4.0 gives deprecated warning on sanitize, but examples show no solution/alternative

### ISSUE THREAD

**Issue by BertCatsburg** [express-validator/express-validator#837]
Hello, 
I just upgraded my express-validator to 6.4.0 and when starting NodeJS/Express server I get an deprecation warning:
```
express-validator: sanitize(), sanitizeBody() and other sanitization-only middlewares have been deprecated.
Please use check(), body() and others instead, which must offer the same API, and more.
```

I'm using the sanitizeParam to convert passed request parameters back from Base64 to its original format (using npm package atob). So, my client is passing the request parameters as Base64 to the NodeJS server.
Base64 is used as an alternative urlencode method here. 

One of the routes looks as follows:

```
router.get('/clientid/:clientid',
    [
        check('clientid')
            .notEmpty()
            .isString(),
        sanitizeParam('clientid')
            .customSanitizer(value => {
                return atob(value);
            })
    ],
    tagController.getTags
);
```

The deprecation warning seems to say I need to use validators for this, but a validator is not able to change the value and pass the changed version on to the controller. 
So, what does express-validator want me to do here when I don't want the deprecation warning?

**Comment by BertCatsburg** [comment]
Fixed it by taking the sanitizeParam out and writing my own sanitize middleware. Now the depreciation warning is gone.
Does this mean express-validator does not do sanitation in newer versions?

**Comment by gustavohenke** [comment]
Hey! Sorry for the inconvenience.
`check`, `body` and etc all provide the same functionality.

https://express-validator.github.io/docs/validation-chain-api.html#sanitization-chain-api

I'll fix the docs to mention this.

**Comment by BertCatsburg** [comment]
Hello Gustovo, 
Thanks for your reply.

In my understanding:  Validation returns only true/false if value is valid (or not). An Sanitizer lets you also change the value (like atob in my case). 
Is that correct? If so, I am missing a Sanitizing example (changing the value) in your docs.

**Comment by gustavohenke** [comment]
Yup, you are correct. There you go!
https://express-validator.github.io/docs/sanitization.html
https://express-validator.github.io/docs/custom-validators-sanitizers.html#custom-sanitizers
