### ISSUE TITLE
Documentation if example doesn't work

### ISSUE THREAD

**Issue by zoutiyx** [express-validator/express-validator#850]
I tried running the example for the `.if` validation chain with a minor change. `.not().empty()` to `.notEmpty()`;

```
[
body('oldPassword')
    // if the new password is provided...
    .if((value, { req }) => req.body.newPassword)
    // OR
    .if(body('newPassword').exists())
    // ...then the old password must be too...
    .notEmpty()
    // ...and they must not be equal.
    .custom((value, { req }) => value !== req.body.newPassword),

  (req, res, next) => {
    const errors = validationResult(req);
    if (!errors.isEmpty())
      return res.status(422).json({ errors: errors.mapped() });
    next();
  }
]
```
Postman body;

`{"oldPassword": "21g41"}`

I only passed in an `oldPassword` and it didn't fail due to `newPassword` not existing. Why is that?

**Comment by gustavohenke** [comment]
Hello @zoutiyx. I'm sorry that it's been a while since you posted.

You didn't get a failure because the `if` step skips the chain if the condition isn't met.
Since you have a condition that's saying "if `newPassword` is provided", your validations didn't run.

Hope this helps.
