### ISSUE TITLE
Validation on optional fields

### ISSUE THREAD

**Issue by GlassHill** [express-validator/express-validator#852]
Hello Everyone,

How do I write schema for fields that are optional? 

For the following example please assume we have:

```
{
 infos: [{...
    resources: [{
                       mimetype: "",
                       desc: ""
                       etc.
                     }]
         ]
}
```

For example an array of objects that may not be provided, but if it is then certain values inside of that array need to exist.

For example:

    body('Data.infos.*.resources.*.').optional().exists().notEmpty(),
The 'resources' array can be optional and if its provided it can't be empty. 

After this initial check I want to make sure that certain fields inside of that array are populated:

    body('Data.infos.*.resources.*.mimeType').exists().notEmpty(),
I.E If the resource array is provided then for each object in resource it needs to provide a mimeType for it.

Is there a way for me to just combine these two checks?

**Comment by zoutiyx** [comment]
I've contemplated posting this for 2 days. But here it is. I use this logic to validate an optional `departments` field and if it exists, then the value inside should follow certain constraints. You should be able to tailor it to your problem.

```
body('departments')
    .exists()
    .isArray({ min: 1 })
    .withMessage(`departments list was empty and/or not valid`)
    .optional(),

  body('departments.*')
    .isLength({ min: 3, max: 70 })
    .withMessage('department name is not between 3 to 70 characters')
    .custom(async value => {
      const exists = await Department.findOne({
        where: { name: { [iLike]: value } }
      });

      if (exists) {
        throw new Error(`department '${exists.name}' exists`);
      }
      return true;
    })
```

Essentially, if `departments` isn't present then it won't check `body('departments.*')`

Hope this gives a little direction
