### ISSUE TITLE
Return a error message that FE can manage

### ISSUE THREAD

**Issue by nebojsanb** [express-validator/express-validator#854]
I would like to return the code of error message, not only a text. The reason is that FE can then take that code and show an adequate message to the user in a user language.

I noticed that in the msg field I can actually send an object, not only string, and that seems to work. I would practically then send {errorCode: 123, errorMessage: "Test error"}.

I could not find anything on this topic anywhere online (sorry if I simply failed to find it) and wanted to check is this ok to do, or maybe this is a bad idea and it should be handled differently.

Thank you and sorry for taking your time.

**Comment by gustavohenke** [comment]
Hey!
Yes this is definitely possible and acceptable.
There are some issues out here that demonstrate this but I couldn't find them at this moment, sorry.

While this is not exactly what you asked for, it may be of your interest as well:
https://express-validator.github.io/docs/custom-error-messages.html#dynamic-messages

Cheers!

**Comment by nebojsanb** [comment]
Hi Gustavo,

Thank you for clarifying this!

All the best.
