### ISSUE TITLE
Allow defaut values

### ISSUE THREAD

**Issue by ronaldour** [express-validator/express-validator#856]
Currently there is not an option to add a default value to an *optional* parameter. I tried implementing this with a CustomSanitizer and CustomValidator but it didn't work because they don't even run when the parameter is set to optional.  Here is an example:

```javascript
checkSchema({
  'params.myArray': {
    in: ['body'],
    isArray: true,
    optional: true, // if it's not set to optional the array validation fails
    customSanitizer: { options: (value) => [] }, //doesn't even run because the optional flag when the parameter doesn't exist
    errorMessage: 'should be an array'
  }
)
```

So I know I can implement another middleware or simply set the default value somewhere else, but I am validating a large object with `checkSchema` and I would save a lot of code by being able to do it. Issue #425 is related, but it's closed. It would be nice to have the option to set a default value or at least to sanitize a non existing value when optional is set

**Comment by alfnori** [comment]
I'm was facing the same issue and ended up using a silly custom validator to make it work.  Im my case I'm using a middleware for LIST requests where I can inject default/fixed values to filter, sort and pagination to req.query. Hope it helps.

```Javascript
 const customOptional = (value, { req }) => (value || req);
 const perPage = [
 query('page')
    .trim()
    .customSanitizer((value) => {
      let page = parseInt(value || defaultPage, 10);
      if (Number.isNaN(page) || page <= 0) page = defaultPage;
      return page;
    })
    .custom(customOptional)
    .isInt()
]
```

**Comment by gustavohenke** [comment]
Out in [`v6.7.0`](https://github.com/express-validator/express-validator/releases/tag/v6.7.0)!

**Comment by luciomr** [comment]
For those using `checkSchema` validation, as alfnori mentioned, a custom validator/salitizer is the way to go. 
The following is an example of an optional parameter of type boolean which defaults to `false`:

```javascript
        optionalBooleanParameter: {
            in: ['body'],
            custom: {
                options: (value) => {
                    if (value && true !== value) {
                        throw new Error('invalid optionalBooleanParameter')
                    }
                    return true // needed. Otherwise, the validator will always fail with falsy values 
                }
            },
            customSanitizer: {
                options: value => value || false
            }
        },
```
        
Falsy values (undefined, null, "", 0) will be converted to false. Only true is valid as a truthy value.
