### ISSUE TITLE
Express-validator .notEquals? 

### ISSUE THREAD

**Issue by AktilaCengiz** [express-validator/express-validator#858]
Hello dear express validator founder!
Can I have an action using a express-validator if a parameter is not equal to what I wrote?
So I want to explain that when they enter a number, I want it to give an error if it's equal to 0.

```
req.checkBody("yuklenecekMiktar","Amount to be payed cannot be less than 0.
").notEquals("0")

```
Is such a thing possible thank you in advance.

**Comment by gustavohenke** [comment]
Sure thing! `.not().equals(value)` is what you're looking for.

**Comment by AktilaCengiz** [comment]
Uh : 
```
TypeError: req.checkBody(...).notEquals is not a function
```
Why am I getting this error? Do you have an idea?
