### ISSUE TITLE
optional({ options: { checkFalsy: true} }) failing with method chaining

### ISSUE THREAD

**Issue by tilakjayswal16** [express-validator/express-validator#859]
My scenario is, I want to ignore request param validation if it is null or "". But the same should be validated for type with isString() or for regex matching with matches() when it is not null or "".

But when I am passing null or blank values, so instead of ignoring the further validations, it is completing the method chain and not ignoring null or blank. 

Below given is the code snippet I have written.

```
check('mcLanAddress')
    .optional({
        options: {
            checkFalsy: true
        }
    })
    .matches('^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$').withMessage('mcLanAddress: IPV4 Format required'),
check('pod', 'pod : String type required')
    .optional({
        options: {
            checkFalsy: true
        }
    }).isString(),
check('tag', 'tag : JSON type allowed')
    .optional({
        options: {
            checkFalsy: true
        }
    }).isJSON()
```
               

Given below is the request param.

```
{
    "pod":null,
    "tag": null,
    "mcLanAddress": "",
}
```

I have tried everything but not able to resolve this. Can you please check is this a bug ?

**Comment by tilakjayswal16** [comment]
I am using express validator v 6.4.0

**Comment by aysiscore** [comment]
Try `.optional({nullable: true, checkFalsy: true})` but I can tell you `optional()` seems dodgy: see #879

**Comment by gustavohenke** [comment]
Syntax is as above. `.optional({ options: { ... } })` is not correct
