### ISSUE TITLE
Handle `isIBAN`

### ISSUE THREAD

**Issue by grallc** [express-validator/express-validator#861]
Hello,
I just noticed than the `isIBAN` validator, which is available in validator package, is missing
it would be cool to implement it ! 😎

**Comment by gustavohenke** [comment]
Hey! Thanks for the heads up @grallc. Will make sure to include it when upgrading to v13 of validator.

**Comment by gustavohenke** [comment]
Closed by #874. Will let you know when the new version has been published (soon!).
