### ISSUE TITLE
Upgrade Validtor to 13.0.0

### ISSUE THREAD

**Issue by pavanmehta91** [express-validator/express-validator#862]
In validator 13.0 there's `isDate` method. It's not present in 12.2.
Can the validator version be upgraded to 13.0.0 for this package

**Comment by gustavohenke** [comment]
Sure thing, but if you have time please go ahead and do it.
I'm a bit busy and not able to give much attention to this project.

**Comment by pavanmehta91** [comment]
Thanks Gustavo. I'll create PR for this one.

**Comment by pavanmehta91** [comment]
https://github.com/express-validator/express-validator/pull/874
PR for the same.

**Comment by gustavohenke** [comment]
Out on v6.5.0!

**Comment by gabrielhpugliese** [comment]
Hi. How do I pass the optional parameter `format` to `.isDate()` when using `checkSchema`?
