### ISSUE TITLE
Import 'express-validator' doesn't work

### ISSUE THREAD

**Issue by FloodGames** [express-validator/express-validator#865]
**Sample** that doesn't work:
```
import { check, validationResult } from "express-validator"
         ^^^^^
SyntaxError: The requested module 'express-validator' does not provide an export named 'check'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
[nodemon] app crashed - waiting for file changes before starting...
```

**Workaround:**
```
import checkAPIs from "express-validator"
const { check, validationResult } = checkAPIs
```

The problem with the workaround is that the webpack build process doesn't seem to work properly.
Can you make the exports ES6-import-proof?

i.e. import { check, validationResult } from "express-validator"

**Comment by VusalIs** [comment]
I think you should change your import statement to `import checkAPIs from 'express-validator/check';`

**Comment by FloodGames** [comment]
> I think you should change your import statement to `import checkAPIs from 'express-validator/check';`

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\GIT\flooded\node_modules\express-validator\check'

**Comment by VusalIs** [comment]
const { check, validationResult } = require('express-validator');

Try this one)

**Comment by FloodGames** [comment]
> const { check, validationResult } = require('express-validator');
> 
> Try this one)

If I run the app with type:"module" in package.json then everything needs to be with import syntax. Require is not allowed.

**Comment by VusalIs** [comment]
In the main Readme file usage of this library in ES6 as following:
`import validator from 'validator';`

**Comment by FloodGames** [comment]
> In the main Readme file usage of this library in ES6 as following:
> `import validator from 'validator';`

You're suggesting another module, i.e. https://www.npmjs.com/package/validator ?

**Comment by aysiscore** [comment]
I just do `import * as validator from 'express-validator'`

**Comment by FloodGames** [comment]
> import * as validator from 'express-validator'

Hmm..
`"validator.body is not a function"`
or
`"validator.check is not a function"`

Vscode does recognize both though!

**Comment by FloodGames** [comment]
Ok everyone. This seems to work!

```
import ValidationChain from "express-validator"
ValidationChain.check("name")
      .isLength({ min: 3 }) //Username must be at least 3 characters long
```

Can be closed.

**Comment by FloodGames** [comment]
Ok everyone. This seems to work!

```
import ValidationChain from "express-validator"
ValidationChain.check("name")
      .isLength({ min: 3 }) //Username must be at least 3 characters long
```

**Comment by FloodGames** [comment]
I've rewritten it to 
`import validator from "validator"

validator.isLength(req.body.name, { min: 3 })`

(another module)
