### ISSUE TITLE
How can I terminate all validation chains in case of error

### ISSUE THREAD

**Issue by zoutiyx** [express-validator/express-validator#866]
I have some validation chains as such;

```
  body('firstName')
    .notEmpty()
    .withMessage('first name is required')
    .trim()
    .isLength({ min: 2, max: 25 })
    .withMessage('first name must be between 2 to 25 characters'),
  body('lastName')
    .notEmpty()
    .withMessage('last name is required')
    .trim()
    .isLength({ min: 2, max: 25 })
    .withMessage('last name must be between 2 to 25 characters')

  and so on...
```

How do I (probably using a custom validation) terminate the check for  `body('lastName')` and the following chains if there are any errors?

**Comment by yavrumian** [comment]
See the [bail()](https://express-validator.github.io/docs/validation-chain-api.html#bail) method in express-validator docs, itterminates all following validations if prevoius one fails
