### ISSUE TITLE
Response type error

### ISSUE THREAD

**Issue by salazarr-js** [express-validator/express-validator#868]
When trying to use `express-validator` with `typescript`
```typescript
import * as express from 'express';
import { query, validationResult } from 'express-validator';

app.get('/', [
  query('url').isURL(),
], (req: express.Request, res: express.Response) => {
...
}
```
Got error
```typescript
interface e.Response<ResBody = any>
error TS7030: Not all code paths return a value.
```

**Comment by ionizer** [comment]
Seems like it's not only the error with Response type. Express Validator somehow converts the typing of request handler parameters (`req`, `res`, `next`) into `any`. This also had caused auto-complete to not work in JS.

```js
const getValidation = [
  check('name').optional(),
];
router.get('/', getValidation, async (req, res, next) => { // ESLint error: Parameter `req`, `res`, `next` has implicitly `any` type
  try {
    const { name } = matchedData(req);
    return res.json({ query: { name }});
  } catch (err) {
    logger.error(err);
    return res.sendStatus(500);
  }
});
```

**Comment by gustavohenke** [comment]
@ionizer your problem is definitely different from the OP's.
You seem to have `noImplicitAny` configuration turned on and you didn't specify the type of the arguments in your route.

**Comment by ionizer** [comment]
> @ionizer your problem is definitely different from the OP's.
> You seem to have `noImplicitAny` configuration turned on and you didn't specify the type of the arguments in your route.

I think I can get away with `noImplicitAny` off in Typescript. But this problem does break VSCode's auto complete on these three regardless of whether we use TS or JS. But let's continue this one in #869.
