### ISSUE TITLE
Express Validator is messing with typings for the route handler

### ISSUE THREAD

**Issue by ionizer** [express-validator/express-validator#869]
First of all, I'm sorry if this has been asked before, but I just noticed that using the validator like the following makes `req`, `res`, and `next` become `any` type:
```js
const getValidation = [
  check('name').optional(),
];
router.get('/', getValidation, async (req, res, next) => { // ESLint error: Parameter `req`, `res`, `next` has implicitly `any` type
  try {
    const { name } = matchedData(req);
    return res.json({ query: { name }});
  } catch (err) {
    logger.error(err);
    return res.sendStatus(500);
  }
});
```

This behavior made some code editors like VSCode provide no auto-complete for `req`, `res`, and `next` objects when the validator is used in such a way, and that Typescript complains that the three parameters are all having implicitly `any` type. I had expected that these three still conforms to Express' `RequestHandlerParams` type and therefore `req`, `res`, `next` has `Request` `Response` and `NextFunction` type respectively.

For your information, I am using express-validator version ^6.4.1

Is this by design, or this shouldn't actually happen?

EDIT:
Seems like I can do this to avoid the implicit `any` issue, but I feel this isn't the way express-validator should be used based on many examples:
```js
router.get('/', ...getValidation, async (req, res, next) => ....
```

**Comment by ionizer** [comment]
Sorry, I kinda posted this issue without looking and this seems linked to #868. Please feel free to close this if you deem that this issue is similar to that one and we can continue there.

**Comment by ionizer** [comment]
Sorry, seems like this is more of an `express` issue. I just discovered that the following example makes Typescript (not ESLint! My bad!) complain about the same error.
```ts
const m1: RequestHandler = (req, res, next) => {
  next();
};

const m2: RequestHandler = (req, res, next) => {
  next();
};

router.post('/', [m1, m2], (req, res, next) => { ... });
```

**Comment by gustavohenke** [comment]
AFAIK express doesn't have official type definitions, they live in https://github.com/DefinitelyTyped/DefinitelyTyped. You can open an issue there or just fix them yourself.

Also, keep in mind that the spread syntax is like you were iterating over an array. Sure it'll be less performant than specifying each handler separately, but the cost is negligible.

And a timeless quote:
> premature optimization is the root of all evil
-- [Donald Knuth](https://en.wikiquote.org/wiki/Donald_Knuth)
