### ISSUE TITLE
Add optional generic type for checkSchema

### ISSUE THREAD

**Issue by ycatbink0t** [express-validator/express-validator#876]
What we have now while using express-validator and TypeScript
`router.('/signup', router.post('', checkSchema({
    email: {
        in: 'body',
    },
    password: {
        in: 'body',
    }
    }), signUpController);`
What we should have
`interface IUser {
    email: string,
    password: string
};
router.('/signup', router.post('', checkSchema<IUser>({
    email: {
        in: 'body',
    },
    password: {
        in: 'body',
    }
    }), signUpController);`

I think it will be cool feature.
Sorry for my bad "issue skills"

**Comment by fedeci** [comment]
Hi @ycatbink0t, can you please provide more information about what the `interface` is expected to do there? Maybe with some other code example :)

**Comment by brianetaveras** [comment]
> Hi @ycatbink0t, can you please provide more information about what the `interface` is expected to do there? Maybe with some other code example :)

I'm guessing what @fedeci meant here was to enable users to use typescript interfaces (or types) to be used as validation.

```ts
type LoginPayload{
   username: string,
   password: string
}


router.post("/login", checkSchema(LoginPayload), signupController);
```

I don't know that this is possible since types don't really make it to the Javascript end, but it would be useful to find a way to validate against typescript types directly.

**Comment by fedeci** [comment]
Exactly, TS interfaces/types are removed at build time so they would not be available when the code is run.
Supporting that kind of validation is possible through babel/typescript transforms but that would be out of the scope of this lib. After some time I am closing this one.
