### ISSUE TITLE
optional() does not treat fields with a value of "null" as optional

### ISSUE THREAD

**Issue by aysiscore** [express-validator/express-validator#879]
Given the following configuration:
```js
 const ExpValidate = require('express-validator');
 router.post('/api/posthandler', 
 [ ExpValidate.body("TopicID").optional({nullable: true, checkFalsy: true}).trim().isInt(), ]
 async function(req, res) {
     const errors = ExpValidate.validationResult(req);
     if (!errors.isEmpty()) {
         return res.status(422).json({ errors: errors.array() });
     }
     else {
     // Handle form here
 }
```
When a form is submitted with `TopicID: null`, then express-validator returns an error despite `{nullable: true, checkFalsy: true}` passed as options above:

```js
 {
     "errors": [
         {
             "value": "null",
             "msg": "Invalid value",
             "param": "TopicID",
             "location": "body"
         }
     ]
 }
```
[Contrary to the docs](https://express-validator.github.io/docs/validation-chain-api.html#optionaloptions), if I pass `TopicID: ""` instead of `TopicID: null` it is treated as optional without any errors.

**Comment by fedeci** [comment]
Hi @aysiscore, maybe `checkFalsy` and `nullable` are not meant to be both true at the same time. 
I will investigate!

**Comment by gustavohenke** [comment]
Looks like is working here: https://runkit.com/gustavohenke/6005f184aa6243001bc4af42

Also, note that you have this in the error you pasted above:

```js
"value": "null",
```

meaning that your value is a string with contents `null` (`value === 'null'`), not a `null` value (`value === null`).
