### ISSUE TITLE
nestedErrors in `formatWith` callback can not use `map()` etc in TS

### ISSUE THREAD

**Issue by pawelfus** [express-validator/express-validator#880]
### Expected behaviour

No error when calling:
```ts
  const formatter = ({ location, msg, param }: ValidationError): string => `${location}[${param}]: ${msg}`;

  const errors = validationResult(req).formatWith(
    (error: ValidationError) => {
      if (error.nestedErrors) {
        return error.nestedErrors.map(formatter).join(' | ');
      }
      
      return formatter(error);
    }
  );
```

### Actual behaviour

Error in TS is thrown:
> This expression is not callable.
  Each member of the union type '(<U>(callbackfn: (value: ValidationError, index: number, array: ValidationError[]) => U, thisArg?: any) => U[]) | (<U>(callbackfn: (value: unknown, index: number, array: unknown[]) => U, thisArg?: any) => U[])' has signatures, but none of those signatures are compatible with each other.ts(2349)

### Workaround
Cast `nestedErrors` to ValidationError array:
```ts
return error.nestedErrors.map(formatter).join(' | ');
```
-> 
```ts
return (error.nestedErrors as ValidationError[]).map(formatter).join(' | ');
```
### Version
- express-validator: v6.5.0
- ts: v3.4.5

**Note:**
I don't know if this is a bug in your TS definitions, just wanted to let you (and other devs) know about this. Never saw this error before. Might be related to https://github.com/microsoft/TypeScript/issues/36390 - maybe that union with `unknown` is unnecessary?

Once again, thanks for the lib! :)

**Comment by gustavohenke** [comment]
Flagging this as part of the v7.0.0 milestone just because I unknowingly improved the type 😛

**Comment by gustavohenke** [comment]
Cut https://github.com/express-validator/express-validator/releases/tag/v7.0.0 with said improvement ✅ 

[Check out docs](https://express-validator.github.io/docs/api/validation-result#error-types)

**Comment by tomtom94** [comment]
Me too I have some ts errors

<img width="766" alt="Capture d’écran 2023-11-19 à 15 21 36" src="https://github.com/express-validator/express-validator/assets/262550/485cb6b4-a481-4e2d-9540-24f0b30c7a01">

I am unable to solve them, please help me.

```Node
import { validationResult, ValidationError, Result } from 'express-validator'
import { Request } from 'express'

export default (req: Request): null | Result<string> => {
  const formatter = ({ location, msg, param }: ValidationError) => `${location}[${param}]: ${msg}`

  const errors = validationResult(req).formatWith((error: ValidationError) => {
    if (error.nestedErrors) {
      return (error.nestedErrors as ValidationError[]).map(formatter).join('\r\n')
    }

    return formatter(error)
  })

  if (!errors.isEmpty()) {
    return errors
  }
  return null
}
```

**Comment by tomtom94** [comment]
I found out I can do something like that, works fine with typescript.

```Node
import { validationResult } from 'express-validator'
import { Request } from 'express'

export default (req: Request): null | string => {
  const errors = validationResult(req).formatWith((error) => {
    switch (error.type) {
      case 'field':
        return `${error.location}[${error.path}]: ${error.msg}`

      case 'alternative':
        return error.nestedErrors.map((nestedError) => `${nestedError.location}[${nestedError.path}]: ${nestedError.msg}`).join('\r\n')

      case 'alternative_grouped':
        return error.nestedErrors
          .map((nestedErrors) =>
            nestedErrors.map((nestedError) => `${nestedError.location}[${nestedError.path}]: ${nestedError.msg}`).join('\r\n')
          )
          .join('\r\n')

      case 'unknown_fields':
        // `error` is an `UnknownFieldsError`
        return `${error.msg}`

      default:
        return `Unknown error type`
    }
  })

  if (!errors.isEmpty()) {
    return errors.array().reduce((acc, error, index) => {
      if (index === 0) {
        return `${error}.`
      }
      return `${acc} ${error}.`
    }, '')
  }

  return null
}

```
