### ISSUE TITLE
an easy way to make property required or allow json property

### ISSUE THREAD

**Issue by ericln** [express-validator/express-validator#882]
I have tried using **checkSchema**, **check**, **body**, to see if there is a way to make property required but without checking the content of it but was unable to find how to do it. Is that even possible?

**Comment by ericln** [comment]
nm found it

**Comment by Sednaoui** [comment]
I am facing the same question. How did you solve it?

**Comment by fedeci** [comment]
@Sednaoui Hi, what about [this](https://express-validator.github.io/docs/validation-chain-api.html#existsoptions)?

**Comment by Sednaoui** [comment]
Hi @fedeci, thanks for answering. Sorry I miss read the question. I was actually looking to know how can I validate an object literal, given any keys or values, and regardless of how many deep nested keys/values there is. 

I tried using isJSON, but obviously it didn't work because the keys in my object do not have  double quotes and is not in JSON format.

**Comment by fedeci** [comment]
If I understood correctly you need something like this:
```js
body('myObject.foo').exists(),
body('myObject.bar').exists()
```

**Comment by Sednaoui** [comment]
You miss-understood me. I assume I don't know if foo or bar exists as keys in my object. I want to only check if I am given an object, no matter what keys or values. Something like that: 

```
'myObject': {
  in: ['body'],
  isObject: true,
  optional: true
},

```

**Comment by fedeci** [comment]
You can use a custom validator for now, but maybe we should implement `isObject`.
```js
custom: {
  options: value => typeof value === 'object',
},
```
/cc @gustavohenke

**Comment by Sednaoui** [comment]
Thanks! I believe it could be something like that: 

```
const isObject = (obj) => {
    return Object.prototype.toString.call(obj) === '[object Object]';
};
```
Happy to contribute if needed
