### ISSUE TITLE
Could use express-validator to validate an object without using {req}

### ISSUE THREAD

**Issue by hoanhax** [express-validator/express-validator#884]
I'm a fan of Express-validator, and I usually use schema to validate my data in middleware
But now I have an issue related to validating objects without `req` in middleware.

Example has an object, this can be queried from database:
`{
  name: 'John',
  age: 12,
  gender: 'male'
}`

Could I use express-validator schema to validate this object without using `req` in middleware?

**Comment by qvdp** [comment]
Hi

I have found a work around for this. You can create your own re-usable validator helper, example for email validation:

```
// email-address.js
const { body } = require('express-validator')

// Your check function
module.exports = (inputName) => body(inputName).isEmail()
```

```
// validator-helper.js
const { validationResult } = require('express-validator')
const rule = require('./email-address)

module.exports = async (data) => {

  // Build an objet similar to `req` with the data you want to validate
  const sample = { body: { data } }

  // Import your validation function and return validation result
  await rule('data').run(sample)
  return validationResult(sample).isEmpty()

}
```
Then you can simply trigger the validation by awaiting the last export.

I am looking to do the same thing but with schema validation now :)

**Comment by hoanhax** [comment]
Thanks qvdp, 
Yea, we can create a fake `req` with data need to validate.

In schema validation, I thought we should replace `req` with `sample`, maybe It is a typo mistake.
`await Promise.all(chains.map(chain => chain.run(req)))` 
`await Promise.all(chains.map(chain => chain.run(sample)))`
