### ISSUE TITLE
Possibility to clear request context or perform dry run validation

### ISSUE THREAD

**Issue by GrzegorzKazana** [express-validator/express-validator#888]
First of all, thank for providing this awesome tool!

**Question**
Is it possible to clear validation errors from request object? Or alternatively perform validation in `dryRun` mode (as seen in the codebase, but I assume it is for internal purposes only right now).

**Why/use case**
I have run into this use case, when using the `next('route')` feature of express which skips current route and forwards the request to the next one, mentioned [here](https://expressjs.com/en/guide/using-middleware.html#middleware.router).

Logic I want to implement is as follows, if the query does not match my validators, I want to forward the request to the next matching handler.

My problem is that the second handler obviously has the errors from the previous one, which is problematic if the second handler had its own validation, which would effectively always fail.

**Minimal repro**
```js
app.get('/', query('foo').exists(), (req, res, next) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        next('route');
    } else {
        res.send('hello from foo');
    }
});

app.get('/', (req, res) => {
    const errors = validationResult(req);
    console.log({ errors });    // logs 'invlid value `foo`' 
    res.send('hello');
});
```

**Comment by gustavohenke** [comment]
Hey! This seems reasonable to do. I'll look at exposing that `dryRun` option you've found!

**Comment by GrzegorzKazana** [comment]
Thanks! As a temporary solution I have settled for a little helper function
```ts
import { contextsKey, InternalRequest } from 'express-validator/src/base';

function clearRequestValidationContext(req: Request): void {
    delete (req as InternalRequest)[contextsKey];
}
```

However, being able to validate request in the `dryRun` mode would be definitely more flexible and elegant solution 🚀

**Comment by gustavohenke** [comment]
Hey @GrzegorzKazana, here you go, out with v6.6.0:
https://express-validator.github.io/docs/validation-chain-api.html#runreq-options

It may not be the best API as it stands, so if you have any suggestions to improve your workflow, please let me know with a new issue 😊

**Comment by GrzegorzKazana** [comment]
Looks really good, will definitely give it a go. Kudos!
