### ISSUE TITLE
👋 Looking for extra maintainers

### ISSUE THREAD

**Issue by gustavohenke** [express-validator/express-validator#889]
👋 Hello, folks!
- Are you using express-validator on your day-to-day?
- Do you have good english skills?
- Are you able to work your way around a decent-complexity codebase?
- Optionally, have you got any history of past open source contributions?

If you've answered yes to most of these questions, then great!
You've (probably) got an unpaid job of maintaining express-validator alongside with me.

I've been very low on time available to maintain express-validator lately, and @ctavan and @rustybailey have long been away from the project.
If that's not enough, I haven't used express-validator myself in a while!

When I can, I do merge a few pull requests here and there, update the validator.js version we support and fix some simple issues but no longer have time to go through the build up of issues (currently, 74!) and help users out.

If you feel like doing some issue triaging, doc writing, bug fixing or feature implementation, you will likely be accepted in 😊 

Please post your "applications" below 👇 🚀

**Comment by liqiang372** [comment]
Hey @gustavohenke, I can help the maintenance

**Comment by gustavohenke** [comment]
Thanks for already being super helpful with the issues!
Please accept the invitation to join the org.

**Comment by manuelitox** [comment]
Hey man @gustavohenke, I have used express-validator a lot last months so, I'd like to help

**Comment by DaemonicNaymon** [comment]
Hiya @gustavohenke , I've been using express-validator quite some time now and would love to help upgrade the docs since it's been a hassle when I wanted to find the isAlpha() method when I needed it when I was a beginner.

**Comment by gustavohenke** [comment]
Hey @manuelitox and @DaemonicNaymon, thanks for raising your hands!
It'd be great to have any pull requests/issue triaging done like @liqiang372 has been doing.

I hate not having time to solve the users' problems. All I can do at the moment is code reviewing and PR merging/releasing 😕

**Comment by DaemonicNaymon** [comment]
Hi @gustavohenke , is there a procedure or anything to contribute or can I just take up an issue and work on it? 😁

**Comment by gustavohenke** [comment]
Just go for it! ✅

**Comment by chinesedfan** [comment]
@gustavohenke Hi, glad to join if still seeking for. I am an "issue killer", who has help [axios](https://github.com/axios/axios) to reduce its issues/prs from 500+/200+ to ~200/50. Now axios doesn't require too much time and I want to help this project before too much things accumulated.

**Comment by gustavohenke** [comment]
Hi @chinesedfan! Yeah it'd be awesome if you're looking to help, answering questions, doing small PR fixes are great ways to start!

**Comment by gustavohenke** [comment]
Looks like we're well served for now. Will reopen if needed. ❤️
