### ISSUE TITLE
NotEmpty converts undefined to empty string

### ISSUE THREAD

**Issue by StigoSvK** [express-validator/express-validator#890]
Hi, I'm using checkSchema validation to validate my request body

`checkSchema({
        searchedValue: {
            notEmpty: true,
            trim: true,
            errorMessage: 'searchedValue is not present',
        },
        sessionId: {
            notEmpty: true,
            trim: true,
            errorMessage: 'sessionId is not present',
        },
    })`

Problem is that when sessionId or searchedValue is not present in request body and errors are not resolved and whole request is not rejected, sessionId is converted to empty string. I'm wondering why is my request body modified. All others params which are not present  stay undefined, only validated params are converted to undefined, even without "notEmpty" option.

Edit: So I find out, that trim option converts undefined values to empty strings.

**Comment by komildeveloper** [comment]
thank you bro


пн, 22 июн. 2020 г. в 13:27, StigoSvK <notifications@github.com>:

**Comment by gustavohenke** [comment]
You're using `trim` sanitizer it seems.

**Comment by StigoSvK** [comment]
Yes I use sanitizer for my value. Problem is, when some not required value is not present, trim convert undefined to empty strings and I have full DB of empty strings. Is this correct behavior? I would say it's not but correct me if I'm wrong. Thanks
