### ISSUE TITLE
.bail() does not seem to be working (for custom validation)

### ISSUE THREAD

**Issue by rubenvereecken** [express-validator/express-validator#892]
First off, I think this is a fantastic library.

I'm a bit confused by this as I've read through the PR implementing `.bail()` and I'm not sure what I'm doing wrong. My validation chain does not seem to stop on the first error.

Consider this example. It should stop if the field `date` does not exist.
```
	validator.body('date').bail().exists().custom((v) => {throw new Error('Uh oh.')}),
```

Yet still I have `validator.validationResult(req).array().length == 2` for a request with an empty body. And indeed, the second error is my custom one. As I understand, that shouldn't have happened.

I'm on `express-validator@6.4.1`.

**Comment by rubenvereecken** [comment]
I think this is related. In my use case I've got both a custom validator and sanitizer for a date field. Despite using `.bail()`, the sanitizer gets run even after the validator fails. Ideally I'd like the sanitizer to be skipped too so it doesn't have to make sure the input is valid, which I was hoping the validation chain would take care of. Now I have a "valid date" check in both validator and sanitizer to make it work. 

```typescript
	chain = chain.bail().notEmpty().custom(validateDate).customSanitizer(sanitizeDate);
```

**Comment by liqiang372** [comment]
check the [bail doc](https://express-validator.github.io/docs/validation-chain-api.html#bail)
it is supposed to be used after one validation

```js
validator.body('date')
 .exists()
 .bail()
```
if `date` exists, `bail` is ignored and continue to pick up next chain method. Otherwise, it will stop there.

**Comment by rubenvereecken** [comment]
Thanks @liqiang372. I don't know where I got it from but I very misunderstood how it worked. I thought it "turned on" bailing for the whole chain so it could be used early. I like bailing.
