### ISSUE TITLE
checkSchema: Best way to validate if a field is even a part of the schema

### ISSUE THREAD

**Issue by mgoodnight** [express-validator/express-validator#893]
Given this schema and route controller:

```
const { checkSchema, validationResult } = require('express-validator');
app.post('/user', checkSchema({
  email: {
    isEmail: {
      errorMessage: 'Invalid email'
    }
  },
  password: {
    isLength: {
      errorMessage: 'Password should be at least 7 chars long',
      options: { min: 7 }
    }
  }
}), (req, res, next) => {
  if (validationResult(req).array().length) {
    return res.status(400).send({ error: validationResult(req).array()[0].msg });
  }
  ...
})
```

If I `POST /user { "email": "matt@fake.com", "password":  "fake1234", "foo": "bar" }` how can I go about generating a schema validation error that will be catch the field `foo` as not being a part of the schema?

**Comment by defusevenue** [comment]
Why would you want to do that? By checking if every single field in the post body is part of the schema, you are wasting resources and increasing the response time by doing unnecessary checks. If you used something like a for loop, to loop through all the fields, you also open yourself to a resource exhaustion attack.

Checking if every single field given by the user is supposed to be there does not increase security. But if you really wanted to anyways, this would be the most efficient solution:
```js
const fields = ['email', 'password']
Object.keys(req.body).slice(0, 10).some((field) => {
	if (!fields.includes(field)) return res.status(400).send({ error: 'Invalid field found' })
})
```

**Comment by defusevenue** [comment]
Seems like someone else found a workaround to this already: https://github.com/express-validator/express-validator/issues/809#issuecomment-564408059

**Comment by mgoodnight** [comment]
Finally got around to trying out the #809 solution and it does the trick! Thanks.

**Comment by tlevesque-ueat** [comment]
@mgoodnight I'm confused, how does this apply to `checkSchema`?

**Comment by gustavohenke** [comment]
Hi @tlevesque-ueat, the idea is that when you're dealing with posted data, you access only those known to your request by using `matchedData`.

That said, you might also be interested in using `checkExact()`, if you're on v7+.
[Docs](https://express-validator.github.io/docs/api/check-exact)
