### ISSUE TITLE
422 status code in documentation when error happened

### ISSUE THREAD

**Issue by yuanchieh-cheng** [express-validator/express-validator#896]
This is a minor question but it draw my attention that the sample code in documentation
```js
if (!errors.isEmpty()) {
    return res.status(422).json({ errors: errors.array() });
}
```
Based on the MDN [422 Unprocessable Entity](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422)   

422 is used for 
> server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions

In my opinion, return 400 could be a better option if the request is malformed.  
> cannot or will not process the request due to something that is perceived to be a client error

**Comment by gustavohenke** [comment]
Fair point. Would you like to make the change yourself?

**Comment by yuanchieh-cheng** [comment]
Sure.
I could make PR later and leave some time to collect any other comments.
