### ISSUE TITLE
Using if validation chain with schema

### ISSUE THREAD

**Issue by defusevenue** [express-validator/express-validator#897]
I'm trying to use the if [validation chain](https://express-validator.github.io/docs/validation-chain-api.html#ifcondition) with the schema. I've tried following below but I can't seem to get it to work. What is the correct way to use the if validation chain inside schemas?

It might be useful to expand the documentation for schemas. There is very little information on how to use specific validations and sanitizations with it, other than a single example. I had to learn most of it by looking through Github issues. Schemas are very valuable and is something we use a lot and is easy to maintain. Especially useful for dynamic rules.

Failed Attempts:
```js
if: {
     options: (value, { req }) => req.body.field,
},

if: options: (value, { req }) => req.body.field,
```

**Comment by liqiang372** [comment]
it worked for me 

```js
// server side
app.post(
  '/demo',
  checkSchema({
    firstName: {
      if: {
        options: (val, { req }) => {
          return val.length  === 1; // can change the predicate to continue validation or not
        },
      },
      isLength: {
        options: {
          min: 10,
        },
      },
    },
  }),
  (req, res) => {
    const errors = validationResult(req);
    console.log(errors);
    res.end('hello world');
  }
);

// client side
axios.post('/demo', {
  firstName: 'foo',
});

```
