### ISSUE TITLE
How to validate unknown keys 

### ISSUE THREAD

**Issue by rajorpratyush** [express-validator/express-validator#902]
I can't seem to find any way to validate fields that are not defined in validation ,but still sent through request

**Comment by liqiang372** [comment]
Can you elaborate your use cases? does this https://express-validator.github.io/docs/wildcards.html help

**Comment by rajorpratyush** [comment]
Sorry , i was little unclear. I will try to demonstrate with an example

**Suppose i have a express validator middleware as:**
[
  body(“user_id").exists().isLength({ max: 50 }),
  body(“user_name”).exists().isLength({ max: 20 }),
];

**But when i send request with**
{
“user_id”:”1234567”,
“user_name”:”rajorpratyush”,
“some_other_field”:”xyz”,
}

Although **"some_other_field"**  is not defined in validator but validator is letting it pass and is not throwing any exception , My question is : 
Is there any way inherently where errors can be raised when **unknown fields** are encountered ?

**Comment by liqiang372** [comment]
@rajorpratyush FWIK, currently the library only supports validation for a given key. It though has a similar [whole body check](https://express-validator.github.io/docs/whole-body-validation.html) that you don't need to pass a key. But this apparently is not what we want here.

Another api is `whiteList` from [validator.js](https://www.npmjs.com/package/validator). But it only whitelist the values for given key.

A work around is if you want to filter some keys implicitly 
```js
    async (req, res, next) => {
      req.body = {
        user_id: req.body.user_id,
        user_name: req.body.user_name,
      };
      next();
    },
```

or if you want to report error when unknown key is given

```js
    async (req, res, next) => {
      const set = new Set(['user_id', 'user_name']);
      for (const key in req.body) {
        if (!set.has(key)) {
          res.status(400).end();
        }
      }
    },
```

**Comment by rajorpratyush** [comment]
Thanks for your reply, I am already doing in same way as you described 😁
