### ISSUE TITLE
How to validate regex in express-validator?

### ISSUE THREAD

**Issue by TamashiKaizen** [express-validator/express-validator#903]
I'm trying to validate a mobile number regex using [express-validator][1]. 

I have browse through the docs api but couldn't find the validator function that checks a regex. Will using `regex.test()` like the following work?

```

body('mobile', 'Invalid mobile number.')
           .escape()
           .exists({checkFalsy: true})
           .isLength({min: 11, max:11})
           .regex.test(/^(\+123)\d{11}$/)
```

  [1]: https://express-validator.github.io/docs/

**Comment by liqiang372** [comment]
express-validator uses [validator](https://github.com/validatorjs/validator.js) for its underlying engine.
check `matches`

**Comment by TamashiKaizen** [comment]
@liqiang372 thank you
