### ISSUE TITLE
Validation and typescript Request type inference

### ISSUE THREAD

**Issue by CedricPradels** [express-validator/express-validator#911]
Hello, 

how to have request type inference after validation ? 

```js
route.get("/test", query("key").isString(), (req, res) => {
  const error = validationResult(req);
  if (!error.isEmpty()) return res.status(400).json({ error: error.array() });

  // req.query.key has type "any" while I expect type "string"
});
```

Thank for your help.

**Comment by liqiang372** [comment]
I think it's pretty hard to narrow down the types for `req` object. 
This is the types for express Request object

```ts
 interface Request<P extends core.Params = core.ParamsDictionary, ResBody = any, ReqBody = any, ReqQuery = core.Query> extends core.Request<P, ResBody, ReqBody, ReqQuery> { }
```
It basically depends on what types you pass into the Request. 

And if you turn on the `--noImplicitAny` rule, it is totally up to devs to determine the types.

Alternatively you can use [assert functions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions) inside the callback to narrow down. e.g.

```ts
route.get("/test", query("key").isString(), (req, res) => {
  const error = validationResult(req);
  if (!error.isEmpty()) return res.status(400).json({ error: error.array() });
  assertString(req.query.key)
 // then req.query.key will be string
});
```

**Comment by gustavohenke** [comment]
Exactly what @liqiang372 said. This out of express-validator's land.
