### ISSUE TITLE
How to debug 'a validator/sanitizer with name ___ does not exist' messages

### ISSUE THREAD

**Issue by slingshot322** [express-validator/express-validator#913]
Anyone have a good way to debug these types of messages?
```
express-validator: a validator/sanitizer with name options does not exist
express-validator: a validator/sanitizer with name 0 does not exist
express-validator: a validator/sanitizer with name 1 does not exist
express-validator: a validator/sanitizer with name 2 does not exist
express-validator: a validator/sanitizer with name 3 does not exist
express-validator: a validator/sanitizer with name 4 does not exist
express-validator: a validator/sanitizer with name options does not exist
```
I have a lot of individual validator schemas that I've pre-built that I re-use and combine so it's hard to try and pinpoint exactly where these messages are coming from in my code. Looking up docs I don't see anything about debugging options to get a sense of where these are coming from and how to fix them.

**Comment by liqiang372** [comment]
The error comes from [here](https://github.com/express-validator/express-validator/blob/master/src/middlewares/schema.ts#L72)
seems like you have invalid validator/sanitizer named `0`, `1` ... in the schema. Have you checked the [schema doc](https://express-validator.github.io/docs/schema-validation.html)

**Comment by slingshot322** [comment]
Not elegant but did some old school debug output to console to see which schemas were causing the issue and addressing it that way.
