### ISSUE TITLE
Can I stop chain with success?

### ISSUE THREAD

**Issue by guilhermenicolini** [express-validator/express-validator#914]
Example

check('email')
.custom()
.withMessage('Invalid')
.bail()
.isEmail()
.withMessage('Invalid e-mail')

If custom fails, bail will stop with message 'Invalid'
If custom pass, isEmail will be validated.
I want to custom pass with success, but exit chain and not trigger isEmail. Is it possible?

What I want to do is:
I have a body field called type. I want to test email only if type is 'individual'. If is another value, email must be empty. In this condition i want do return true and stop chain

**Comment by liqiang372** [comment]
```ts
  oneOf([
    body('email')
      .custom((val, { req }) => {
        return req.body.type === 'individual';
      })
      .bail()
      .isEmail()
      .withMessage('invalid email'),

    body('email')
      .custom((val, { req }) => {
        return req.body.type !== 'individual';
      })
     .bail()
      .isEmpty()
      .withMessage('should be empty'),
  ]),
```

**Comment by fedeci** [comment]
Hi @guilhermenicolini, have you solved this?
