### ISSUE TITLE
matchedData type

### ISSUE THREAD

**Issue by stellanhaglund** [express-validator/express-validator#917]
Hi, shouldn't the datatype in `matchedData` match the validation?

If I do `query('age').isNumberic().optional()` and `?age=1` I get `{age:'1'}` in `matchedData`.
Wouldn't it make more sense that it was `{age: 1}`?

**Comment by gustavohenke** [comment]
Hey, in this case, `isNumeric` only really validates that the contents are numbers.
It's equivalent to `/[0-9]+/.test(String(someValue))`.

It's a good idea to add a sanitiser to convert it to the data type you want though, e.g. `.isNumeric().toInt()`.
