### ISSUE TITLE
express-validator is Not a funtion problem

### ISSUE THREAD

**Issue by Adamkaram** [express-validator/express-validator#918]
i faced this issue with express-validator earlier

]
[1] TypeError: expressValidator is not a function
[1]     at Object.<anonymous> (C:\Users\Adam\Desktop\3th project\Backend\server.js:19:9)
[1]     at Module._compile (internal/modules/cjs/loader.js:1138:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
[1]     at Module.load (internal/modules/cjs/loader.js:986:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
[1]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
[1]     at internal/main/run_main_module.js:17:47

using this syntax
const expressValidator = require('express-validator');
app.use(expressValidator());

altrady search about this issue and i've found the amswe here #735
it's say change 
**uninstall current version: npm uninstall express-validator
reinstall specific version: npm install --save express-validator@5.3.1**
and my version is 
**"express-validator": "^6.6.1",**

but i don't want to do that why should i use older version ?? is there is any way to fix that

**Comment by Adamkaram** [comment]
@gustavohenke

**Comment by stevenaldinger** [comment]
try  `npm uninstall --save express-validator` and then `npm install --save express-validator@5.3.1`
that worked for me (with the `--save` on uninstall too)

I just spent an hour+ trying to get the newer version to work, I think the bigger issue here is that everyone needs to downgrade to use this node module to begin with

**Comment by Adamkaram** [comment]
@stevenaldinger  yup i know it's working for me as i  said eariler in my issue explain but the question is why shluld i use older version < why they can't fix this probleme tho

**Comment by liqiang372** [comment]
Hi @Adamkaram , as mentioned in #735. This is a API breaking change. You can't install the latest version and still expects to use the older api

**Comment by Adamkaram** [comment]
should i use [](https://express-validator.github.io/docs/) there No talk about using  app.use(expressValidator());
and here's someone facing a bug issue with Non use for it #33
i don't know if it still there or they fixed it

**Comment by Adamkaram** [comment]
i fixed it , there's the migrate guide 
https://github.com/express-validator/express-validator/pull/871/commits/581fb4af7404e3cadb5f216b256b282be16d3268
