### ISSUE TITLE
Validations passing (when they should fail) when chaining promises. 

### ISSUE THREAD

**Issue by dsomel21** [express-validator/express-validator#921]
I've lost all patience for the night, but I've triple checked everything and I cannot figure this out. 

Here is the validation function:

```
const validateChhandType = (action) => {
  switch (action) {
    case 'createChhandType':
      // Make sure this name doesn't exist already
      return [
        body('chhand_name_unicode').isString(),
        body('chhand_name_unicode').custom(isGurmukhi),
        body('chhand_name_english').isString(),
        body('chhand_name_gs').isString(),
        check(
          'chhand_name_unicode',
          'Chhand already exists in the database'
        ).custom((unicode) => {
          return db
            .select('*')
            .from('chhand_types')
            .where('chhand_name_unicode', unicode)
            .first()
            .then((chhandType) => {
              // If this exists, then prevent it from going to the controller
              // return typeof chhandType === 'undefined';
              return false; // Even if you hardcode "false" it still continues as if everything is fine
            });
        }),
      ];
      break;

    default:
      break;
  }
};
```

Which gets called as a middleware function here: 

```
router.post(
  '/chhand-types',
  validateChhandType('createChhandType'),
  createChhandType
);
```

**Comment by liqiang372** [comment]
Hi @dsomel21, sorry to hear that it frustrated you. On the other side, generally,  it would be very helpful if you could provide a minimal reproducible repo or at least what input you have fed into the api, what approaches you have tried, what thoughts you have concluded. Throwing a block of code and saying it's not working and plz help debug it won't help others understand your problem easily and thus do no good to yourself in turn.

**Comment by dsomel21** [comment]
Yeah sorry for the comment if it came off rude. 

That sounds like a good idea, I can include a GIF tonight (or latest, tomorrow) of my input data and where express-validator is supposedly breaking.

Thanks.

**Comment by dsomel21** [comment]
I am going to close this issue. I ended up refactoring it to this:

```js
check('chhand_name_unicode').custom((unicode) => {
  return db
    .select('*')
    .from('chhand_types')
    .where('chhand_name_unicode', unicode)
    .first()
    .then((chhandType) => {
      if (chhandType) return Promise.reject('Chhand already exists');
    });
}),
```

Was the problem that I should have just rejected a Promise, instead of trying to return false?

**Comment by liqiang372** [comment]
@dsomel21 a promised `false` value doesn't mean anything negative. It is still a legit correct value. Like you ask your api if a user exists, if the api returns `false`, then it means the user doesn't exist, but the value itself shouldn't cause your application error. 

check the [custom](https://express-validator.github.io/docs/custom-validators-sanitizers.html#example-checking-if-e-mail-is-in-use) doc.
