### ISSUE TITLE
checkNoUnknown()

### ISSUE THREAD

**Issue by CarlosRodar** [express-validator/express-validator#927]
So I would like to add this to the v4+ APIs, not to the legacy APIs as they are difficult to implement, modularise and type.

My API suggestion for now is:

```js
app.get('/some/path', [
  check('something').not().isEmpty(),
  checkNoUnknown()
], (req, res, next) => {});
```

Any better names? 🤔

_Originally posted by @gustavohenke in https://github.com/express-validator/express-validator/issues/266#issuecomment-359225100_

Did you added this feature for the library?

**Comment by geritol** [comment]
Would love to see something like this if there is a possibility for it!

**Comment by gustavohenke** [comment]
Duplicate of #266 and #578

**Comment by alexandernanberg** [comment]
I'm using a schema but this seems to work quite well

```ts
const schema: Schema = {
  avatar: {
    in: ['body'],
    isURL: true,
    optional: { options: { nullable: true } },
  },
};

const schemaKeys = Object.keys(schema);

await checkSchema({
  ...schema,
  '*': {
    in: ['body'],
    custom: {
      options: (field, { path }) => {
        if (!schemaKeys.includes(path)) {
          throw new Error(`Unknown field: ${path}`);
        }
        return true;
      },
    },
  },
}).run(req);
```

**Comment by gustavohenke** [comment]
This is coming to v7 🙂

**Comment by gustavohenke** [comment]
Hi hi, https://github.com/express-validator/express-validator/releases/tag/v7.0.0 is out with a fix for this 🙂
