### ISSUE TITLE
Is there a way to bail() after one field is failed?

### ISSUE THREAD

**Issue by leedorian** [express-validator/express-validator#928]
Is there a way to bail() after one field is failed, for example:

when user doing the signup, check the captcha first, if the captcha is not correct, will not check the user existence.

```javascript
router.post(
    "/signup",
    [
      check("captcha").custom(
         (value, {req}) => {
            if(!captcha.check(req, value, false)){
              throw new Error("Captcha error");
            }
          return true;
        }
      ).bail(),//not working.
      check("email").custom(
... ...
```

**Comment by gustavohenke** [comment]
Yeah, `bail` works on the single validation chain that it's tied to.

You can look at #926 for another example of how to better control your validation flow!
