### ISSUE TITLE
Strange, undocumented behavior of .notEmpty()

### ISSUE THREAD

**Issue by favph** [express-validator/express-validator#931]
The [documentation states](https://express-validator.github.io/docs/validation-chain-api.html#notempty):

> .notEmpty()
> Adds a validator to check if a value is not empty; that is, a string with a length of 1 or bigger.

but it seems to me there's something left out – how it handles arrays. The value doesn't actually have to be a string for the validation to succeed.

E. g. with express-validator 6.6.1:

```javascript
const express = require('express')
const { query, matchedData, validationResult } = require('express-validator')
const app = express()

app.get('/',
  query('username').notEmpty(),
  function (req, res, next) {
    if (!validationResult(req).isEmpty()) {
      return res.status(400).send(
        validationResult(req).array()
      )
    }
    next()
  },
  function (req, res, next) {
    res.status(200).send(
      { matchedData: matchedData(req, { locations: ['query'] }) }
    )
  }
)

app.listen(8081)
```
The following works as expected:
```shell
$ curl 'localhost:8081?username='
[{"value":"","msg":"Invalid value","param":"username","location":"query"}]
$ curl 'localhost:8081?username=test'
{"matchedData":{"username":"test"}}
```
But with an url param supplied multiple times it succeeds, too:
```shell
$ curl 'localhost:8081?username=test&username=test'
{"matchedData":{"username":["test","test"]}}
```
... though the matched value isn't a string.

There are also strange edge cases:
```shell
$ curl 'localhost:8081?username=test&username='
{"matchedData":{"username":["test",""]}}
$ curl 'localhost:8081?username=&username=test'
[{"value":["","test"],"msg":"Invalid value","param":"username","location":"query"}]
```
It would be great if you could add this to the documentation.

**Comment by fedeci** [comment]
`notEmpty()` validator is just the negated `.isEmpty()`, so if you pass multiple times the same parameter [express](https://github.com/expressjs/express) will convert it to an array containing all the values of that parameter. 
`express-validator` will then validate the array, not the single values contained inside of the array.
```js
// curl 'localhost:8081?username=test&username=name'
// results in this query params
{ username: ['test', 'name'] }

// and this validation
query('username').notEmpty()
// or
query('username').not().isEmpty()

// but username is now an array of strings and not a single string, and is not empty, 
// so the validation succeeds
```

**Comment by favph** [comment]
@fedeci so far it would be reasonable, but then `?username=&username=test` (=> value `["","test"]`) doesn't succeed the validation by `.notEmpty()`.

**Comment by fedeci** [comment]
> @fedeci so far it would be reasonable, but then `?username=&username=test` (=> value `["","test"]`) doesn't succeed the validation by `.notEmpty()`.

Right, that may be a bug caused by the order of elements in the array, I'll check it later and eventually open a PR.

**Comment by fedeci** [comment]
@favph here we go, I just checked, and it doesn't validate the entire array, but the first element of it.
That's why `username=test&username=` validation succeeds and `username=&username=test` does not.
In fact [Validator.js](https://github.com/validatorjs/validator.js) only accepts strings as input, so express-validator is forced to convert any value to that type.
```ts
// this is the function used to convert values to string
export function toString(value: any, deep = true): string {
  if (Array.isArray(value) && value.length && deep) {
    return toString(value[0], false);
  } else if (value instanceof Date) {
    return value.toISOString();
  } else if (value && typeof value === 'object' && value.toString) {
    return value.toString();
  } else if (value == null || (isNaN(value) && !value.length)) {
    return '';
  }

  return String(value);
}
```
The same behaviour may occur also in the other validators "bridging" to `validator.js`.
