### ISSUE TITLE
Sanitizers before optional validators are causing empty value errors

### ISSUE THREAD

**Issue by MhdSyrwan** [express-validator/express-validator#932]
### Affected Version
Issue started to happen after upgrading from `5.3.1` to `6.6.1`

### Issue
Let's take following simplified code block:
```js
router.post('/some-path', [
  body('name').trim(),
  body('name').optional().not().isEmpty(),
], function(req, res, next) {
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({ errors: errors.array() });
  }

  res.send('respond with a resource1');
});

```

and assuming it's called like this (with no name param):
```
POST /some-path
```

### Expectations
I'd expect it not to give any error since `name` is optional 

### What happens
It gives the following error

```json
{
    "errors": [
        {
            "value": "",
            "msg": "Invalid value",
            "param": "name",
            "location": "body"
        }
    ]
}
```

### Observations

Because of the `trim` sanitizer, the library [here](https://github.com/express-validator/express-validator/blob/master/src/context-items/sanitization.ts) is coercing null/undefined values into empty strings `''` which breaks any later `optional` validation.

I understand that if we wrote the validation first it will work. but it should work the opposite way too due to some usage patterns like:
-  Use of sanitizations to make an input fit into a valid model
-  Use of sanitizations to prevent empty/dummy input to be counted as valid by `notEmpty()` validator.

### Possible solution

Can we skip calling standard sanitizers on null/undefined values instead of calling them with empty strings?
Related file: https://github.com/express-validator/express-validator/blob/master/src/context-items/sanitization.ts

**Comment by mohammad-matini** [comment]
It's worth noting that this issue was not present in `v5.3.1` possibly because non-string values were not sanitized prior to `v6.0.0` ([changelog](https://github.com/express-validator/express-validator/releases/tag/v6.0.0)).

**Comment by fedeci** [comment]
@MhdSyrwan Hi, that happens because each chain is independent from the others. https://github.com/express-validator/express-validator/issues/954#issuecomment-743079863
```js
// this should work as expected
body('name').optional().trim().notEmpty()
```
