### ISSUE TITLE
Custom Validator does not work ASYNC/AWAIT

### ISSUE THREAD

**Issue by kondricz** [express-validator/express-validator#933]
Hey everyone,

`.custom(val => ...)`

It will work when if it is a synchronous check.

But it stops working (actually executes), when combined with async/await. I believe it must be connected to https://github.com/express-validator/express-validator/issues/505

```
  body('_id').custom(async (val) => {
    await new Promise((resolve) => setTimeout(resolve, 3000));
    return val === 'sajt';
  }),
```

It actually executes the function, I can read logs from it's body, but it just ignores the last condition. Thanks for the help in advance.

**Comment by kondricz** [comment]
just want to add quickly that the following solution will work:

```
  body('_id').exists().custom((val) => dbHelpers.docAvailable(val, Company).then(res => {
    if (!res) {
      return Promise.reject();
    }
  })),
```

where dbHelpers.docAvailable is a function written in async/await context.

**Comment by gustavohenke** [comment]
Yup, this is according to the documented behaviour, you must reject your promise in order for the validation to succeed/fail.
