### ISSUE TITLE
Does this library, like validatorjs, "validates and sanitizes strings only"?

### ISSUE THREAD

**Issue by chtseac** [express-validator/express-validator#934]
I see that this project is trying to provide validation for basically the body of a RESTful request, but since it is a thin wrapper around [validatorjs/validator.js](https://github.com/validatorjs/validator.js), I can't find any validator for validating that (for example) the parameter is a number and that it is less than 50. I am currently trying to throw lodash function references into the custom validator (`body('num').custom(_.isInteger).custom(v => v>=0&&v<50)`); is this supported / encouraged?

**Comment by fedeci** [comment]
`isInt()` does the job of checking if value is an integer.
```js
body('num').isInt()
```
However if you prefer to use lodash you definitely can, provided that the function returns `true` for successful validations and `false` or `throw` for unsuccessful ones.

**Comment by chtseac** [comment]
> `isInt()` does the job of checking if value is an integer.

The `isInt` function in validatorjs checks if *the string is an integer*. Passing anything other than a string trigger a TypeError.

But it seems like that the values are casted into string first. (Because I don't see an error passing an integer into the `isInt` checker that express-validator provides.

So I guess if I want to actually validate an integer:

```js
body('num').custom(_.isInteger).isInt({min:0, max:49})
```

And if I want the more lenient validator, but a number on the other side of the chain:

```js
body('num').isInt({min:0, max:49}).toInt()
```

If this is correct, I am going to post the solution to SO.

**Comment by chtseac** [comment]
https://github.com/express-validator/express-validator/blob/32be877f3a705db900c0fdd8e814d8d5d953ed3d/src/chain/validators-impl.ts#L208

https://github.com/express-validator/express-validator/blob/32be877f3a705db900c0fdd8e814d8d5d953ed3d/src/chain/validators-impl.ts#L72

https://github.com/express-validator/express-validator/blob/d26fa86ca8f29451290f4c50e9532151cc5ace8a/src/context-items/standard-validation.ts#L16

Found the toString.
