### ISSUE TITLE
cannot update req body

### ISSUE THREAD

**Issue by Siddhesh1992** [express-validator/express-validator#936]
I'm trying to update the target validator req.body.empCode but cannot get updated req.body.empCode in next middleware function

can update req.body.empCode on next validator function or just create new object in req.empCode.
```
body('empCode').custom(async (value, { req }) => {
    if (req.body.hasEmpCode === false) {
      req.body.empCode = '';
    }

    return true;
  })
```

**Comment by chinesedfan** [comment]
I guess you need [custom sanitizer](https://express-validator.github.io/docs/sanitization.html), instead of custom validator.
