### ISSUE TITLE
How to use custom validation for string ?

### ISSUE THREAD

**Issue by illiyyin** [express-validator/express-validator#938]
I wanted to know, how to make custom validation on a string. 
I need the string like "{2 number}/{6 number}/{2 alphabet}/{5 number}"
so an example could be "65/129432/SV/74631"

thanks

**Comment by fedeci** [comment]
Hello, you must use regex validation with `.matches()` validator.
e.g.
```javascript
  check('id').matches(/[0-9]{2}\/[0-9]{6}\/[a-zA-Z]{2}\/[0-9]{5}/g)
```
