### ISSUE TITLE
express validator without express

### ISSUE THREAD

**Issue by ehsan2003** [express-validator/express-validator#941]
## express-validator is awesome, why just express!
I recently used express-validator in my express app and it was the best solution and now I am working on the front-end of that app with react.
but I miss express-validator functionality in front-end for form validation.

I searched a lot on the net but I can't find a way to implement it on my front-end is there a way?
if there is no way so why keep this powerful thing on just express?
## a separated library may be the solution

although I know that the express-validator uses validator.js under the hood 
but it can be very nice to have something like validation chains in the web apps
something like :
```js
import {createValidator} from 'the-name-for-separated-library'

const validator=createValidator([
    check('some-field')
    .exists()
    .isEmail().withMessage('invalid email')
]);

const validationResult=validator.validate({
    'some-field':'an invalid email'
});

if (!validationResult.isEmpty())
      showToEndUserSomeHow(validationResult.array({onlyFirstError:true}))
```

**Comment by ronaldohoch** [comment]
Hello, how are you?
Take a look at the original plugin, the validator.js, it has a client-side implementation too: 

https://github.com/validatorjs/validator.js#client-side-usage

**Comment by ehsan2003** [comment]
> Hello, how are you?
> Take a look at the original plugin, the validator.js, it has a client-side implementation too:
> 
> https://github.com/validatorjs/validator.js#client-side-usage

oh I know that but in that simple validator there isn't something like chains on the express validator

**Comment by chinesedfan** [comment]
If were familiar with how express middlewares run, you can reuse those APIs without changes in express-validator. I will show the main process and you can wrap them as a function as you wish. Not tested but should able to work.

```
const { body, validationResult } = require('express-validator')

// prepare an object
const req = {
  body: {} // put the data to be validated here
}

// prepare validators(middlewares)
const validators = [
  body('somefield1').isEmail(),
  body('somefield2').isEmail(),
]

// execute them and check the result 
Promise.all(
  // empty `res` and `next`
  validators.map(v => v(req, {}, () => {}))
).then(() => {
  const errors = validationResult(req)
})
```

**Comment by ehsan2003** [comment]
> If were familiar with how express middlewares run, you can reuse those APIs without changes in express-validator. I will show the main process and you can wrap them as a function as you wish. Not tested but should able to work.
> 
> ```
> const { body, validationResult } = require('express-validator')
> 
> // prepare an object
> const req = {
>   body: {} // put the data to be validated here
> }
> 
> // prepare validators(middlewares)
> const validators = [
>   body('somefield1').isEmail(),
>   body('somefield2').isEmail(),
> ]
> 
> // execute them and check the result 
> Promise.all(
>   // empty `res` and `next`
>   validators.map(v => v(req, {}, () => {}))
> ).then(() => {
>   const errors = validationResult(req)
> })
> ```

thanks a lot, it was really helpful.

**Comment by fedeci** [comment]
Closing this
/cc @gustavohenke
