### ISSUE TITLE
Change blacklist and whitelist to DenyList and AllowList

### ISSUE THREAD

**Issue by java-james** [express-validator/express-validator#944]
## Is your feature request related to a problem? Please describe.

Inspired by the great presentation https://twitter.com/carolstran/status/1035547140016287746?s=12

Follow suit with github: https://thenextweb.com/dd/2020/06/15/github-plans-to-replace-racially-insensitive-terms-like-master-and-whitelist/
Apple: https://www.firstpost.com/tech/news-analysis/apple-is-replacing-racial-words-like-master-blacklist-whitelist-in-a-push-for-inclusive-language-8611181.html
and Microsoft: https://www.theregister.com/2019/09/03/chromium_microsoft_offensive/

"While the etymology of the words isn't steeped in racial undertones or history like other problematic tech word choices, there is no harm in changing them to synonyms that as just as understandable and avoid the question entirely"
Possible options :

Allowlist
Throughlist
Goodlist
Includelist
Yeslist
Denylist
Blocklist
Poisonlist
Badlist
Excludelist
Nolist

## Describe the solution you'd like

Rename blacklist and whitelist to denylist and allowlist throughout code and documentation.

**Comment by fedeci** [comment]
This would bring some breaking changes and I think could be released in the future along with 7.0.0.

**Comment by fedeci** [comment]
Hi @java-james some months ago I tried to submit a PR to `validator.js`, which is the library on top of which `express-validator` is built, and it was rejected.
It is almost impossible for us to change the name of options and validators without creating a mess with the code, so we have to wait until `validator.js` team accepts to improve those.
