### ISSUE TITLE
Bug:normalizeEmail() is removing '.' from valid email addresss.

### ISSUE THREAD

**Issue by Ace000001** [express-validator/express-validator#946]
When i make a request with a valid email (e.g sunnyace.sa@gmail.com), normalizeEmail() function is removing the first '.' before '@' from the email address. which is clearly changing the email address altogether and email address is clearly not the same any more.

This is causing an unexpected behavior in my app. Of course i can do the email normalization myself in my code but then this defeats the purpose of using express validator. So I was wondering if this an expected behavior or is this something you guys should have a look at.

**Comment by Ace000001** [comment]
for now i am going with customSanitizer() to normalize emails manually...

**Comment by fedeci** [comment]
Gmail doesn't care about dots in the username of the email.
john.appleseed@gmail.com is an alias of johnappleseed@gmail.com and vice versa.

However if you don't want to remove dots from gmail addresses you can change `normalizeEmailOptions`.

e.g.
```js
check('email').normalizeEmail({ gmail_remove_dots: false })
```

**Comment by Ace000001** [comment]
Thank you for pointing me in the right direction. even though its same in google, its causing issues in my APP. 

Is there any proper documentation on normalizeEmailOptions that i can check to avoid unexpected behaviors?

**Comment by jinsley8** [comment]
This solution doesn't seem to work anymore with v6. 

I added `check('email').normalizeEmail({ gmail_remove_dots: false })` but it strips the period still. If I remove `normalizeEmail()` it leaves the gmail address as is.
