### ISSUE TITLE
Bug: req.params string can't be cast to number in sanitizer middlewares

### ISSUE THREAD

**Issue by keepapi** [express-validator/express-validator#949]
## Describe the bug

sanitize req.params with toInt does not "cast" the string to number for next middleware

## To Reproduce

npm i express express-validator

cat <<'EOF' > app.js
const app = require('express')()
const { param, query, validationResult } = require('express-validator')
app.use('/:userId/:stuffId/:catId',
    [
        param('userId').isInt().customSanitizer(value => Number(value)),// 1 try to cast
        param('stuffId').isInt().toInt(),// 2 try to cast with isInt
        param('catId').isInt().customSanitizer((value, { req }) => { req.params.catId = 1000; return req.params.catId }),// 3try to change the hard way
        query('aText').isString().toLowerCase(),
        query('anotherText').isString().customSanitizer(value => value.toLowerCase()),
        (req, res, next) => {
            if (!validationResult(req).isEmpty()) return res.json('error')
            return next()
        }
    ],
    (req, res) => {
        res.json({
            userIdStrangeBehavior: typeof req.params.userId, // it is always a string not a number???
            stuffIdStrangeBehavior: typeof req.params.stuffId, // it is always a string not a number???
            catIdStrangeBehavior: req.params.catId, // not possible to change req.params in customSanitizer???
            ok: req.query.aText,
            okBis: req.query.anotherText
        })
    }
)
app.listen(1234)
EOF

node app.js

http://127.0.0.1:1234/5/60/700?aText=aRandomText&anotherText=heLLO
## Express-validator version:
 - Version: 6.7.0

**Comment by fedeci** [comment]
From [express docs](https://expressjs.com/it/api.html#req.params).
`Any changes made to the req.params object in a middleware or route handler will be reset.`
This means that if you want to sanitize params you have to run the sanitizer imperatively right in the middleware where you are using them (or simply to cast them), otherwise you will only be allowed to validate them.

**Comment by msageryd** [comment]
I wonder if I'm missing something. If I understand what you wrote above, this shouldn't work, should it?

`param('companyId').notEmpty().isInt().toInt()`

I'm using this concept on many of my routes. If I don't add `toInt()`, req.params.companyId will be a string. If I use `toInt()` I'll get a number in req.params.companyId.

Is my way of doing it a bad way? It seems to work.. I usially don't have more middleware before my route handler function. Would I get into trouble if/when I add more middleware?

**Comment by fedeci** [comment]
Hi, have you tried this? 
```js
// let's suppose the parameter is companyId
(req, res, next) => {
  console.log(typeof req.params.companyId);
    next();
  }

```
The logged result should be `string`.

**Comment by msageryd** [comment]
```
  (req, res, next) => {
    console.log(req.params);
    console.log(typeof req.params.blueprintId);
    next();
  },
```

`param('blueprintId').notEmpty().isInt({min: 1}).toInt()`
![image](https://user-images.githubusercontent.com/4483085/101785050-97548380-3afc-11eb-94a8-124e9f18c46d.png)

`param('blueprintId').notEmpty().isInt({min: 1})`
![image](https://user-images.githubusercontent.com/4483085/101785154-b521e880-3afc-11eb-8905-6e5582943158.png)

**Comment by fedeci** [comment]
Which version of express and express-validator are you using?

**Comment by msageryd** [comment]
```
    "express": "^4.16.3",
    "express-validator": "^6.8.0",
```

**Comment by fedeci** [comment]
https://github.com/expressjs/express/issues/3341
It just happens when using with `app.all()` or `app.use()`.
Express docs should be updated :)

**Comment by msageryd** [comment]
Hmm. But I am using app.use for my routes. I don't quite follow when this won't work

The concept of altering for example req.body is widely used in my server. I use it to store the logged in user after authentication via Passport.

Is it a bad idea to cast the values in params directly in the middleware?
What is best practice?

**Comment by fedeci** [comment]
```js
const express = require('express')
const { param } = require('express-validator')
const app = express()

// Not sanitizing correctly
app.use('/route/:id', [
  param('id').isInt().toInt()
  // handle validation errors
], (req, res, next) => {
  console.log(typeof req.params.id) // string
  return res.sendStatus(200)
})

// Sanitizing correctly (tested also with .get and .all)
app.post('/:id', [
  param('id').isInt().toInt()
  // handle validation errors
], (req, res, next) => {
  console.log(typeof req.params.id) // number
  return res.sendStatus(200)
})

app.listen(3000)
```

**Comment by msageryd** [comment]
Thanks!
In my case I'm using app.use to load routers. The routers defines the routes with separate verbs, such as:

```
const routerX = router.route('/companies')
  .get(getCompanies);
  .post([param('companyId').isInt().toInt(), etc], validate, postCompany);
```

The routes are loaded like this:
`app.use(routerX)`

**Comment by fedeci** [comment]
Sure, in this way it works!

**Comment by msageryd** [comment]
I'll ping the OP @keepapi as well. His problem could probably be solved by using the explocit verbs for routes. Sorry again for hijacking the thread. Hopefully he got something out of my posts as well.

**Comment by keepapi** [comment]
> const routerX = router.route('/companies')
>   .get(getCompanies);
>   .post([param('companyId').isInt().toInt(), etc], validate, postCompany);


Thanks for your answers. I also use this technique now !

**Comment by fedeci** [comment]
Closing this :)
