### ISSUE TITLE
Bug: Cannot use oneOf with wildcards

### ISSUE THREAD

**Issue by bombillazo** [express-validator/express-validator#950]
## Describe the bug
When using `oneOf` with wildcard to validate individual elements, they are being evaluated as a complete group.

## To Reproduce
1. Use wildcards inside `oneOf`
```
oneOf([
  body('data.*.id').isInt().withMessage('Param must be int'),
  [
    body('data.*.user_id').isInt().withMessage('Param must be int'),
    body('data.*.book_id').isInt().withMessage('Param must be int'),
  ],
]),
```
2. Send request where each only meets one of the rules:
```
{
    "data": [
        {
            "user_id": 736,
            "book_id": 10
        },
        {
            "id": 34
        }
    ]
}
```

## Expected behavior

Each element is validated according to the `oneOf` array

## Current behavior

Request fails:
```
"errors": [
        {
            "msg": "Invalid value(s)",
            "param": "_error",
            "nestedErrors": [
                {
                    "msg": "Param must be int",
                    "param": "data[0].id",
                    "location": "body"
                },
                {
                    "msg": "Param must be int",
                    "param": "data[1].user_id",
                    "location": "body"
                },
                {
                    "msg": "Param must be int",
                    "param": "data[1].book_id",
                    "location": "body"
                }
            ]
        }
    ],
```
They should pass since it has either an `id` or both `user_id` and `book_id`.

Seems the `OneOf` function with wildcards is storing the same type of checks in the same array for all elements. So if at least one item fails for each of the checks in the `oneOf` array, even if the other condition is met, it will be counted for the complete condition check.

## Express-validator version:
 - Version: 6.7.0

**Comment by gustavohenke** [comment]
> they are being evaluated as a complete group

welp, that's exactly what's being done.

I understand the frustration, and it wouldn't be feasible to fix this with the current API.

A better option would if `oneOf` was part of the chain, e.g.

```
body('data.*').oneOf([
	// Where id, user_id and book_id are all relative to `data.*`
	body('id').isInt(),
	[body('user_id').isInt(), body('book_id').isInt()],
])
```
