### ISSUE TITLE
How to validate custom object in req

### ISSUE THREAD

**Issue by ao-alex** [express-validator/express-validator#953]
Hi there, 
I have middleware which  set user object in the request object, after token validation . Something like this  
```
req.user = {
  email: example@mail.com,
  username: username,
  roles: userRoles;
}
```
Now I would like to validate user email, but Im not sure how to access that property.
I have validator like this but value is undefined,  is there a way to tell lib to look property is specific place, rather than body or params?
```
checkSchema(
{
    user: {
        custom: {
            options: (value) => {
                console.log(value);
                return getProviderByEmail(value.email).then((provider) => {
                  console.log(provider)
                  if (!provider) {
                    return Promise.reject(new Error('Requestor Not Found '));
                  }
                  return provider;
                });
              },
        },
    },
}),
```
`

**Comment by fedeci** [comment]
There is no way, express-validator is intended to validate express input and not any variables. For that I suggest you to use [validator.js](https://github.com/chriso/validator.js) or "manual" validation.

**Comment by fedeci** [comment]
Closing this :)
