### ISSUE TITLE
Question: How can I validate object field only if the object is present

### ISSUE THREAD

**Issue by donqui** [express-validator/express-validator#954]
Hello,

I am trying to create a schema to validate an optional field, that is a JSON, but only if that field is present:

```json
  "user": {
    "in": ["body"],
    "optional": true
  },
  "user.name": {
   "in": ["body"],
   "isString": true
  },
  "user.email": {
    "in": ["body"],
    "isEmail": true
  },
...
```

But this is not working, even though `user` is marked as optional, checks that follow are not taking that into the account.

So my question is if it is possible to do this?

**Comment by fedeci** [comment]
If I understood your problem you get some errors when you try to validate, for example, an empty body, am I right?

Well, each property is handled independently from the others, so when validating `user.name` express-validator does not know you defined `user` as optional and, not finding it, returns an error.
```js
// This works
'user.name': {
  in: ['body'],
  isString: true,
  optional: true
},
'user.email': {
  in: ['body'],
  isEmail: true,
  optional: true
},
```
