### ISSUE TITLE
custom sanitizer: Split String

### ISSUE THREAD

**Issue by Inkbug** [express-validator/express-validator#955]
Would it be possible to add a "split" sanitizer?

For example, if I am expecting an input of the form: "Apples,Oranges,Pears", I can run:

    check('fruit').isString().split(',').isArray({min: 2, max: 5})

and then `body.fruit` would be `["Apples", "Oranges", "Pears"]`

**Comment by fedeci** [comment]
Is there any particular use case for this?

**Comment by gustavohenke** [comment]
Closing due to no response

**Comment by p4sh4** [comment]
One potential use case is when a query parameter can receive either a single string or string with commas that represents multiple strings, so you'd need to validate either the single string, or each string after it was split.
