### ISSUE TITLE
Bug: oneOf returns all the errors of a group

### ISSUE THREAD

**Issue by kouraf** [express-validator/express-validator#956]
## Describe the bug
when using `oneOf` with groups of validation it returns all the errors of a group

## To Reproduce
1. use oneOf
```
oneOf([ 
 [
  body('name').equals('foo'),
  body('age').exists().isInt()
 ],
 [
  body('name').equals('bar'),
  body('work').exists().isString()
 ]
])
```
2. send a body with one wrong filed
```
{
"name":"foo",
"age":"f"
}
```

## Expected behavior
```
{
      "msg": "Invalid value(s)",
      "param": "_error",
      "nestedErrors": [
        {
          "value": "f",
          "msg": "Invalid value",
          "param": "age",
          "location": "body"
        }
     ]
}
```

## Current behavior
 ```
{
      "msg": "Invalid value(s)",
      "param": "_error",
      "nestedErrors": [
        {
          "value": "f",
          "msg": "Invalid value",
          "param": "age",
          "location": "body"
        },
        {
          "value": "foo",
          "msg": "Invalid value",
          "param": "name",
          "location": "body"
        },
        {
          "msg": "Invalid value",
          "param": "work",
          "location": "body"
        },
        {
          "msg": "Invalid value",
          "param": "work",
          "location": "body"
        }
      ]
    }
```

## Express-validator version:
 - Version: 6.6.0

**Comment by fedeci** [comment]
Hi, I don't think this should be treated as a bug, but instead as an improvement of `nestedErrors`.
In particular `oneOf` allows to apply to validators the boolean operator 'or' and, in case of failure, to return all the errors that have been generated.
In your case you only have two properties per "branch", so you can may not want errors of the others, but if you have 5 or 6 it could be useful. What undoubtedly can be done is a further grouping of errors or a specification of the branch from which they were generated.

@gustavohenke do you have any suggestions on how to improve this?

**Comment by gustavohenke** [comment]
Looks like I should have seen this a long time ago 🙃 

> What undoubtedly can be done is a further grouping of errors

Can you clarify, please?

> or a specification of the branch from which they were generated.

This is a simple change, SGTM.

**Comment by gustavohenke** [comment]
Other than these: adding an option to `oneOf` to either see all errors (current v6 behaviour) or just those of the least red group could SGTM if people find it useful.

**Comment by fedeci** [comment]
> > What undoubtedly can be done is a further grouping of errors
> 
> Can you clarify, please?

I meant that we may group the errors per branch instead of showing all of them together.

**Comment by gustavohenke** [comment]
This is out in https://github.com/express-validator/express-validator/releases/tag/v7.0.0 now!
[Docs](https://express-validator.github.io/docs/api/one-of)
