### ISSUE TITLE
Bug: isEmail validation with domains consisting of numbers is incorrect

### ISSUE THREAD

**Issue by mathieumagalhaes** [express-validator/express-validator#958]
## Describe the bug
.isEmail() is not working on domains that consists out of only numbers.

**Example:** We have a certain domain let's call it `12341234.nl` and we have an email for that domain `info@12341234.nl`
The isEmail() will tell you that email is invalid, which it isn't

## To Reproduce
- Use body('email').exists().isEmail() middleware
- Create a request with `info@12341234.fr` in the body under the email property

## Expected behavior
`info@12341234.nl` should be validated as a valid email adress

## Current behavior
`info@12341234.nl` is not valid, or any other email with a domain consisting out of only numbers
when using the .isEmail() validation

## Express-validator version:
express-validator@6.7.0

**Comment by gustavohenke** [comment]
Fixed in v6.8.1!
