### ISSUE TITLE
Bug:error message repeating same number of times as validation rules

### ISSUE THREAD

**Issue by Jonofat** [express-validator/express-validator#960]
When I send a post request to a particular endpoint, the validation errors repeats the same number of times as rules I have set. 

For example, this code:

`body("firstName").not().isEmpty().isAlpha().isLength({ min: 2 }).trim(),`

returns 

```
    "Invalid value",
    "Invalid value",
    "Invalid value",
```

**Comment by fedeci** [comment]
Can you add also the body of the failing request, please?

**Comment by Jonofat** [comment]
Hi there, not sure what you mean by the body, do you mean what json I am sending in the body? If so, I am sending an empty string for starters. I just want to be able to have 1 error message sent back for all issues. So, if it's empty or if less than 2 or not isAlpha(), just send 1 error "Invalid first name". I know that is vague for the user but I would like to do it.

**Comment by fedeci** [comment]
You can check the existence of errors using `validationResult (req) .isEmpty ()` and, if there are, return a custom error message.

**Comment by fedeci** [comment]
Closing this for now.
