### ISSUE TITLE
Same route, Different data fields in the form

### ISSUE THREAD

**Issue by janith-dev** [express-validator/express-validator#964]
I have a scenario where, the end-user submits a form with different data objects on different scenarios.

As u can see below body data objects, fields will differ based on end-user's selection. I know I can simply use different routes for different cases. But I just want to know, Is there any other way, I can achieve this while using same route, since it is more clear and concise. 

Some examples of the data objects attached to the body in different scenarios.

- Account type - Bank, sub type -> normal account

```javascript
{
  accountData: {
    accountName: 'Test',
    accountType: '5fb6902ac3f5695e137f0dba', 
    openingDate: '2020-12-25',
    openingBalance: '150',
    bankAccountType: 'normal-account'
  },
  accountType: 'Bank'
}
```

- Account type - Bank, sub type -> current account

```javascript
{
  accountData: {
    accountName: 'Test',
    accountType: '5fb6902ac3f5695e137f0dba',
    openingDate: '2020-12-25',
    openingBalance: '3000',
    overdraftLimit: '8000',
    bankAccountType: 'current-account'
  },
  accountType: 'Bank'
}
```

- Account type - Credit card

```javascript
{
  accountData: {
    accountName: 'Test',
    accountType: '5fb6902ac3f5695e137f0dc0',
    creditCardLimit: '5000',
    currentOutstanding: '1000',
    cutoffDate: '2020-12-25',
    dueDate: '2020-12-25'
  },
  accountType: 'Credit Card'
}
```

I have tried below, as suggested [here](https://github.com/express-validator/express-validator/pull/658), what I am doing wrong here, since it does not returns any validation error

```javascript
const addAccountValidations = [
  body('accountType')
    .if((value) => value)
    .equals('Bank')
    .if(
      body('accountData.bankAccountType')
        .if((value) => value)
        .equals('normal-account')
    )
    .if(
      body(
        'accountData.accountName',
        'Account name must be minimum 3 and maximum 20 characters'
      ).isLength({min: 3, max: 20})
    ),
];
```

I tried below as well, as suggested [here](https://stackoverflow.com/questions/61712527/express-validator-one-function-that-will-check-multiple-forms), But still no luck, no validation error returns.

```javascript
const addAccountValidations = (req, res, next) => {
  if (req.body.accountType === 'Bank') {
    return [
      body(
        'accountData.accountName',
        'Account name must be minimum 3 and maximum 20 characters'
      ).isLength({min: 3, max: 20}),
    ];
  }
};
```

Any help would be highly appreciated, Since I am stuck at this point for couple days trying many ways without success..

**Comment by fedeci** [comment]
@janith-dev Hi, do you check for errors in `validationResult`?
```js
const validate = (req, res, next) => {

  const errors = validationResult(req)
  if (!errors.isEmpty()) {
    return res.status(400).json({ errors: errors.array() })
  }
  next()
}
```

However you are using `.if` in the wrong way :), because it just stops the execution of the chain ([docs](https://express-validator.github.io/docs/validation-chain-api.html#ifcondition)) and does not throw any error.
> ```js
> const addAccountValidations = [
>   body('accountType')
>     .equals('Bank')
>     .if(
>       body('accountData.bankAccountType')
>         .equals('normal-account')
>     )
>     .if(
>       body(
>         'accountData.accountName',
>         'Account name must be minimum 3 and maximum 20 characters'
>       ).isLength({min: 3, max: 20})
>     ),
> ];
> ```

To make your code work you should use [`oneOf`](https://express-validator.github.io/docs/check-api.html#oneofvalidationchains-message) or a [`customValidator`](https://express-validator.github.io/docs/custom-validators-sanitizers.html#custom-validator).
```js
const addAccountValidations = oneOf([
  body('accountType')
    .equals('Bank'),
  body('accountData.bankAccountType')
    .equals('normal-account'),
  body(
    'accountData.accountName', 
    'Account name must be minimum 3 and maximum 20 characters',
  ).isLength({min: 3, max: 20})
], [
  // other validation "branch"
])
```

**Comment by janith-dev** [comment]
@fedeci, First many thanks for your response

I tried the `oneOf` method u suggested, But it returns empty errors array

- Validation logic

```javascript
const addAccountValidations = oneOf([
  body('accountType').equals('Bank'),
  body('accountData.bankAccountType').equals('normal-account'),
  body(
    'accountData.accountName',
    'Account name must be minimum 3 and maximum 20 characters'
  ).isLength({min: 3, max: 20}),
]);
```

- Validation results

```javascript
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.send({
      hasErrors: true,
      data: req.body,
      validationsErrors: errors.array(),
    });
  }
```

- Result of `errors` and the `req.body` with empty `accountName`

```javascript
Result { formatter: [Function: formatter], errors: [] }
{
  accountData: {
    accountName: '',  //accountName is empty but still no error thrown
    accountType: '5fb6902ac3f5695e137f0dba',
    openingDate: '',
    openingBalance: '',
    bankAccountType: 'normal-account'
  },
  accountType: 'Bank'
}
```

I like to use `customValidator`, But i really do not understand how to use validation chain method inside the `customValidator` and how to return/throw the error correctly on each case.

```javascript
const addAccountValidations = [
  body('accountType').custom((value, {req}) => {
    if (value === 'Bank') {
       // Here I do not know, How to use validation chain methods like, `isLength`, `isEmpty` and how return the error correctly with a error message.
    }
  }),
];
```

**Comment by janith-dev** [comment]
@fedeci, First many thanks for your response

I tried the `oneOf` method u suggested, But it is not working as i intended

- Validation logic

```javascript
const addAccountValidationsTest = oneOf(
  [
    body('accountType').equals('Bank'),
    body('accountData.bankAccountType').equals('normal-account'),
    body(
      'accountData.name',
      'Bank Account name must be minimum 3 and maximum 20 characters'
    ).isLength({min: 3, max: 20}),
  ],
  [
    body('accountType').equals('Credit Card'),
    body(
      'accountData.name',
      'Credit Card name must be minimum 3 and maximum 20 characters'
    ).isLength({min: 3, max: 20}),
  ]
);
```

- Validation results

```javascript
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    console.log('Empty if method called');
    return res.send({
      hasErrors: true,
      data: req.body,
      validationsErrors: errors.array(),
    });
  }
```

- Result from for two different body requests returns the same validation error

- Request with bank account data

![image](https://user-images.githubusercontent.com/9546456/103434656-03b73400-4c1e-11eb-9b2d-c2da95d79e06.png)

- Request with credit card data

![image](https://user-images.githubusercontent.com/9546456/103434549-6a3b5280-4c1c-11eb-9644-66f7ae09e443.png)

> Other strange behaviour, Which i couldn't understand is result of `validationResult(req)` function call, For ex. both above requests works fine with post man and back-end function send the response without any issue (As shown in the screen shots above). But when I send the same request through the web app, second request with `credit card data body` run smoothly but the first request with `bank account data body` never execute the below if block

```javascript
 if (!errors.isEmpty()) {
    console.log('Empty if method called');
    return res.send({
      hasErrors: true,
      data: req.body,
      validationsErrors: errors.array(),
    });
  }
```

I like to use `customValidator`, But i really do not understand how to use validation chain method inside the `customValidator` and how to return/throw the error correctly on each case.

```javascript
const addAccountValidations = [
  body('accountType').custom((value, {req}) => {
    if (value === 'Bank') {
       // Here I do not know, How to use validation chain methods like, `isLength`, `isEmpty` and how return the error correctly with a error message.
    }
  }),
];
```

I really having hard time to crack these issues and and input validation of my different body data structures.

Any help would be greatly appreciated, Thanks gain

**Comment by fedeci** [comment]
> ```js
> const addAccountValidationsTest = oneOf(
>   [
>     body('accountType').equals('Bank'),
>     body('accountData.bankAccountType').equals('normal-account'),
>     body(
>       'accountData.name',
>       'Bank Account name must be minimum 3 and maximum 20 characters'
>     ).isLength({min: 3, max: 20}),
>   ],
>   [
>     body('accountType').equals('Credit Card'),
>     body(
>       'accountData.name',
>       'Credit Card name must be minimum 3 and maximum 20 characters'
>     ).isLength({min: 3, max: 20}),
>   ]
> );
> ```
> 
> * Validation results
> 
> ```js
>   const errors = validationResult(req);
>   if (!errors.isEmpty()) {
>     console.log('Empty if method called');
>     return res.send({
>       hasErrors: true,
>       data: req.body,
>       validationsErrors: errors.array(),
>     });
>   }
> ```
> 
> * Result from for two different body requests returns the same validation error

As mentioned [here](https://github.com/express-validator/express-validator/issues/956), `oneOf` always returns all the errors of all the branches because "it doesn't know" which branch were meant to be run. So if you pass two different bodies but both of them are errored it will return the same error.
Moreover both the requests you sent are missing some params like `accountType` and that's why they fail.

> 
> Other strange behaviour, Which i couldn't understand is result of `validationResult(req)` function call, For ex. both above requests works fine with post man and back-end function send the response without any issue (As shown in the screen shots above). But when I send the same request through the web app, second request with `credit card data body` run smoothly but the first request with `bank account data body` never execute the below if block
> 
> ```js
>  if (!errors.isEmpty()) {
>     console.log('Empty if method called');
>     return res.send({
>       hasErrors: true,
>       data: req.body,
>       validationsErrors: errors.array(),
>     });
>   }
> ```
> 

Well, If that block never runs is because the validation is not failing :)
> I like to use `customValidator`, But i really do not understand how to use validation chain method inside the `customValidator` and how to return/throw the error correctly on each case.
> 
> ```js
> const addAccountValidations = [
>   body('accountType').custom((value, {req}) => {
>     if (value === 'Bank') {
>        // Here I do not know, How to use validation chain methods like, `isLength`, `isEmpty` and how return the error correctly with a error message.
>     }
>   }),
> ];
> ```
> 
> I really having hard time to crack these issues and and input validation of my different body data structures.

You have to [run validators imperatively](https://express-validator.github.io/docs/next/running-imperatively.html), however if you want to use validation chain methods I would use a [separate middleware](https://express-validator.github.io/docs/next/running-imperatively.html#example-validating-with-a-condition) and not a custom validator.
e.g.
```js
  const customValidation = async (req, res, next) => {
    if (req.body.accountType === 'Bank') {
      // let's check req.body.accountData.accountName is a string
      await body('accountData.accountName').isString().run(req);
    }

  // check for errors using validationResult(req) and return an errored response
  }
```

**Comment by janith-dev** [comment]
@fedeci Thanks man, I defined a separate middle-ware, As you suggested above and it resolved my issue, Now all my validations rules are working as intended based on the conditions.

Many thanks, cheers

**Comment by fedeci** [comment]
You're welcome!
