### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by gbagiryan** [express-validator/express-validator#965]
## Describe the bug

When I use express-validator and send multipart/form-data, the notEmpty() check doesn't work. It just takes undefined fields and sets their values as 'undefined'. I use multer to process multipart/form-data, so you'd think it should work. But for some reson it doesn't. Here's a part of code, could someone explain if i'm doing something wrong or if there's a solution to this problem?

## To Reproduce

```js
//CODE EXAMPLE

//Validator
export const validateEditProfile = [
    check('username')
        .notEmpty()
        .withMessage('Username is required'),
    check('email')
        .isEmail()
        .withMessage('Valid Email is required')
];

export const isValidated = (req, res, next) => {
    const errors = validationResult(req);
    if (errors.array().length > 0) {
        return res.status(400).json({errors: errors.array()});
    }
    next();
}

//Routes
import express from 'express';
import authController from '../controllers/authController.js';
import {isValidated, validateEditProfile} from "../validators/authValidators.js";
import requireAuth from "../middleware/authMiddleware.js";
import upload from '../middleware/multerMiddleware.js';

const router = express.Router();

router.patch('/edit_profile', requireAuth, upload.single('profilePicture'), validateEditProfile, isValidated, authController.editProfile_patch);

export default router;

//Controller
const editProfile_patch = async (req, res) => {
    try {
        const {email, username} = req.body;
        const file = req.file;

        await User.findOneAndUpdate({_id: req.user._id}, {
            email,
            username,
            profilePicture: file ? file.path : null
        })

        res.status(200)
        });
    } catch (err) {
        res.status(500).json(err.message);
    }
};
```

## Expected behavior

undefined fields must throw an error

## Current behavior

undefined fields pass as "undefined" strings

## Express-validator version:

- Version: 6.8.0

**Comment by fedeci** [comment]
Hi, multer is converting anything you pass as multipart/form-data to string, so `undefined` becomes `'undefined'` and the latter is no longer an empty value.
It does not depend on express-validator :)

**Comment by gbagiryan** [comment]
> Hi, multer is converting anything you pass as multipart/form-data to string, so `undefined` becomes `'undefined'` and the latter is no longer an empty value.
> It does not depend on express-validator :)

I see, thank you very much for your help. Any chance you could advise how to avoid that issue?

**Comment by fedeci** [comment]
I don't use multer, so I don't know available options, but you can just avoid adding the `username` parameter to the request if it is undefined or null.
