### ISSUE TITLE
Looking for validate that a string does not contain a word

### ISSUE THREAD

**Issue by BZaragoza** [express-validator/express-validator#979]
Hi, i'm working on a basic API and i'm trying to avoid SQL injection by the request body. I heard about contains() method but it's not documentation about it (couldn't find it at least) and I can't find a way to do it. I thought I can do it validating that data doesn't contains words like DROP, DELETE, etc. because I need strings as entries. Do you guys have any idea??

Maybe it's a newbie question but i kinda newbie at this. Thanks for reading.

P.D. I was looking that docs website doesn't have a lot of information, what do you think about a translation project?, I worked in the Node.js repo and it's not difficult at all. Docs in Spanish would look great.

**Comment by gustavohenke** [comment]
Hey!
`contains` is a validator that is pulled from the validator.js dependency. You can check its documentation here: https://github.com/validatorjs/validator.js#validators

And sounds like you want to negate the condition, so I guess `check('field').not.contains(str)` is what you wanna do.

...though there are better ways of treating SQL injection attempts out there (e.g. make sure that you're not passing unescaped strings into your queries).

Hope this helps!

---

> I was looking that docs website doesn't have a lot of information, what do you think about a translation project?, I worked in the Node.js repo and it's not difficult at all. Docs in Spanish would look great.

We use https://docusaurus.io/ which has some support for translations.
However, I'm afraid we don't have the availability to keep translations up-to-date across any extra languages at the moment... tools like Node.js, React, etc have plenty of people using and updating the docs all the time -- unfortunately not our case 😕
