### ISSUE TITLE
select-fields improvements

### ISSUE THREAD

**Issue by fedeci** [express-validator/express-validator#981]
```js
const obj = {
  foo: {
    '4.0': 'foo'
  }
}
```
To validate this we have to use a wildcard symbol in front of the square brackets:
```js
body('foo.*[4.0]').isString()
```
but lodash does not support wildcards and this approach may be confusing.

```js
// Right now using 
body('foo.[4.0]').isString()
// or
body('foo[4.0]').isString()
// results in an error
```

Related issues: #863 
## Describe the solution you'd like
I think we should remove the wildcard requirement and support lodash paths to achieve better compatibility and improve ease of use.

/cc @gustavohenke 

---
edit: this is working from tests. But still can't get it to function from a real express app.

**Comment by gustavohenke** [comment]
Also related to #544 and efbfe3ad9b89f962392bd31d6d2627b6673fca59.

---

> I think we should remove the wildcard requirement and support lodash paths to achieve better compatibility and improve ease of use.
> this is working from tests. But still can't get it to function from a real express app.

How is your test code looking?
I spinned up the following test app and it... worked?

```js
const express = require('express');
const { check, oneOf, matchedData, validationResult } = require('./src');

const app = express();
app.use(express.json());

app.all('/*', [check('foo[1.0]').isInt()], (req, res) => {
  console.log(req.body);
  const errors = validationResult(req);
  return res.json({
    errors: errors.mapped(),
    data: matchedData(req),
  });
});

app.listen(4001);
```

And test request using [httpie](https://httpie.io/):

```
$ http --body :4001 foo:='{"1.0":123}'
{
    "data": {
        "foo": {
            "1.0": 123
        }
    },
    "errors": {}
}
```

**Comment by fedeci** [comment]
I lost my example repo🤦, I will post a snippet of code as soon as I have time to create it again :)

**Comment by gustavohenke** [comment]
I've refactored field selection for v7.0.0.

For anyone seeing this issue, please open a new one if you still find problems with something like that!
