### ISSUE TITLE
Search option in the documentation website

### ISSUE THREAD

**Issue by asingh04** [express-validator/express-validator#985]
## Is your feature request related to a problem? Please describe.
As a new developer using this library, it is very hard to navigate through pages/sections to look into a API/function description. 

## Describe the solution you'd like
It would be better if there was a search feature in the docs website so that I can directly go to that section which explains the API/function I am concerned with

**Comment by fedeci** [comment]
This should be fixed by #857
@gustavohenke should we merge that?
